In [1]:
import numpy as np

In [2]:
N = 3
M = 3

In [3]:
C = np.empty((N,M), dtype='complex')

In [4]:
C

array([[  7.99763982e-316 +7.99841772e-316j,
          1.75158208e-316 +1.70842564e-316j,
          1.70800391e-316 +1.75157734e-316j],
       [  1.93696381e-316 +1.91963910e-316j,
          1.89892115e-316 +1.93696184e-316j,
          1.89892589e-316 +1.92415328e-316j],
       [  1.75297456e-316 +1.75594014e-316j,
          1.71816269e-316 +1.71539316e-316j,
          1.71534770e-316 +1.71546628e-316j]])

In [5]:
for i in range(N):
    for j in range(M):
        C[i,j] = 0

In [6]:
C

array([[ 0.+0.j,  0.+0.j,  0.+0.j],
       [ 0.+0.j,  0.+0.j,  0.+0.j],
       [ 0.+0.j,  0.+0.j,  0.+0.j]])

In [9]:
B = np.zeros(5)

In [10]:
B

array([ 0.,  0.,  0.,  0.,  0.])

In [11]:
B = np.zeros((5,3))

In [12]:
B

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [13]:
B = np.zeros_like(C)

In [14]:
B

array([[ 0.+0.j,  0.+0.j,  0.+0.j],
       [ 0.+0.j,  0.+0.j,  0.+0.j],
       [ 0.+0.j,  0.+0.j,  0.+0.j]])

In [15]:
C.shape

(3L, 3L)

In [16]:
C.shape[0]

3L

In [17]:
C.shape[1]

3L

In [20]:
B = np.zeros(C.shape[0])

In [21]:
B

array([ 0.,  0.,  0.])

In [22]:
B = np.reshape(B, (C.shape[0],1))

In [23]:
B

array([[ 0.],
       [ 0.],
       [ 0.]])