# Title

bla bla bla

inline equation $\sum^{3}_{k=1} \frac{1}{k}$

### Code

In [1]:
import numpy

In [2]:
vector = numpy.array([1, 32.3, 10])

In [3]:
vector

array([  1. ,  32.3,  10. ])

In [4]:
vector+3

array([  4. ,  35.3,  13. ])

In [5]:
vector*2

array([  2. ,  64.6,  20. ])