# Notation

Let $\mathbf{x}$ be a $N \times 1$ vector given by:

$$
\mathbf{x} = \begin{bmatrix}
x_{0} \\
x_{1} \\
\vdots \\
x_{N-1}
\end{bmatrix}_{\, N \times 1} \quad .
$$

Along this course, we use $x_{i}$ or $x[i]$ to define the $i$-th element of $\mathbf{x}$, depending on the context. Finally, the transpose of $\mathbf{x}$ is a $1 \times N$ vector represented by:

$$
\mathbf{x}^{\top} = \begin{bmatrix}
x_{0} & x_{1} & \cdots & x_{N-1}
\end{bmatrix}_{1 \times N} \quad .
$$

In [1]:
import numpy as np

In [2]:
x = np.array([15.4, 23, 7, -65, 1, 0])

In [3]:
x

array([ 15.4,  23. ,   7. , -65. ,   1. ,   0. ])

In [4]:
x[0]

15.4

In [5]:
x[1]

23.0

In [6]:
x[-1]

0.0

In [7]:
x[-2]

1.0

# Pseudo-code

#### Scalar-vector multiplication

$$
\begin{split}
\mathbf{y} &= a \, \mathbf{x} \\
&= \begin{bmatrix} 
    a \, x_{0} \\
    a \, x_{1} \\
    \vdots \\
    a \, x_{N-1}
 \end{bmatrix}
\end{split}
$$

    y = zeros(N)
    for i = 0:N-1
        y[i] = a*x[i]

or, alternatively, by using the *colon notation*,

    y[:] = a*x[:]

In [8]:
a = 0.5

In [9]:
y = a*x

In [10]:
y

array([  7.7,  11.5,   3.5, -32.5,   0.5,   0. ])

In [11]:
x

array([ 15.4,  23. ,   7. , -65. ,   1. ,   0. ])

#### Vector-vector addition

$$
\begin{split}
\mathbf{z} &= \mathbf{x} + \mathbf{y} \\
&= \begin{bmatrix} 
    x_{0} + y_{0} \\
    x_{1} + y_{1} \\
    \vdots \\
    x_{N-1} + y_{N-1}
 \end{bmatrix}
\end{split}
$$

    z = zeros(N)
    for i = 0:N-1
        z[i] = x[i] + y[i]

In [12]:
x = np.arange(7)
y = np.ones(7)*2
z = y + x

In [13]:
x

array([0, 1, 2, 3, 4, 5, 6])

In [14]:
y

array([2., 2., 2., 2., 2., 2., 2.])

In [15]:
z

array([2., 3., 4., 5., 6., 7., 8.])

Be careful! Take a look at the following operation between the vector `x` and a scalar `a`.

In [16]:
a = 2

In [17]:
x + a

array([2, 3, 4, 5, 6, 7, 8])

In [18]:
a + x

array([2, 3, 4, 5, 6, 7, 8])

Is it mathematically sound?

#### Colon notation

The "colon notation" is a handy way of selecting elements in a vector. Let's consider a vector $\mathbf{x}$ defined as follows:

$$
\mathbf{x} = \begin{bmatrix}
x_{0} \\
x_{1} \\
x_{2} \\
x_{3} \\
x_{4} \\
x_{5} \\
x_{6} \\
x_{7}
\end{bmatrix} \quad .
$$

Now, suppose that we want to create a new vector formed by the 3rd, 4th, 5th and 6th elements, i.e., $x_{2}$, $x_{3}$, $x_{4}$ and $x_{5}$. By using the colon notation, we can do it as follows:

$$
\mathbf{x}[2:5:1] = \begin{bmatrix}
x_{2} \\
x_{3} \\
x_{4} \\
x_{5}
\end{bmatrix} \quad .
$$

Notice that the syntax $\mathbf{x}[2:5:1]$ specifies the *start* (index 2), *stop* (index 5) and the *step* (equal to 1). We opted for defining the colon notation in this way because it is equivalent to [slicing of numpy arrays](https://docs.scipy.org/doc/numpy/reference/arrays.indexing.html). 

There is a difference between this notation and the numpy array slicing. To understand this difference, let's create a vector $\mathbf{x}$ with 8 elements.

In [19]:
x = np.array([4, -5, 15.4, 23, 7, -65, 1, 0])

In [26]:
x[-1:-5:-1]

array([  0.,   1., -65.,   7.])

By using the colon notation defined above, the vector $\mathbf{x}[1:3:1]$ formed by the 2nd, 3rd and 4th elements of $\mathbf{x}$ is given by: 

$$
\mathbf{x}[1:3:1] = \begin{bmatrix}
-5 \\
15.4 \\
23
\end{bmatrix} \quad .
$$

Now, by using the numpy array slicing, we obtain:

In [21]:
print(x[1:3:1])

[-5.  15.4]


Could you explain the difference?