# Exemplos de vetores com diferentes shapes

Exemplifica como é o shape de diferentes numpy arrays.

### Importe as coisas

In [1]:
import numpy as np

### Criar vetores

In [2]:
A1 = np.array([[1, 2, 3], 
               [4, 5, 6], 
               [7, 8, 9]])

In [3]:
A1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
A1.shape

(3L, 3L)

In [5]:
np.mean(A1, axis=0)

array([ 4.,  5.,  6.])

In [7]:
A1.mean(axis=0)

array([ 4.,  5.,  6.])

In [8]:
np.mean(A1, axis=1).shape

(3L,)

In [9]:
m1 = np.array([1, 2, 3])

In [10]:
m2 = np.array([[1], [2], [3]])

In [11]:
m1[1]

2

In [12]:
m2[1]

array([2])

In [13]:
m2[1][0]

2