# Notation

Let $\mathbf{x}$ be a $N \times 1$ vector given by:

$$
\mathbf{x} = \begin{bmatrix}
x_{1} \\
x_{2} \\
\vdots \\
x_{N}
\end{bmatrix}_{\, N \times 1} \quad .
$$

Along this course, we use $x_{i}$ or $x[i]$ to define the $i$-th element of $\mathbf{x}$, depending on the context. Finally, the transpose of $\mathbf{x}$ is a $1 \times N$ vector represented by:

$$
\mathbf{x}^{\top} = \begin{bmatrix}
x_{1} & x_{2} & \cdots & x_{N}
\end{bmatrix}_{1 \times N} \quad .
$$

In [1]:
import numpy as np

In [2]:
x = np.arange(10)

In [3]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Basic vector operations

#### Scalar-vector multiplication

$$
\begin{split}
\mathbf{y} &= a \, \mathbf{x} \\
&= \begin{bmatrix} 
    a \, x_{1} \\
    a \, x_{2} \\
    \vdots \\
    a \, x_{N}
 \end{bmatrix}
\end{split}
$$

    for i = 1:N
        y[i] = a*x[i]

or, alternatively, by using the *colon notation*,

    y[:] = a*x[:]

In [4]:
a = 0.5

In [5]:
y = a*x

In [6]:
y

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

#### Vector-vector addition

$$
\begin{split}
\mathbf{z} &= \mathbf{x} + \mathbf{y} \\
&= \begin{bmatrix} 
    x_{1} + y_{1} \\
    x_{2} + y_{2} \\
    \vdots \\
    x_{1} + y_{N}
 \end{bmatrix}
\end{split}
$$

    for i = 1:N
        z[i] = x[i] + y[i]

In [7]:
x = np.arange(7)
y = np.ones(7)*2
z = y + x

In [8]:
x

array([0, 1, 2, 3, 4, 5, 6])

In [9]:
y

array([2., 2., 2., 2., 2., 2., 2.])

In [10]:
z

array([2., 3., 4., 5., 6., 7., 8.])

Be careful! Take a look at the following operation between the vector `x` and a scalar `a`.

In [11]:
a = 2

In [12]:
x + a

array([2, 3, 4, 5, 6, 7, 8])

In [13]:
a + x

array([2, 3, 4, 5, 6, 7, 8])

Is it mathematically sound?

#### Colon notation

The "colon notation" is a handy way of selecting elements in a vector. Let's consider a vector $\mathbf{x}$ defined as follows:

$$
\mathbf{x} = \begin{bmatrix}
x_{1} \\
x_{2} \\
x_{3} \\
x_{4} \\
x_{5} \\
x_{6} \\
x_{7} \\
x_{8}
\end{bmatrix} \quad .
$$

Now, suppose that we want to create a new vector formed by the elements $x_{3}$, $x_{4}$, $x_{5}$ and $x_{6}$. By using the colon notation, we can do it as follows:

$$
\mathbf{x}[3:6:1] = \begin{bmatrix}
x_{3} \\
x_{4} \\
x_{5} \\
x_{6}
\end{bmatrix} \quad .
$$

Notice that the syntax $\mathbf{x}[3:6:1]$ specifies the *start* (index 3), *stop* (index 6) and the *step* (equal to 1). We opted for defining the colon notation in this way because it is equivalent to [slicing of numpy arrays](https://docs.scipy.org/doc/numpy/reference/arrays.indexing.html). 

There is a differnece between this notation and the numpy array slicing. To understand this difference, let's create a vector `x` with 8 elements.

In [21]:
x = np.arange(10, 18)

In [22]:
x

array([10, 11, 12, 13, 14, 15, 16, 17])

Now, let's repeat the example given above: 

In [23]:
x[3:6:1]

array([13, 14, 15])

Could you explain the difference between the array slicing and the colon notation defined above?