# Notation

Let $\mathbf{x}$ be a $N \times 1$ vector given by:

$$
\mathbf{x} = \begin{bmatrix}
x_{1} \\
x_{2} \\
\vdots \\
x_{N}
\end{bmatrix}_{\, N \times 1} \quad .
$$

Along this course, we use $x_{i}$ or $x[i]$ to define the $i$-th element of $\mathbf{x}$, depending on the context. Finally, the transpose of $\mathbf{x}$ is a $1 \times N$ vector represented by:

$$
\mathbf{x}^{\top} = \begin{bmatrix}
x_{1} & x_{2} & \cdots & x_{N}
\end{bmatrix}_{1 \times N} \quad .
$$

# Basic vector operations

In [1]:
import numpy as np

In [2]:
x = np.arange(10)

In [3]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### Scalar-vector multiplication

    for i = 1:N
        y[i] = a*x[i]

or, alternatively, by using the *colon notation*,

    y[:] = a*x[:]

In [5]:
a = 0.5

In [6]:
y = a*x

In [7]:
y

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

#### Scalar-vector addition

    for i = 1:N
        y[i] = a + x[i]

In [8]:
a = 1

In [9]:
y = a + x

In [10]:
y

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
y + x

In [ ]:
y = y + 1

In [ ]:
y

In [ ]:
x/y

This product can be represented as follows:

### Import the required stuff

In [ ]:
import numpy as np
import my_functions as mf

In [ ]:
from numpy.testing import assert_almost_equal as aae

### Input

In [ ]:
a = 4.0
x = np.array([1., 2., 3.])

In [ ]:
print x

### Result computed with my function

In [ ]:
my_result = mf.dumb_scalar_vector(a,x)

In [ ]:
print my_result

### Testing

In [ ]:
# specific input
b = 3.
y = np.ones(4)

print y

In [ ]:
# expected result
expected_result = np.zeros(4) + 3.

In [ ]:
print expected_result

In [ ]:
# my result
my_result = mf.dumb_scalar_vector(b, y)

In [ ]:
my_result

In [ ]:
# compare your result with the expected result
aae(my_result, expected_result, decimal=15)

In [ ]:
# compare your result with an alternative Python implementation
aae(my_result, b*y[:], decimal=15)

In [ ]:
# compare your result with an alternative Python implementation
aae(my_result, b*y, decimal=15)

Take a look at the file `test_my_functions.py`. At the same directory containing the file `my_functions.py`, run the command `python -m pytest test_my_functions.py`.

### Timing the code

In [ ]:
c = 23.
z = np.random.rand(1000)

In [ ]:
%timeit -n 10000 mf.dumb_scalar_vector(c, z)

In [ ]:
%timeit -n 10000 c*z[:]

In [ ]:
%timeit -n 10000 c*z