# Cholesky decomposition

Consider a $N \times N$ matrix $\mathbf{A}$ that is symmetric and [positive definite](http://mathworld.wolfram.com/PositiveDefiniteMatrix.html). Then, it satisfies the following equations:

$$
\mathbf{A} = \mathbf{A}^{\top}
$$

and

$$
\mathbf{x}^{\top} \mathbf{A} \mathbf{x} \gt 0 \: , 
\quad \text{for all nonzero} \: \mathbf{x} \in \mathbb{R}^{N \times N} \: .
$$

In this case, $\mathbf{A}$ satisfies the following theorem (Golub and Van Loan, 2013):

**THEOREM:** If $\mathbf{A} \in \mathbb{R}^{N \times N}$ is symmetric and positive definite, then there exists a unique lower triangular matrix $\mathbf{G} \in \mathbb{R}^{N \times N}$ with positive diagonal entries such that $\mathbf{A} = \mathbf{G} \mathbf{G}^{\top}$.

It can be shown that, given a symmetric positive definite matrix $\mathbf{A}$, the matrix $\mathbf{G}$ can be calculated as follows:

    for j = 1:N

        G[j,j] = A[j,j] - dot(G[j,:j-1],G[j,:j-1])    

        G[j,j] = sqrt(G[j,j])

        G[j+1:,j] = (A[j+1:,j] - dot(G[j+1:,:j-1], G[j,:j-1]))/G[j,j]

The following two images present a "proof" of this algorithm for the particular case in which $N = 4$.

<img src='Cholesky_decomposition_sketch_1.jpg' width = 600>

<img src='Cholesky_decomposition_sketch_2.jpg' width = 600>

### Solving a linear system by applying the Cholesky decomposition

Consider a linear a linaer system

$$
\mathbf{A} \mathbf{x} = \mathbf{y} \: ,
$$

where $\mathbf{A}$ is a symmetric positive definite matrix. In this case, the linear system can be rewritten as follows:

$$
\begin{split}
\mathbf{A} \, &\mathbf{x} &= \mathbf{y} \\
\mathbf{G} \, \mathbf{G}^{\top} &\mathbf{x} &= \mathbf{y}
\end{split} \: .
$$

So, the linear system can be solved in two steps:

$$
\begin{split}
\mathbf{G} \, &\mathbf{w} &= \mathbf{y} \\
\mathbf{G}^{\top} \, &\mathbf{x} &= \mathbf{w}
\end{split} \: .
$$

### Exercise 19

1. Implement the algorithm presented above for calculating the matrix `G` from a symmetric positive definite matrix `A`. The function must receive a symmetric positive definite matrix `A` and return the lower triangular matrix `G`.

2. Solve a linear system by using the calculated `G`. Use the functions implemented previously for solving triangular systems.

3. Test if `A` = `GG`<sup>T</sup>

4. Test your solution of the linear system against the solution obtained by using the routine [`numpy.linalg.solve`](http://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.solve.html)

How to create a symmetric matrix?

In [1]:
import numpy as np

In [2]:
N = 5

A = np.reshape(np.random.rand(N*N), (N,N))

A = np.dot(A.T, A)

In [3]:
print A

[[ 1.78680217  1.20091478  1.56831244  1.04615701  1.53371694]
 [ 1.20091478  0.99696385  1.34769708  0.83271709  1.23109583]
 [ 1.56831244  1.34769708  1.97846671  1.10315765  1.80366976]
 [ 1.04615701  0.83271709  1.10315765  1.34197254  1.30109305]
 [ 1.53371694  1.23109583  1.80366976  1.30109305  2.02298205]]


Remember that a matrix can be symmetric but not necessarily positive definite. In this case, the Cholesky decomposition fails and 