In [1]:
import numpy as np

In [2]:
N = 4

In [3]:
A = np.reshape(np.random.rand(N*N), (N,N))

A = np.dot(A.T, A)

In [4]:
G1 = np.zeros((N,N))

In [5]:
for j in range(N):
    
    G1[j,j] = A[j,j]
    for i in range(j):
        G1[j,j] -= G1[j,i]*G1[j,i]
    G1[j,j] = np.sqrt(G1[j,j])
    
    for i in range(j+1,N):
        G1[i,j] = A[i,j]
        for k in range(j):
            G1[i,j] -= G1[j,k]*G1[i,k]
        G1[i,j] = G1[i,j]/G1[j,j]

In [6]:
A_calc1 = np.dot(G1, G1.T)

In [7]:
np.allclose(A, A_calc1)

True

In [23]:
G2 = np.zeros((N,N))

In [24]:
M = (np.indices((N,N))[1]+11)+(10*np.indices((N,N))[0])

In [25]:
for j in range(N):
    
    G2[j,j] = A[j,j] - np.dot(G2[j,:j],G2[j,:j])    
    
    G2[j,j] = np.sqrt(G2[j,j])
    
    G2[j+1:,j] = (A[j+1:,j] - np.dot(G2[j+1:,:j], G2[j,:j]))/G2[j,j]
    #for i in range(j+1,N):
    #    G2[i,j] = (A[i,j] - np.dot(G2[i,:j],G2[j,:j]))/G2[j,j]
    print M[j+1:,:j],M[j,:j]

[] []
[[31]
 [41]] [21]
[[41 42]] [31 32]
[] [41 42 43]


In [11]:
A_calc2 = np.dot(G2, G2.T)

In [12]:
np.allclose(A, A_calc2)

True

In [13]:
M

array([[11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34],
       [41, 42, 43, 44]])