# Cross product

### Real cross product

Let $\mathbf{x}$ and $\mathbf{y}$ be two $3 \times 1$ real vectors defined as follows:

$$\mathbf{x} = \left[
\begin{array}{c}
x_{0} \\
x_{1} \\
x_{2}
\end{array}
\right]_{\, 3 \times 1}$$

and

$$
\mathbf{y} = \left[
\begin{array}{c}
y_{0} \\
y_{1} \\
y_{2}
\end{array}
\right]_{\, 3 \times 1} \quad .
$$

The [cross product](https://mathworld.wolfram.com/CrossProduct.html) of $\mathbf{x}$ and $\mathbf{y}$ produces a new real vector $\mathbf{z}$ given by:

$$\begin{split}
\mathbf{z} 
& = \mathbf{x} \times \mathbf{y} \\
& = \begin{bmatrix}
x_{1} \, y_{2} - x_{2} \, y_{1} \\
x_{2} \, y_{0} - x_{0} \, y_{2} \\
x_{0} \, y_{1} - x_{1} \, y_{0}
\end{bmatrix}
\end{split}$$

### Complex cross product

Let $\mathbf{x} = \mathbf{x}_{R} + imag \; \mathbf{x}_{I}$ and $\mathbf{y} = \mathbf{y}_{R} + imag \; \mathbf{y}_{I}$ be two $3 \times 1$ complex vectors, where $imag = \sqrt{-1}$ represents the imaginary unit. The cross product of $\mathbf{x}$ and $\mathbf{y}$ results in a complex vector $\mathbf{z}$ given by:

$$
\mathbf{z} = \mathbf{z}_{R} + imag \; \mathbf{z}_{I} \quad ,
$$

where

$$
\mathbf{z}_{R} = \mathbf{x}_{R} \times \mathbf{y}_{R} - \mathbf{x}_{I} \times \mathbf{y}_{I}
$$

and

$$
\mathbf{z}_{I} = \mathbf{x}_{R} \times \mathbf{y}_{I} + \mathbf{x}_{I} \times \mathbf{y}_{R} \quad .
$$

### Exercise

Create the functions below according to `template.py`: 
* `cross_real_dumb`
* `cross_real_numba` 
* `cross_complex` 
    
Create tests for these functions.

In [1]:
import numpy as np

In [2]:
x = np.arange(3) + 1j*np.random.rand(3)

In [3]:
x

array([0.+0.61928752j, 1.+0.11261152j, 2.+0.81799953j])

In [4]:
y = np.ones(3) + 1j*np.random.rand(3)

In [5]:
y

array([1.+0.73693569j, 1.+0.93253906j, 1.+0.84998989j])

In [6]:
np.cross(x,y)

array([-0.33290214-1.72047624j,  1.92357509+1.67258339j,
       -1.49452236-0.23025968j])

In [7]:
z_R  = np.cross(x.real, y.real)
z_R -= np.cross(x.imag, y.imag)
z_I  = np.cross(x.real, y.imag)
z_I += np.cross(x.imag, y.real)

In [8]:
np.allclose(np.cross(x,y), z_R + 1j*z_I)

True