# Diagonal matrices

Consider a $N \times N$ matrix $\mathbf{A}$ given by:

$$\mathbf{A} 
= \left[ \begin{array}{ccc}
a_{11} &  &  \\
 & \ddots &  \\
 &  & a_{NN}
\end{array} \right] \: .
$$

This matrix is called **diagonal**. Only the diagonal elements are different from zero. In this case, most of the matrix elements are zero and, consequently, do not need to be stored. Such matrices can be represented by a $N \times 1$ vector defined as follows:

$$diag \left( \mathbf{A} \right) = 
\left[ \begin{array}{c}
a_{11} \\
\vdots \\
a_{NN}
\end{array} \right] \: .
$$

Let $\mathbf{x}$ be a $N \times 1$ vector given by:

$$\mathbf{x} = 
\left[ \begin{array}{c}
x_{1} \\
\vdots \\
x_{N}
\end{array} \right] \: .
$$

In this case, it can be easily shown that

$$
\mathbf{A} \mathbf{x} = diag \left( \mathbf{A} \right) \circ \mathbf{x} \: .
$$

Now, consider a full $L \times N$ matrix $\mathbf{B}$ and a full $N \times M$ matrix $\mathbf{C}$. It can be show that the product $\mathbf{D} = \mathbf{B} \mathbf{A}$ can be calculated as follows:

    for j = 1:N
        D[:,j] = B[:,j]*A[j,j]

Similarly, it can be shown that the product $\mathbf{E} = \mathbf{A} \mathbf{C}$ can be calculated as follows:

    for i = 1:N
        E[i,:] = C[i,:]*A[i,i]

### Exercise 9

Validate these two algorithms according to the steps below:

1. Create a function that calculates the product `BA`. The function must receive the full matrix `B` and the diagonal of `A`.
2. Create a function that calculates the product `AC`. The function must receive the diagonal of `A` and the full matrix `C`.
3. Use the `code-template.ipynb` for testing the two functions against the Python code shown below:

In [2]:
import numpy as np

Create a matrix by using, for example, the function [`numpy.diag`](http://docs.scipy.org/doc/numpy/reference/generated/numpy.diag.html)

In [7]:
A = np.diag(np.linspace(20., 100., 5))

In [8]:
A

array([[  20.,    0.,    0.,    0.,    0.],
       [   0.,   40.,    0.,    0.,    0.],
       [   0.,    0.,   60.,    0.,    0.],
       [   0.,    0.,    0.,   80.,    0.],
       [   0.,    0.,    0.,    0.,  100.]])

Create two matrices by using, for example, the function [`numpy.random.rand`](http://docs.scipy.org/doc/numpy/reference/generated/numpy.random.rand.html#numpy.random.rand)

In [9]:
B = np.random.rand(4,A.shape[0])

In [15]:
print B

[[ 0.09482231  0.92140011  0.6288456   0.57622648  0.54855956]
 [ 0.76323911  0.09369195  0.47751263  0.39128319  0.89209618]
 [ 0.46296025  0.8084192   0.97832675  0.71180099  0.8685995 ]
 [ 0.45131512  0.19583903  0.70030389  0.85515572  0.12601004]]


In [11]:
C = np.random.rand(A.shape[1], 3)

In [16]:
print C

[[ 0.72286696  0.01768515  0.32915472]
 [ 0.55605813  0.76311434  0.13326642]
 [ 0.85481818  0.59127274  0.57808891]
 [ 0.88191343  0.106508    0.8190515 ]
 [ 0.32797104  0.39916993  0.26937097]]


Calculate the products `BA` and `AC` by using the [`numpy.dot`](http://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html)

In [13]:
D = np.dot(B, A)

In [17]:
print D

[[  1.89644629  36.85600448  37.73073586  46.09811868  54.85595641]
 [ 15.26478223   3.74767792  28.65075794  31.30265541  89.20961816]
 [  9.25920492  32.33676807  58.69960504  56.9440796   86.85994974]
 [  9.0263024    7.83356132  42.01823315  68.41245753  12.6010038 ]]


In [18]:
E = np.dot(A, C)

In [19]:
print E

[[ 14.45733911   0.35370295   6.58309433]
 [ 22.24232506  30.52457346   5.33065668]
 [ 51.28909107  35.47636436  34.68533476]
 [ 70.55307437   8.52063962  65.52412004]
 [ 32.79710417  39.91699274  26.93709724]]
