# Diagonal matrices - part 1

Consider an $N \times N$ matrix $\mathbf{D}$ given by:

$$\mathbf{D} 
= \left[ \begin{array}{ccc}
d_{00} &  &  \\
 & \ddots &  \\
 &  & d_{N-1N-1}
\end{array} \right] \: .
$$

This matrix is called **diagonal**. Only the diagonal elements are different from zero. In this case, most of the matrix elements are zero and, consequently, do not need to be stored. Such matrices can be represented by an $N \times 1$ vector defined as follows:

$$\mathbf{d} = diag \left( \mathbf{D} \right) = 
\left[ \begin{array}{c}
d_{00} \\
\vdots \\
d_{N-1N-1}
\end{array} \right] \: .
$$

Let $\mathbf{x}$ be an $N \times 1$ vector given by:

$$\mathbf{x} = 
\left[ \begin{array}{c}
x_{0} \\
\vdots \\
x_{N-1}
\end{array} \right] \: .
$$

In this case, it can be easily shown that

$$
\mathbf{D} \mathbf{x} = \mathbf{d} \circ \mathbf{x} \: ,
$$

which represents the Hadamard (or entrywise) product of $\mathbf{d}$ and $\mathbf{x}$.

Now, consider a full $N \times N$ matrix $\mathbf{B}$. It can be show that the resultant matrix $\mathbf{C} = \mathbf{D} \mathbf{B}$ can be calculated as follows:

    for i = 0:N-1
        C[i, :] = d[i]*B[i,:]

Similarly, it can be shown that the product $\mathbf{E} = \mathbf{B} \mathbf{D}$ can be calculated as follows:

    for j = 0:N-1
        E[:,j] = d[j]*B[:,j]

### Exercise

Deduce the pseudo-codes shown above for computing $\mathbf{D}\mathbf{x}$, $\mathbf{D}\mathbf{B}$ and $\mathbf{B}\mathbf{D}$.

#### Creating the diagonal matrix $\mathbf{D}$ and the vector $\mathbf{d}$ containing its diagonal elements

In [1]:
import numpy as np

Create a vector `d` by using, for example, the function [`numpy.random.rand`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.random.rand.html)

In [2]:
d = np.random.rand(5)

In [3]:
d

array([0.3063378 , 0.56646481, 0.26361068, 0.16406177, 0.47066708])

Now, create the diagonal matrix `D` by using the routine [`numpy.diag`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.diag.html)

In [4]:
D = np.diag(d)

In [5]:
D

array([[0.3063378 , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.56646481, 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.26361068, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.16406177, 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.47066708]])

You can also extract the diagonal of a given matrix by using the routine [`numpy.diag`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.diag.html)

In [6]:
np.diag(D)

array([0.3063378 , 0.56646481, 0.26361068, 0.16406177, 0.47066708])