#Eliminação de Gauss com pivotamento parcial

Um sistema linear $N \times N$ pode ser transformado, de forma iterativa, em um sistema triangular equivalente por meio da Eliminação de Gauss. Isto é, o sistema linear

$$\mathbf{A} \, \mathbf{x}  = \mathbf{y}$$

é transformado no sistema triangular equivalente

$$\mathbf{B} \, \mathbf{x} = \mathbf{z} \: ,$$

com a mesma solução $\mathbf{x}$ do sistema original.

Tal como visto anteriormente, a transformação do sistema linear original para o sistema triangular equivalente é feita de forma iterativa, por meio de sucessivas transformações lineares do tipo:

$$
\begin{array}{ccccc}
\mathbf{A}^{(0)} = \mathbf{A} & & & \mathbf{y}^{(0)} = \mathbf{y} \\\\
\mathbf{A}^{(1)} = \mathbf{G}^{(1)} \mathbf{A}^{(0)} & & &
\mathbf{y}^{(1)} = \mathbf{G}^{(1)} \mathbf{y}^{(0)} \\\\
\mathbf{A}^{(2)} = \mathbf{G}^{(2)} \mathbf{A}^{(1)} & & &
\mathbf{y}^{(2)} = \mathbf{G}^{(2)} \mathbf{y}^{(1)} \\\\
\vdots & & & \vdots \\\\
\mathbf{A}^{(N-2)} = \mathbf{G}^{(N-2)} \mathbf{A}^{(N-3)} & & &
\mathbf{y}^{(N-2)} = \mathbf{G}^{(N-2)} \mathbf{y}^{(N-3)} \\\\
\mathbf{B} = \mathbf{G}^{(N-1)} \mathbf{A}^{(N-2)} & & &
\mathbf{z} = \mathbf{G}^{(N-1)} \mathbf{y}^{(N-2)} \\\\
\end{array} \: ,$$

em que $\mathbf{G}^{(k)}$ é a **Transformação de Gauss** da k-ésima iteração. Esta matriz depende do **vetor de Gauss** $\mathbf{t}^{(k)}$, cujo i-ésimo elemento é definido como:

$t_{i}^{(k)} = \begin{cases} 0 & \quad \text{if } i \le k \\\\ \dfrac{a^{(k-1)}_{ik}}{a^{(k-1)}_{kk}} & \quad \text{if } i \gt k\\ \end{cases} \: ,$

em que $a^{(k-1)}_{ij}$ é o elemento $ij$ da matriz $\mathbf{A}^{(k-1)}$. Observe que, para calcular o elemento $t^{(k)}_i$, é necessário que $a^{(k-1)}_{kk} \ne 0$. Contudo, é possível que $a^{(k-1)}_{kk} = 0$ e, consequentemente, que o vetor de Gauss não possa ser calculado. Valores $a^{(k-1)}_{kk} \approx 0$ também são um problema porque podem produzir resultados espúrios. Para exemplificar este problema, vamos considerar o sistema linear abaixo:

In [1]:
import numpy as np

In [2]:
A = np.array([[1.e-6, 2.],
              [1.e-2, 1.e-3]])

In [3]:
print A

[[  1.00000000e-06   2.00000000e+00]
 [  1.00000000e-02   1.00000000e-03]]


In [4]:
y = np.reshape((7.*A[:,0] + 0.15*A[:,1]),(2,1))

In [5]:
print y

[[ 0.300007]
 [ 0.07015 ]]


A solução deste sistema é dada por:

In [6]:
x = np.array([[7.],
              [0.15]])

In [7]:
print x

[[ 7.  ]
 [ 0.15]]


Neste caso, apenas uma iteração é necessária para transformar este sistema no sistema equivalente. Neste caso, a Transformação de Gauss é dada por:

In [8]:
I = np.identity(2)

In [9]:
u = np.array([[1.],
              [0.]])

In [10]:
t = np.array([[0.],
              [A[1][0]/A[0][0]]])

In [11]:
G = I - t*u.T

In [12]:
print G

[[  1.00000000e+00   0.00000000e+00]
 [ -1.00000000e+04   1.00000000e+00]]


A aplicação desta Transformação de Gauss resulta na seguinte matriz triangular:

In [13]:
B = G.dot(A)
z = G.dot(y)

In [14]:
print B

[[  1.00000000e-06   2.00000000e+00]
 [  0.00000000e+00  -1.99999990e+04]]


In [15]:
print y

[[ 0.300007]
 [ 0.07015 ]]


A solução do sistema triangular equivalente é dada por:

In [16]:
w = np.zeros((2,1))
w[1] = y[1]/B[1,1]
w[0] = (y[0] - B[0,1]*w[1])/B[0,0]

In [17]:
print w

[[  3.00014015e+05]
 [ -3.50750018e-06]]


Note que esta solução é muito diferente daquela do sistema original

In [18]:
print x

[[ 7.  ]
 [ 0.15]]


Neste exemplo, a Transformação de Gauss calculada a partir dos elementos de $\mathbf{A}$ envolve uma divisão por um número $a_{11} \approx 0$ e isso faz com que a solução do sistema triangular seja espúria. Para contornar este problema, basta fazer uma permutação das linhas de $\mathbf{A}$ e também do vetor $\mathbf{y}$. Esta permutação gera uma nova matriz $\tilde{\mathbf{A}}$ e um novo vetor $\tilde{\mathbf{y}}$. Ao fazer a permutação, o elemento $\tilde{a}_{11}$ da matriz $\tilde{\mathbf{A}}$ deixa de ser tão próximo a zero. Contudo, o que acontece com a solução do sistema linear? Vamos exemplificar esta operação abaixo:

#####Permutação das linhas de $\mathbf{A}$ e $\mathbf{y}$

In [19]:
A_til = A[::-1,:]

In [20]:
print A_til

[[  1.00000000e-02   1.00000000e-03]
 [  1.00000000e-06   2.00000000e+00]]


In [21]:
y_til = y[::-1]

In [22]:
print y_til

[[ 0.07015 ]
 [ 0.300007]]


#####Cálculo do novo vetor de Gauss $\tilde{\mathbf{t}}$ e da nova Transformação de Gauss $\tilde{\mathbf{G}}$

In [23]:
t_til = np.array([[0.],
                 [A_til[1][0]/A_til[0][0]]])

In [24]:
G_til = I - t_til*u.T

In [25]:
B_til = G_til.dot(A_til)
z_til = G_til.dot(y_til)

In [26]:
print B_til

[[  1.00000000e-02   1.00000000e-03]
 [  0.00000000e+00   1.99999990e+00]]


In [27]:
print z_til

[[ 0.07015   ]
 [ 0.29999998]]


#####Solução do sistema triangular equivalente

In [28]:
w_til = np.zeros((2,1))
w_til[1] = y_til[1]/B_til[1,1]
w_til[0] = (y_til[0] - B_til[0,1]*w[1])/B_til[0,0]

In [29]:
print w_til

[[ 7.01500035]
 [ 0.15000351]]


Note que esta solução é muito próxima da solução do sistema original

In [30]:
print x

[[ 7.  ]
 [ 0.15]]


Matematicamente, a permutação das linhas de uma matriz ou de um vetor é o resultado da premultiplicação por uma matriz $\mathbf{P}$. Esta matriz é convenientemente denominada **matriz permutação** e será explicada no próximo IPython Notebook.