# Gaussian elimination - pivoting

The [Gaussian elimination](https://en.wikipedia.org/wiki/Gaussian_elimination) iteratively transforms an unstructured linear system $\mathbf{A}\mathbf{x} = \mathbf{y}$ into an equivalent triangular system $\mathbf{B}\mathbf{x} = \mathbf{z}$ having the same solution $\mathbf{x}$. As pointed out in the previous class, the **pivots** needed for computating the **Gauss multipliers** must be nonzero. The presence of small pivots produces arbitrarily poor results, even for well-conditioned problems, showing that Gauss elimination is an unstable method (Golub and Van Loan, 2013).

To avoid the division by small pivots and guarantee that the pivot has the largest absolute value, we may always swap the lines. 

Let's recall the linear system $\mathbf{A}\mathbf{x} = \mathbf{y}$ presented in the previous class:

In [1]:
import numpy as np

In [2]:
A = np.array([[2.,1.,-1.],
              [-3.,-1.,2.],
              [-2.,1.,2.]])

In [3]:
y = np.array([[8.],
              [-11.],
              [-3.]])

The solution of this system is given by:

In [4]:
x = np.linalg.solve(A,y)

In [5]:
print x

[[ 2.]
 [ 3.]
 [-1.]]


This system can be solved by Gaussian elimination as follows:

In [6]:
I = np.identity(3)

**Iteration k = 1:**

In [7]:
u = np.array([[1.],
              [0.],
              [0.]])

In [8]:
t = np.array([[0.],
              [A[1][0]/A[0][0]],
              [A[2][0]/A[0][0]]])

In [9]:
A1 = (I - t*u.T).dot(A)

In [10]:
A1

array([[ 2. ,  1. , -1. ],
       [ 0. ,  0.5,  0.5],
       [ 0. ,  2. ,  1. ]])

In [11]:
y1 = (I - t*u.T).dot(y)

In [12]:
y1

array([[ 8.],
       [ 1.],
       [ 5.]])

Notice that, in this case, the pivot of the next Gauss transform is `0.5`. The pivot is not a small number. However, let's apply the partial pivoting for illustrating the procedure and showing that it does not change the final result.

In this case, we interchange the third and second rows/elements of `A1`/`y1`. This is equivalent to premultiply `A1` and `y1` by the following matrix:

In [13]:
P1 = np.identity(3)[[0,2,1]]

print P1

[[ 1.  0.  0.]
 [ 0.  0.  1.]
 [ 0.  1.  0.]]


In [14]:
A1 = np.dot(P1, A1)
y1 = np.dot(P1, y1)

In [15]:
print A1

[[ 2.   1.  -1. ]
 [ 0.   2.   1. ]
 [ 0.   0.5  0.5]]


In [16]:
print y1

[[ 8.]
 [ 5.]
 [ 1.]]


Notice that this row permutation changed the pivot from `0.5` to `2`.

**Iteration 2:**

In [17]:
u = np.array([[0.],
              [1.],
              [0.]])

In [18]:
t = np.array([[0.],
              [0.],
              [A1[2][1]/A1[1][1]]])

In [19]:
B = (I - t*u.T).dot(A1)

In [20]:
B

array([[ 2.  ,  1.  , -1.  ],
       [ 0.  ,  2.  ,  1.  ],
       [ 0.  ,  0.  ,  0.25]])

In [21]:
z = (I - t*u.T).dot(y1)

In [22]:
z

array([[ 8.  ],
       [ 5.  ],
       [-0.25]])

Solution of this equivalent triangular system:

In [23]:
print np.linalg.solve(B,z)

[[ 2.]
 [ 3.]
 [-1.]]


Solution of the original system:

In [24]:
print np.linalg.solve(A,y)

[[ 2.]
 [ 3.]
 [-1.]]


Now, our equivalent triangular system was iteratively calculated according to the following algorithm:

$$
\begin{array}{ccccc}
\mathbf{A}^{(0)} = \mathbf{A} & & & \mathbf{y}^{(0)} = \mathbf{y} \\\\
\mathbf{A}^{(1)} = \left(\mathbf{I} - \mathbf{M}^{(1)}\right) \mathbf{P}^{(1)}\mathbf{A}^{(1)} & & &
\mathbf{y}^{(1)} = \left(\mathbf{I} - \mathbf{M}^{(1)}\right) \mathbf{P}^{(1)}\mathbf{y}^{(1)} \\\\
\mathbf{A}^{(2)} = \left(\mathbf{I} - \mathbf{M}^{(2)}\right) \mathbf{P}^{(2)}\mathbf{A}^{(2)} & & &
\mathbf{y}^{(2)} = \left(\mathbf{I} - \mathbf{M}^{(2)}\right) \mathbf{P}^{(2)}\mathbf{y}^{(2)}
\end{array} \: ,$$

where $\mathbf{P}^{(k)}$ is the permutation matrix used to interchange the rows and perform the partial pivoting.