# Gaussian elimination - introduction

Consider the following linear system:

$$\mathbf{A} \, \mathbf{x}  = \mathbf{y}\: ,$$

where $\mathbf{A}$ is a $N \times N$ unstructured matrix given by

$$\mathbf{A} = \left[
\begin{array}{cccccc}
a_{11} & a_{12} & a_{13} & a_{14} & \cdots & a_{1M} \\
a_{21} & a_{22} & a_{23} & a_{24} & \cdots & a_{2M} \\
a_{31} & a_{32} & a_{33} & a_{34} & \cdots & a_{3M} \\
a_{41} & a_{42} & a_{43} & a_{44} & \cdots & a_{4M} \\
\vdots & \vdots & \vdots & \vdots & \ddots & \vdots \\
a_{N1} & a_{N2} & a_{N3} & a_{N4} & \cdots & a_{NN}
\end{array}
\right]_{\, N \times N} \: ,$$

$$\mathbf{y} = \left[
\begin{array}{c}
y_{1} \\
y_{2} \\
\vdots \\
y_{N}
\end{array}
\right]_{\,  \times 1}$$

and

$$\mathbf{x} = \left[
\begin{array}{c}
x_{1} \\
x_{2} \\
\vdots \\
x_{N}
\end{array}
\right]_{\, N \times 1} \: .$$

This is a **square and unstructured linear system** because $\mathbf{A}$ is a general square matrix that is not diagonal, triangular, banded or any other type of structured matrix. 

How to solve this linear system? At this part of the course, we only know how to solve diagonal and triangular systems. It would be useful if this system were tranformed into an equivalent triangular system having the same solution $\mathbf{x}$ as the unstructured system presented above. We say that this new system is equivalent because the solution is the same and triangular because its matrix is upper triangular.

[**Gaussian elimination**](https://en.wikipedia.org/wiki/Gaussian_elimination) is a numerical procedure applied for transforming a square and unstructured system into this equivalent triangular system, which can be represented as follows: 

$$\mathbf{B} \, \mathbf{x} = \mathbf{z} \: ,$$

where

$$\mathbf{B} = \left[
\begin{array}{ccccc}
b_{11} & b_{12} & b_{13} & b_{14} & \cdots & b_{1M} \\
0 & b_{22} & b_{23} & b_{24} & \cdots & b_{2M} \\
0 & 0 & b_{33} & b_{34} & \cdots & b_{3M} \\
0 & 0 & 0 & b_{44} & \cdots & b_{4M} \\
\vdots & \vdots & \vdots &  & \ddots & \vdots \\
0 & 0 & 0 & 0 & \cdots & b_{NN}
\end{array}
\right]_{\, N \times N}$$

and

$$\mathbf{z} = \left[
\begin{array}{c}
z_{1} \\
z_{2} \\
\vdots \\
z_{N}
\end{array}
\right]_{\, N \times 1} \: .$$

As pointed out before, this equivalent system has the same solution $\mathbf{x}$ as the unstructured system. The most striking observation to emerge from [Gaussian elimination](https://en.wikipedia.org/wiki/Gaussian_elimination) is that it transforms an unstructured linear system into a triangular system, which can be easily solved.

This transformation is based on three row transformations that do not change the solution of the linear system: **swapping the positions of two rows**, **multiplying a row by a nonzero scalar** and **adding to one row a scalar multiple of another**. The cells below examplify these transformations.

Let's consider a linear system `Ax = y` given by:

In [32]:
import numpy as np

In [33]:
A = np.array([[1.,3.,2.],
              [7.,4.,9.],
              [8.,6.,5.]])

In [34]:
y = np.array([5.23, 6.45, 1.67])

The solution of this system is given by:

In [35]:
x = np.linalg.solve(A,y)

In [36]:
print x

[-1.70556701  1.34958763  1.44340206]


### Solution obtained by **swapping the positions of two rows**

Let's generating a matrix `T` and a vector `t` by swapping, respectively, the first two rows of `A` and the first two elements of `y`:

In [37]:
T = A[[1,0,2]]
t = y[[1,0,2]]

In [38]:
print A
print '\n'
print T

[[ 1.  3.  2.]
 [ 7.  4.  9.]
 [ 8.  6.  5.]]


[[ 7.  4.  9.]
 [ 1.  3.  2.]
 [ 8.  6.  5.]]


In [39]:
print y
print '\n'
print t

[ 5.23  6.45  1.67]


[ 6.45  5.23  1.67]


This row swapping is equivalent to premultiplying `A` and `y` by a permutation matrix `P` given by

In [40]:
P = np.identity(3)[[1,0,2]]
print P

[[ 0.  1.  0.]
 [ 1.  0.  0.]
 [ 0.  0.  1.]]


In [41]:
T = np.dot(P,A)
t = np.dot(P,y)

In [42]:
print A
print '\n'
print T

[[ 1.  3.  2.]
 [ 7.  4.  9.]
 [ 8.  6.  5.]]


[[ 7.  4.  9.]
 [ 1.  3.  2.]
 [ 8.  6.  5.]]


In [43]:
print y
print '\n'
print t

[ 5.23  6.45  1.67]


[ 6.45  5.23  1.67]


The solution of the system `Tx = t` is given by:

In [44]:
x1 = np.linalg.solve(T,t)

In [45]:
print x1

[-1.70556701  1.34958763  1.44340206]


### Solution obtained by **multiplying a row by a nonzero scalar**

Now, let's generating a matrix `T` and a vector `t` by multiplying, respectively, the second row of `A` and the second element of `y` by `3`

In [46]:
T = np.dot(np.diag([1.,3.,1.]), A)
t = np.dot(np.diag([1.,3.,1.]), y)

In [47]:
print A
print '\n'
print T

[[ 1.  3.  2.]
 [ 7.  4.  9.]
 [ 8.  6.  5.]]


[[  1.   3.   2.]
 [ 21.  12.  27.]
 [  8.   6.   5.]]


In [48]:
print y
print '\n'
print t

[ 5.23  6.45  1.67]


[  5.23  19.35   1.67]


Notice that this operation is equivalent to premultiplying `A` and `y` by the matrix

In [49]:
np.diag([1.,3.,1.])

array([[ 1.,  0.,  0.],
       [ 0.,  3.,  0.],
       [ 0.,  0.,  1.]])

The solution of this system is given by:

In [50]:
x2 = np.linalg.solve(T,t)

In [51]:
print x2

[-1.70556701  1.34958763  1.44340206]


### Solution obtained by **adding to one row a scalar multiple of another**

Finally, let's generating a matrix `T` by adding the double of the first row of `A` to the third row of `A`. Let's also generating a vector `t` by adding the double of the first element of `y` to the third element of `y`

In [52]:
Q = np.diag([1.,1.,1.])
Q[2,0] += 2.
T = np.dot(Q, A)
t = np.dot(Q, y)

In [53]:
print A
print '\n'
print T

[[ 1.  3.  2.]
 [ 7.  4.  9.]
 [ 8.  6.  5.]]


[[  1.   3.   2.]
 [  7.   4.   9.]
 [ 10.  12.   9.]]


In [54]:
print y
print '\n'
print t

[ 5.23  6.45  1.67]


[  5.23   6.45  12.13]


Notice that this operation is equivalent to premultiplying `A` and `y` by the matrix

In [55]:
print Q

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 2.  0.  1.]]


The solution of this system is given by:

In [56]:
x3 = np.linalg.solve(T,t)

In [57]:
print x3

[-1.70556701  1.34958763  1.44340206]


### Comparison between the solutions `x`, `x1`, `x2` and `x3`

In [58]:
print x

[-1.70556701  1.34958763  1.44340206]


In [59]:
print x1

[-1.70556701  1.34958763  1.44340206]


In [60]:
print x2

[-1.70556701  1.34958763  1.44340206]


In [61]:
print x3

[-1.70556701  1.34958763  1.44340206]
