# Linear systems - introduction

Consider the following set of equations:

$$\begin{array}{r}
       x_{0} & + & 5   \, x_{1} & - & 5.3 \, x_{2} & = & y_{0} \\
2.4 \, x_{0} & - & 2   \, x_{1} & + &        x_{2} & = & y_{1} \\
7.8 \, x_{0} & - & 4.1 \, x_{1} & + & 6.4 \, x_{2} & = & y_{2} \\
\end{array} \: .
$$

Notice that $y_{i}$, $i = 0, 1, 2$, are [linear combinations](https://en.wikipedia.org/wiki/Linear_combination) of the variables $x_{0}$, $x_{1}$, $x_{2}$. It means that the derivative of $y_{i}$, $i = 0, 1, 2$, with respect to any variable $x_{0}$, $x_{1}$, $x_{2}$ does not depend on the variables $x_{0}$, $x_{1}$, $x_{2}$. For example, the derivative of $y_{1}$ with respect to $x_{2}$ is equal to $1$.

This set of equations can be written in matrix notation as follows:

$$\mathbf{A}\, \mathbf{x} = \mathbf{y} \: ,$$

where

$$\mathbf{A} = \left[
\begin{array}{ccc}
1 & 5 & -5.3 \\
2.4 & -2 & 1 \\
7.8 & -4.1 & 6.4
\end{array}
\right] \: ,$$

$$\mathbf{y} = \left[
\begin{array}{c}
y_{0} \\
y_{1} \\
y_{2}
\end{array}
\right]$$

and

$$\mathbf{x} = \left[
\begin{array}{c}
x_{0} \\
x_{1} \\
x_{2}
\end{array}
\right] \: .$$

This equation is commonly called linear system of equations or simply **linear system**.

Linear systems are very common in geophysical problems. In general, $\mathbf{y}$ contains the geophysical data (or observables), e.g., gravity data, total-field anomaly data, seismic travel times, horizontal and vertical components of the electrical and magnetic fields, etc. Then, $\mathbf{y}$ is usually known. Similarly, the matrix $\mathbf{A}$ also contains observables (e.g., time, distance, depth to the top of a geological body, etc.). On the other hand, the vector $\mathbf{x}$ usually contains the unkowns, which are the parameters to be estimated by solving the linear system. For example, they can represent a magnetic moment distribution, density contrast distribution, etc. 

Therefore, solving a linear system means determining the vector $\mathbf{x}$ from the values of $\mathbf{A}$ and $\mathbf{y}$. The complexity of the algorithm used for solving a linear system depends mainly on the structure of the matrix $\mathbf{A}$.
The [`numpy.linalg.solve`](https://numpy.org/doc/stable/reference/generated/numpy.linalg.solve.html) provides a routine to solve linear systems, for example. The cells below show an application of this routine.

In [1]:
import numpy as np

Let `A` and `y` be a matrix and a vector defined as follows:

In [2]:
A = np.array([[1.,5.,-5.3],
              [2.4,-2.,1.],
              [7.8,-4.1,6.4]])
y = np.array([42., 11., 67.])

The solution of the linear system `Ax = y` is given by:

In [3]:
x = np.linalg.solve(A,y)

In [4]:
print(x)

[11.08129511  9.23845874  2.88180921]


How to verify if x is a true solution?

In [5]:
y_calc = np.dot(A, x)

In [6]:
print(y_calc)

[42. 11. 67.]


In [7]:
print(y)

[42. 11. 67.]
