# Kronecker product

#### References

* Magnus, J. R. and H. Neudecker (2007), Matrix differential calculus with applications in statistics and econometrics, 3rd edition, John Wiley & Sons, ISBN 0-471-98632-1.

* Jain, A. K. (1989), Fundamentals of Digital Image Processing, Prentice Hall, ISBN 978-0-13-336165-0.

* Horn, R. A. and C. R. Johnson, (1991), Topics in Matrix Analysis, Cambridge University Press, ISBN 978-0-521-46713-1.

Let $\mathbf{A}$ and $\mathbf{B}$ be, respectively, $N \times M$ and $L \times P$ matrices given by:

$$\mathbf{A} 
= \begin{bmatrix}
a_{00} & \cdots & a_{0(M-1)} \\
\vdots &        & \vdots \\
a_{(N-1)0} & \cdots & a_{(N-1)(M-1)}
\end{bmatrix}_{N \times M} \:
$$

and

$$\mathbf{B} 
= \begin{bmatrix}
b_{00} & \cdots & b_{0(P-1)} \\
\vdots &        & \vdots \\
b_{(L-1)0} & \cdots & b_{(L-1)(P-1)}
\end{bmatrix}_{L \times P} \: .
$$

The [Kronecker product](https://en.wikipedia.org/wiki/Kronecker_product) of $\mathbf{A}$ and $\mathbf{B}$, denoted as $\mathbf{A} \otimes \mathbf{B}$, is an $NL \times MP$ matrix given by:

<a id='eq1'></a>
$$
\mathbf{A} \otimes \mathbf{B}
= \begin{bmatrix}
a_{00} \, \mathbf{B} & \cdots & a_{0(M-1)} \, \mathbf{B} \\
\vdots &        & \vdots \\
a_{(N-1)0} \, \mathbf{B} & \cdots & a_{(N-1)(M-1)} \, \mathbf{B}
\end{bmatrix}_{\, NL \, \times \, MP} \: . \tag{1}
$$

Notice that $\mathbf{A} \otimes \mathbf{B}$ ([equation 1](#eq1)) is a block matrix formed by $N \times M$ blocks, each one with $L \times P$ elements.

In [1]:
import numpy as np
from numpy.linalg import multi_dot

In [2]:
N = 3
M = 4
L = 2
P = 3

In [3]:
A = np.random.rand(N, M)
B = np.random.rand(L, P)

In [4]:
print(A)

[[0.50357681 0.96973804 0.73056838 0.87027423]
 [0.06757006 0.89455737 0.24410583 0.69944685]
 [0.01029108 0.51506587 0.79679306 0.57282245]]


In [5]:
print(B)

[[0.21283349 0.03818903 0.58210066]
 [0.74049306 0.0851349  0.78176005]]


In [6]:
A_kron_B = np.kron(A, B)

In [7]:
A_kron_B.shape

(6, 12)

In [8]:
print(A_kron_B)

[[1.07178011e-01 1.92311100e-02 2.93132393e-01 2.06392735e-01
  3.70333555e-02 5.64485156e-01 1.55489421e-01 2.78996982e-02
  4.25264340e-01 1.85223505e-01 3.32349291e-02 5.06587207e-01]
 [3.72895129e-01 4.28719617e-02 3.93676227e-01 7.18084286e-01
  8.25585523e-02 7.58102453e-01 5.40980815e-01 6.21968671e-02
  5.71129171e-01 6.44432026e-01 7.40907108e-02 6.80345621e-01]
 [1.43811717e-02 2.58043503e-03 3.93325759e-02 1.90391770e-01
  3.41622785e-02 5.20722436e-01 5.19538978e-02 9.32216517e-03
  1.42094168e-01 1.48865717e-01 2.67111971e-02 4.07148475e-01]
 [5.00351593e-02 5.75257028e-03 5.28235721e-02 6.62413520e-01
  7.61580531e-02 6.99329207e-01 1.80758676e-01 2.07819262e-02
  1.90832189e-01 5.17935537e-01 5.95473386e-02 5.46799601e-01]
 [2.19028623e-03 3.93006317e-04 5.99044372e-03 1.09623268e-01
  1.96698661e-02 2.99820183e-01 1.69584251e-01 3.04287544e-02
  4.63813768e-01 1.21915805e-01 2.18755342e-02 3.33440331e-01]
 [7.62047232e-03 8.76129968e-04 8.04515412e-03 3.81402699e-01
  4

It can be shown that the Kronecker product satisfies the following conditions:

<a id='eq2'></a>
$$
\begin{align}
\mathbf{A} \otimes (\mathbf{B} + \mathbf{C}) &= \mathbf{A} \otimes \mathbf{B} + \mathbf{A} \otimes \mathbf{C} \tag{2a} \\
(\mathbf{B} + \mathbf{C}) \otimes \mathbf{A} &= \mathbf{B} \otimes \mathbf{A} + \mathbf{C} \otimes \mathbf{A} \tag{2b} \\
(k\mathbf{A}) \otimes \mathbf{B} &= \mathbf{A} \otimes (k\mathbf{B}) = k(\mathbf{A} \otimes \mathbf{B}) \tag{2c} \\
(\mathbf{A} \otimes \mathbf{B}) \otimes \mathbf{C} &= \mathbf{A} \otimes (\mathbf{B} \otimes \mathbf{C}) \tag{2d} \\
(\mathbf{A} \otimes \mathbf{B})^{\top} &= \mathbf{A}^{\top} \otimes \mathbf{B}^{\top} \tag{2e} \\
(\mathbf{A} \otimes \mathbf{B})^{\ast} &= \mathbf{A}^{\ast} \otimes \mathbf{B}^{\ast} \tag{2f}
\end{align}
$$

where $\mathbf{C}$ is an arbitrary matrix.

In [9]:
C = np.random.rand(B.shape[0], B.shape[1])
A_kron_B_plus_C = np.kron(A, B+C)
A_kron_C = np.kron(A, C)
np.allclose(A_kron_B_plus_C, A_kron_B + A_kron_C)

True

In [10]:
AT_kron_BT = np.kron(A.T, B.T)
np.allclose(A_kron_B.T, AT_kron_BT)

True

Another very important property of the Kronecker product can be defined as follows:

The matrix-vector product

<a id='eq3'></a>
$$
\left( \mathbf{A} \otimes \mathbf{B} \right) \mathbf{v} = \mathbf{w} \: , \tag{3}
$$

where $\mathbf{v}$ is an $MP \times 1$ vector and $\mathbf{w}$ is an $NL \times 1$ vector,  can be rewritten as follows:

<a id='eq4'></a>
$$
\mathbf{A} \mathbf{V} \mathbf{B}^{\top} = \mathbf{W} \: , \tag{4}
$$

where $\mathbf{V}$ is an $M \times P$ matrix obtained by reorganizing $\mathbf{v}$ along its rows and $\mathbf{W}$ is a $N \times L$ matrix obtained by reorganizing $\mathbf{w}$ along its rows (Jain, 1989; Horn and Johnson, 1991).

In [11]:
print(N, M, L, P)

3 4 2 3


In [12]:
A_kron_B.shape

(6, 12)

In [13]:
v = np.arange(M*P)

In [14]:
v.shape

(12,)

In [15]:
v

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [16]:
w = np.dot(A_kron_B, v)

In [17]:
w.shape

(6,)

In [18]:
w

array([16.29740255, 29.38011726, 10.99195073, 19.92829039, 11.84388222,
       21.57915299])

In [19]:
# reorganize v along the rows of V
V = np.reshape(v, (M, P))

In [20]:
V.shape

(4, 3)

In [21]:
V

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [22]:
v

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [23]:
# reorganize w along the rows of W
W = np.reshape(w, (N, L))

In [24]:
W.shape

(3, 2)

In [25]:
W

array([[16.29740255, 29.38011726],
       [10.99195073, 19.92829039],
       [11.84388222, 21.57915299]])

In [26]:
w

array([16.29740255, 29.38011726, 10.99195073, 19.92829039, 11.84388222,
       21.57915299])

In [27]:
np.allclose(multi_dot([A, V, B.T]), W)

True

Similarly to equations [3](#eq3) and [4](#eq4), the matrix-vector product

<a id='eq5'></a>
$$
\left( \mathbf{B}^{\top} \otimes \mathbf{A} \right) \mathbf{v} = \mathbf{w} \: , \tag{5}
$$

where $\mathbf{v}$ is an $LM \times 1$ vector and $\mathbf{w}$ is an $PN \times 1$ vector, can be rewritten as follows:

<a id='eq6'></a>
$$
\mathbf{A} \mathbf{V} \mathbf{B} = \mathbf{W} \: , \tag{6}
$$

where $\mathbf{V}$ is an $M \times L$ matrix obtained by reorganizing $\mathbf{v}$ along its columns and $\mathbf{W}$ is a $L \times P$ matrix obtained by reorganizing $\mathbf{w}$ along its columns (Magnus and Neudecker, 2007).

In [28]:
BT_kron_A = np.kron(B.T, A)

In [29]:
BT_kron_A.shape

(9, 8)

In [30]:
BT_kron_A

array([[1.07178011e-01, 2.06392735e-01, 1.55489421e-01, 1.85223505e-01,
        3.72895129e-01, 7.18084286e-01, 5.40980815e-01, 6.44432026e-01],
       [1.43811717e-02, 1.90391770e-01, 5.19538978e-02, 1.48865717e-01,
        5.00351593e-02, 6.62413520e-01, 1.80758676e-01, 5.17935537e-01],
       [2.19028623e-03, 1.09623268e-01, 1.69584251e-01, 1.21915805e-01,
        7.62047232e-03, 3.81402699e-01, 5.90019729e-01, 4.24171051e-01],
       [1.92311100e-02, 3.70333555e-02, 2.78996982e-02, 3.32349291e-02,
        4.28719617e-02, 8.25585523e-02, 6.21968671e-02, 7.40907108e-02],
       [2.58043503e-03, 3.41622785e-02, 9.32216517e-03, 2.67111971e-02,
        5.75257028e-03, 7.61580531e-02, 2.07819262e-02, 5.95473386e-02],
       [3.93006317e-04, 1.96698661e-02, 3.04287544e-02, 2.18755342e-02,
        8.76129968e-04, 4.38500818e-02, 6.78348984e-02, 4.87671832e-02],
       [2.93132393e-01, 5.64485156e-01, 4.25264340e-01, 5.06587207e-01,
        3.93676227e-01, 7.58102453e-01, 5.71129171e-01, 6.

In [31]:
v = np.arange(L*M)

In [32]:
v.shape

(8,)

In [33]:
v

array([0, 1, 2, 3, 4, 5, 6, 7])

In [34]:
w = np.dot(BT_kron_A, v)

In [35]:
w.shape

(9,)

In [36]:
w

array([13.91195312,  8.96320577,  9.2613503 ,  1.66863433,  1.07826367,
        1.11728858, 16.489187  , 10.70688686, 11.14531272])

In [37]:
# reorganize v along the columns of V
V = np.reshape(v, (L, M)).T

In [38]:
V.shape

(4, 2)

In [39]:
V

array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

In [40]:
v

array([0, 1, 2, 3, 4, 5, 6, 7])

In [41]:
# reorganize w along the columns of W
W = np.reshape(w, (P, N)).T

In [42]:
W.shape

(3, 3)

In [43]:
W

array([[13.91195312,  1.66863433, 16.489187  ],
       [ 8.96320577,  1.07826367, 10.70688686],
       [ 9.2613503 ,  1.11728858, 11.14531272]])

In [44]:
w

array([13.91195312,  8.96320577,  9.2613503 ,  1.66863433,  1.07826367,
        1.11728858, 16.489187  , 10.70688686, 11.14531272])

In [45]:
np.allclose(multi_dot([A, V, B]), W)

True