# Kronecker product

#### References

* Magnus, J. R. and H. Neudecker (2007), Matrix differential calculus with applications in statistics and econometrics, 3rd edition, John Wiley & Sons, ISBN 0-471-98632-1.

* Jain, A. K. (1989), Fundamentals of Digital Image Processing, Prentice Hall, ISBN 978-0-13-336165-0.

* Horn, R. A. and C. R. Johnson, (1991), Topics in Matrix Analysis, Cambridge University Press, ISBN 978-0-521-46713-1.

Let $\mathbf{A}$ and $\mathbf{B}$ be, respectively, $N \times M$ and $L \times P$ matrices given by:

$$\mathbf{A} 
= \begin{bmatrix}
a_{11} & \cdots & a_{1M} \\
\vdots &        & \vdots \\
a_{N1} & \cdots & a_{NM}
\end{bmatrix}_{N \times M} \:
$$

and

$$\mathbf{B} 
= \begin{bmatrix}
b_{11} & \cdots & b_{1P} \\
\vdots &        & \vdots \\
b_{L1} & \cdots & b_{LP}
\end{bmatrix}_{L \times P} \: .
$$

The [Kronecker product](https://en.wikipedia.org/wiki/Kronecker_product) of $\mathbf{A}$ and $\mathbf{B}$, denoted as $\mathbf{A} \otimes \mathbf{B}$, is an $NL \times MP$ matrix given by:

$$
\mathbf{A} \otimes \mathbf{B}
= \begin{bmatrix}
a_{11} \, \mathbf{B} & \cdots & a_{1M} \, \mathbf{B} \\
\vdots &        & \vdots \\
a_{N1} \, \mathbf{B} & \cdots & a_{NM} \, \mathbf{B}
\end{bmatrix}_{\, NL \, \times \, MP} \: .
$$

Notice that $\mathbf{A} \otimes \mathbf{B}$ is a block matrix formed by $N \times M$ blocks, each one with $L \times P$ elements.

In [1]:
import numpy as np
from numpy.linalg import multi_dot

In [2]:
N = 3
M = 4
L = 2
P = 3

In [3]:
A = np.random.rand(N, M)
B = np.random.rand(L, P)

In [4]:
Kron_AB = np.kron(A, B)

In [5]:
Kron_AB.shape

(6, 12)

In [6]:
Kron_AB

array([[5.02619801e-02, 7.80877263e-01, 5.94319434e-01, 1.58680895e-02,
        2.46528893e-01, 1.87631167e-01, 5.54084286e-02, 8.60833216e-01,
        6.55173271e-01, 4.68580570e-04, 7.27993429e-03, 5.54069972e-03],
       [5.38715953e-01, 4.62103873e-01, 6.85119560e-01, 1.70076725e-01,
        1.45889709e-01, 2.16297458e-01, 5.93876412e-01, 5.09419832e-01,
        7.55270645e-01, 5.02232160e-03, 4.30808527e-03, 6.38720785e-03],
       [3.63771369e-02, 5.65160365e-01, 4.30139031e-01, 5.22065402e-02,
        8.11088224e-01, 6.17312755e-01, 1.53447075e-02, 2.38397556e-01,
        1.81442472e-01, 3.80532153e-02, 5.91200158e-01, 4.49957708e-01],
       [3.89895979e-01, 3.34447943e-01, 4.95855673e-01, 5.59558059e-01,
        4.79981974e-01, 7.11625800e-01, 1.64467033e-01, 1.41077784e-01,
        2.09163253e-01, 4.07860456e-01, 3.49857649e-01, 5.18702249e-01],
       [2.97680322e-02, 4.62480376e-01, 3.51990113e-01, 5.28261573e-04,
        8.20714684e-03, 6.24639377e-03, 1.35884924e-02, 2.11

It can be shown that the Kronecker product satisfies the following conditions:

$$
\begin{align}
\mathbf{A} \otimes (\mathbf{B} + \mathbf{C}) &= \mathbf{A} \otimes \mathbf{B} + \mathbf{A} \otimes \mathbf{C} \\
(\mathbf{B} + \mathbf{C}) \otimes \mathbf{A} &= \mathbf{B} \otimes \mathbf{A} + \mathbf{C} \otimes \mathbf{A} \\
(k\mathbf{A}) \otimes \mathbf{B} &= \mathbf{A} \otimes (k\mathbf{B}) = k(\mathbf{A} \otimes \mathbf{B}) \\
(\mathbf{A} \otimes \mathbf{B}) \otimes \mathbf{C} &= \mathbf{A} \otimes (\mathbf{B} \otimes \mathbf{C})
\end{align} \quad ,
$$

where $\mathbf{C}$ is a matrix. The is also another very important property of Kronecker product. Let's first consider the equation:

$$
\left( \mathbf{A} \otimes \mathbf{B} \right) \mathbf{v} = \mathbf{w} \: ,
$$

where $\mathbf{v}$ is an $MP \times 1$ vector and $\mathbf{w}$ is an $NL \times 1$ vector. It can be shown that this equation can be rewritten as follows:

$$
\mathbf{A} \mathbf{V} \mathbf{B}^{\top} = \mathbf{W} \: ,
$$

where $\mathbf{V}$ is an $M \times P$ matrix obtained by reorganizing $\mathbf{v}$ along its rows and $\mathbf{W}$ is a $N \times L$ matrix obtained by reorganizing $\mathbf{w}$ along its rows (Jain, 1989; Horn and Johnson, 1991).

In [7]:
v = np.arange(M*P)

In [8]:
v.shape

(12,)

In [9]:
v

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [10]:
w = np.dot(Kron_AB, v)

In [11]:
w.shape

(6,)

In [12]:
w

array([15.67902532, 17.33752278, 22.32938095, 25.00558841, 17.12910368,
       19.38676776])

In [13]:
# reorganize v along the rows of V
V = np.reshape(v, (M, P))

In [14]:
V.shape

(4, 3)

In [15]:
V

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [16]:
v

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [17]:
# reorganize w along the rows of W
W = np.reshape(w, (N, L))

In [18]:
W.shape

(3, 2)

In [19]:
W

array([[15.67902532, 17.33752278],
       [22.32938095, 25.00558841],
       [17.12910368, 19.38676776]])

In [20]:
w

array([15.67902532, 17.33752278, 22.32938095, 25.00558841, 17.12910368,
       19.38676776])

In [21]:
np.allclose(multi_dot([A, V, B.T]), W)

True

Similarly, consider the equation:

$$
\left( \mathbf{B}^{\top} \otimes \mathbf{A} \right) \mathbf{v} = \mathbf{w} \: ,
$$

where $\mathbf{v}$ is an $LM \times 1$ vector and $\mathbf{w}$ is an $PN \times 1$ vector. It can be shown that this equation can be rewritten as follows:

$$
\mathbf{A} \mathbf{V} \mathbf{B} = \mathbf{W} \: ,
$$

where $\mathbf{V}$ is an $M \times L$ matrix obtained by reorganizing $\mathbf{v}$ along its columns and $\mathbf{W}$ is a $L \times P$ matrix obtained by reorganizing $\mathbf{w}$ along its columns (Magnus and Neudecker, 2007).

In [22]:
Kron_BTA = np.kron(B.T, A)

In [23]:
Kron_BTA.shape

(9, 8)

In [24]:
Kron_BTA

array([[5.02619801e-02, 1.58680895e-02, 5.54084286e-02, 4.68580570e-04,
        5.38715953e-01, 1.70076725e-01, 5.93876412e-01, 5.02232160e-03],
       [3.63771369e-02, 5.22065402e-02, 1.53447075e-02, 3.80532153e-02,
        3.89895979e-01, 5.59558059e-01, 1.64467033e-01, 4.07860456e-01],
       [2.97680322e-02, 5.28261573e-04, 1.35884924e-02, 4.43306030e-02,
        3.19058537e-01, 5.66199215e-03, 1.45643638e-01, 4.75142503e-01],
       [7.80877263e-01, 2.46528893e-01, 8.60833216e-01, 7.27993429e-03,
        4.62103873e-01, 1.45889709e-01, 5.09419832e-01, 4.30808527e-03],
       [5.65160365e-01, 8.11088224e-01, 2.38397556e-01, 5.91200158e-01,
        3.34447943e-01, 4.79981974e-01, 1.41077784e-01, 3.49857649e-01],
       [4.62480376e-01, 8.20714684e-03, 2.11112749e-01, 6.88726546e-01,
        2.73684462e-01, 4.85678675e-03, 1.24931309e-01, 4.07571356e-01],
       [5.94319434e-01, 1.87631167e-01, 6.55173271e-01, 5.54069972e-03,
        6.85119560e-01, 2.16297458e-01, 7.55270645e-01, 6.

In [28]:
v = np.arange(L*M)

In [29]:
v.shape

(8,)

In [30]:
v

array([0, 1, 2, 3, 4, 5, 6, 7])

In [31]:
w = np.dot(Kron_BTA, v)

In [32]:
w.shape

(9,)

In [33]:
w

array([ 6.73175285,  8.39625521,  5.66510052,  7.65457475, 10.0946557 ,
        7.21822141,  9.91289966, 12.75751778,  8.90045383])

In [34]:
# reorganize v along the columns of V
V = np.reshape(v, (L, M)).T

In [35]:
V.shape

(4, 2)

In [36]:
V

array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

In [37]:
v

array([0, 1, 2, 3, 4, 5, 6, 7])

In [38]:
# reorganize w along the columns of W
W = np.reshape(w, (P, N)).T

In [39]:
W.shape

(3, 3)

In [40]:
W

array([[ 6.73175285,  7.65457475,  9.91289966],
       [ 8.39625521, 10.0946557 , 12.75751778],
       [ 5.66510052,  7.21822141,  8.90045383]])

In [41]:
w

array([ 6.73175285,  8.39625521,  5.66510052,  7.65457475, 10.0946557 ,
        7.21822141,  9.91289966, 12.75751778,  8.90045383])

In [42]:
np.allclose(multi_dot([A, V, B]), W)

True