# Kronecker product

#### References

* Magnus, J. R. and H. Neudecker (2007), Matrix differential calculus with applications in statistics and econometrics, 3rd edition, John Wiley & Sons, ISBN 0-471-98632-1.

* Jain, A. K. (1989), Fundamentals of Digital Image Processing, Prentice Hall, ISBN 978-0-13-336165-0.

* Horn, R. A. and C. R. Johnson, (1991), Topics in Matrix Analysis, Cambridge University Press, ISBN 978-0-521-46713-1.

Let $\mathbf{A}$ and $\mathbf{B}$ be, respectively, $N \times M$ and $L \times P$ matrices given by:

$$\mathbf{A} 
= \begin{bmatrix}
a_{11} & \cdots & a_{1M} \\
\vdots &        & \vdots \\
a_{N1} & \cdots & a_{NM}
\end{bmatrix}_{N \times M} \:
$$

and

$$\mathbf{B} 
= \begin{bmatrix}
b_{11} & \cdots & b_{1P} \\
\vdots &        & \vdots \\
b_{L1} & \cdots & b_{LP}
\end{bmatrix}_{L \times P} \: .
$$

The [Kronecker product](https://en.wikipedia.org/wiki/Kronecker_product) of $\mathbf{A}$ and $\mathbf{B}$, denoted as $\mathbf{A} \otimes \mathbf{B}$, is an $NL \times MP$ matrix given by:

<a id='eq1'></a>
$$
\mathbf{A} \otimes \mathbf{B}
= \begin{bmatrix}
a_{11} \, \mathbf{B} & \cdots & a_{1M} \, \mathbf{B} \\
\vdots &        & \vdots \\
a_{N1} \, \mathbf{B} & \cdots & a_{NM} \, \mathbf{B}
\end{bmatrix}_{\, NL \, \times \, MP} \: . \tag{1}
$$

Notice that $\mathbf{A} \otimes \mathbf{B}$ ([equation 1](#eq1)) is a block matrix formed by $N \times M$ blocks, each one with $L \times P$ elements.

In [1]:
import numpy as np
from numpy.linalg import multi_dot

In [2]:
N = 3
M = 4
L = 2
P = 3

In [3]:
A = np.random.rand(N, M)
B = np.random.rand(L, P)

In [4]:
print(A)

[[0.26748972 0.52791847 0.77860038 0.81383297]
 [0.98263864 0.9992426  0.15667369 0.9724966 ]
 [0.31046894 0.81214042 0.44177935 0.34265088]]


In [5]:
print(B)

[[0.84463183 0.19731041 0.32089693]
 [0.22649296 0.51949212 0.27758031]]


In [6]:
Kron_AB = np.kron(A, B)

In [7]:
Kron_AB.shape

(6, 12)

In [8]:
print(Kron_AB)

[[0.22593033 0.05277851 0.08583663 0.44589674 0.10416381 0.16940741
  0.65763067 0.15362596 0.24985047 0.68738923 0.16057771 0.2611565 ]
 [0.06058454 0.1389588  0.07424988 0.11956982 0.27424948 0.14653977
  0.17634751 0.40447676 0.21612414 0.18432744 0.42277981 0.22590401]
 [0.82996788 0.19388483 0.31532572 0.84399211 0.19716096 0.32065388
  0.13233159 0.03091335 0.05027611 0.82140159 0.1918837  0.31207117]
 [0.22256074 0.51047303 0.27276114 0.22632142 0.51909865 0.27737007
  0.03548549 0.08139075 0.04348953 0.22026364 0.50520432 0.26994591]
 [0.26223195 0.06125875 0.09962853 0.68595965 0.16024376 0.26061336
  0.3731409  0.08716766 0.14176564 0.28941384 0.06760859 0.10995562]
 [0.07031903 0.16128617 0.08618006 0.18394409 0.42190054 0.22543419
  0.10005991 0.22950089 0.12262925 0.07760801 0.17800443 0.09511314]]


It can be shown that the Kronecker product satisfies the following conditions:

<a id='eq2'></a>
$$
\begin{align}
\mathbf{A} \otimes (\mathbf{B} + \mathbf{C}) &= \mathbf{A} \otimes \mathbf{B} + \mathbf{A} \otimes \mathbf{C} \tag{2a} \\
(\mathbf{B} + \mathbf{C}) \otimes \mathbf{A} &= \mathbf{B} \otimes \mathbf{A} + \mathbf{C} \otimes \mathbf{A} \tag{2b} \\
(k\mathbf{A}) \otimes \mathbf{B} &= \mathbf{A} \otimes (k\mathbf{B}) = k(\mathbf{A} \otimes \mathbf{B}) \tag{2c} \\
(\mathbf{A} \otimes \mathbf{B}) \otimes \mathbf{C} &= \mathbf{A} \otimes (\mathbf{B} \otimes \mathbf{C}) \tag{2d}
\end{align}
$$

where $\mathbf{C}$ is an arbitrary matrix. Another very important property of the Kronecker product can be defined as follows:

The matrix-vector product

<a id='eq3'></a>
$$
\left( \mathbf{A} \otimes \mathbf{B} \right) \mathbf{v} = \mathbf{w} \: , \tag{3}
$$

where $\mathbf{v}$ is an $MP \times 1$ vector and $\mathbf{w}$ is an $NL \times 1$ vector,  can be rewritten as follows:

<a id='eq4'></a>
$$
\mathbf{A} \mathbf{V} \mathbf{B}^{\top} = \mathbf{W} \: , \tag{4}
$$

where $\mathbf{V}$ is an $M \times P$ matrix obtained by reorganizing $\mathbf{v}$ along its rows and $\mathbf{W}$ is a $N \times L$ matrix obtained by reorganizing $\mathbf{w}$ along its rows (Jain, 1989; Horn and Johnson, 1991).

In [9]:
print(N, M, L, P)

3 4 2 3


In [10]:
Kron_AB.shape

(6, 12)

In [11]:
v = np.arange(M*P)

In [12]:
v.shape

(12,)

In [13]:
v

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [14]:
w = np.dot(Kron_AB, v)

In [15]:
w.shape

(6,)

In [16]:
w

array([20.51080546, 16.46596946, 19.90525185, 16.33258991, 12.73590295,
       10.4129124 ])

In [17]:
# reorganize v along the rows of V
V = np.reshape(v, (M, P))

In [18]:
V.shape

(4, 3)

In [19]:
V

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [20]:
v

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [21]:
# reorganize w along the rows of W
W = np.reshape(w, (N, L))

In [22]:
W.shape

(3, 2)

In [23]:
W

array([[20.51080546, 16.46596946],
       [19.90525185, 16.33258991],
       [12.73590295, 10.4129124 ]])

In [24]:
w

array([20.51080546, 16.46596946, 19.90525185, 16.33258991, 12.73590295,
       10.4129124 ])

In [25]:
np.allclose(multi_dot([A, V, B.T]), W)

True

Similarly to equations [3](#eq3) and [4](#eq4), the matrix-vector product

<a id='eq5'></a>
$$
\left( \mathbf{B}^{\top} \otimes \mathbf{A} \right) \mathbf{v} = \mathbf{w} \: , \tag{5}
$$

where $\mathbf{v}$ is an $LM \times 1$ vector and $\mathbf{w}$ is an $PN \times 1$ vector, can be rewritten as follows:

<a id='eq6'></a>
$$
\mathbf{A} \mathbf{V} \mathbf{B} = \mathbf{W} \: , \tag{6}
$$

where $\mathbf{V}$ is an $M \times L$ matrix obtained by reorganizing $\mathbf{v}$ along its columns and $\mathbf{W}$ is a $L \times P$ matrix obtained by reorganizing $\mathbf{w}$ along its columns (Magnus and Neudecker, 2007).

In [26]:
Kron_BTA = np.kron(B.T, A)

In [27]:
Kron_BTA.shape

(9, 8)

In [28]:
Kron_BTA

array([[0.22593033, 0.44589674, 0.65763067, 0.68738923, 0.06058454,
        0.11956982, 0.17634751, 0.18432744],
       [0.82996788, 0.84399211, 0.13233159, 0.82140159, 0.22256074,
        0.22632142, 0.03548549, 0.22026364],
       [0.26223195, 0.68595965, 0.3731409 , 0.28941384, 0.07031903,
        0.18394409, 0.10005991, 0.07760801],
       [0.05277851, 0.10416381, 0.15362596, 0.16057771, 0.1389588 ,
        0.27424948, 0.40447676, 0.42277981],
       [0.19388483, 0.19716096, 0.03091335, 0.1918837 , 0.51047303,
        0.51909865, 0.08139075, 0.50520432],
       [0.06125875, 0.16024376, 0.08716766, 0.06760859, 0.16128617,
        0.42190054, 0.22950089, 0.17800443],
       [0.08583663, 0.16940741, 0.24985047, 0.2611565 , 0.07424988,
        0.14653977, 0.21612414, 0.22590401],
       [0.31532572, 0.32065388, 0.05027611, 0.31207117, 0.27276114,
        0.27737007, 0.04348953, 0.26994591],
       [0.09962853, 0.26061336, 0.14176564, 0.10995562, 0.08618006,
        0.22543419, 0.122629

In [29]:
v = np.arange(L*M)

In [30]:
v.shape

(8,)

In [31]:
v

array([0, 1, 2, 3, 4, 5, 6, 7])

In [32]:
w = np.dot(Kron_BTA, v)

In [33]:
w.shape

(9,)

In [34]:
w

array([7.01189014, 7.34946846, 4.64509512, 8.20655071, 9.49679885,
       5.91508858, 5.36034914, 5.98587312, 3.74747018])

In [35]:
# reorganize v along the columns of V
V = np.reshape(v, (L, M)).T

In [36]:
V.shape

(4, 2)

In [37]:
V

array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

In [38]:
v

array([0, 1, 2, 3, 4, 5, 6, 7])

In [39]:
# reorganize w along the columns of W
W = np.reshape(w, (P, N)).T

In [40]:
W.shape

(3, 3)

In [41]:
W

array([[7.01189014, 8.20655071, 5.36034914],
       [7.34946846, 9.49679885, 5.98587312],
       [4.64509512, 5.91508858, 3.74747018]])

In [42]:
w

array([7.01189014, 7.34946846, 4.64509512, 8.20655071, 9.49679885,
       5.91508858, 5.36034914, 5.98587312, 3.74747018])

In [43]:
np.allclose(multi_dot([A, V, B]), W)

True