# Kronecker product

Let $\mathbf{A}$ and $\mathbf{B}$ be, respectively, $N \times M$ and $L \times P$ matrices given by:

$$\mathbf{A} 
= \begin{bmatrix}
a_{11} & \cdots & a_{1M} \\
\vdots &        & \vdots \\
a_{N1} & \cdots & a_{NM}
\end{bmatrix}_{N \times M} \:
$$

and

$$\mathbf{B} 
= \begin{bmatrix}
b_{11} & \cdots & b_{1P} \\
\vdots &        & \vdots \\
b_{L1} & \cdots & b_{LP}
\end{bmatrix}_{L \times P} \: .
$$

The [Kronecker product](https://en.wikipedia.org/wiki/Kronecker_product) of $\mathbf{A}$ and $\mathbf{B}$, denoted as $\mathbf{A} \otimes \mathbf{B}$, is an $NL \times MP$ matrix given by:

$$
\mathbf{A} \otimes \mathbf{B}
= \begin{bmatrix}
a_{11} \, \mathbf{B} & \cdots & a_{1M} \, \mathbf{B} \\
\vdots &        & \vdots \\
a_{N1} \, \mathbf{B} & \cdots & a_{NM} \, \mathbf{B}
\end{bmatrix}_{\, NL \, \times \, MP} \: .
$$

Notice that $\mathbf{A} \otimes \mathbf{B}$ is block matrix formed by $N \times M$ blocks, each one with $L \times P$ elements.

It can be shown that the Kronecker product satisfies the following conditions:

$$
\begin{align}
\mathbf{A} \otimes (\mathbf{B} + \mathbf{C}) &= \mathbf{A} \otimes \mathbf{B} + \mathbf{A} \otimes \mathbf{C} \\
(\mathbf{B} + \mathbf{C}) \otimes \mathbf{A} &= \mathbf{B} \otimes \mathbf{A} + \mathbf{C} \otimes \mathbf{A} \\
(k\mathbf{A}) \otimes \mathbf{B} &= \mathbf{A} \otimes (k\mathbf{B}) = k(\mathbf{A} \otimes \mathbf{B}) \\
(\mathbf{A} \otimes \mathbf{B}) \otimes \mathbf{C} &= \mathbf{A} \otimes (\mathbf{B} \otimes \mathbf{C})
\end{align} \quad ,
$$

where $\mathbf{C}$ is a matrix. The is also another very important property of Kronecker product. Let's first consider the equation:

$$
\left( \mathbf{A} \otimes \mathbf{B} \right) \mathbf{v} = \mathbf{w} \: ,
$$

where $\mathbf{v}$ and $\mathbf{w}$ are vectors. It can be shown that this equation can be rewritten as follows:

$$
\mathbf{A} \mathbf{V} \mathbf{B}^{\top} = \mathbf{W} \: ,
$$

where $\mathbf{V}$ and $\mathbf{W}$ are row-oriented matrices obtained from the vectors $\mathbf{v}$ and $\mathbf{w}$, respectively (Jain, 1989; Horn and Johnson, 1991).

A pseudo-code for computing the Kronecker product can be written as follows:

    C = zeros((N*L, M*P))
    i1 = 
    i2 = 
    for i = 1:N
        j1 = 
        j2 = 
        for j = 1:M
            C[i1:i2, j1:j2] = A[i,j]*B
            j1 = 
            j2 = 
        i1 = 
        i2 = 

### Exercise

1. In your `my_function.py` file, create one functions called `kronecker` for computing the Krnecker product. Your function must receive 2 matrices `A` and `B` and return the resultant matrix.
2. In your `test_my_function.py` file, create 3 tests for function `kronecker`. One test must compare the result produced by your function and an expected result produced by a specific input. The other test must compare the result produced by your function and the result produced by the routine [`numpy.kron`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.kron.html) (see the example presented below). The last test must verify the conditions listed above about the Kronecker product.

In [1]:
import numpy as np

In [2]:
A = np.array([[1.,2.,3.],
              [4.,5.,6.],
              [7.,8.,9.]])
B = np.array([[7., 8.],
              [9., 10.]])

In [3]:
C = np.kron(A, B)

In [4]:
C

array([[ 7.,  8., 14., 16., 21., 24.],
       [ 9., 10., 18., 20., 27., 30.],
       [28., 32., 35., 40., 42., 48.],
       [36., 40., 45., 50., 54., 60.],
       [49., 56., 56., 64., 63., 72.],
       [63., 70., 72., 80., 81., 90.]])

In [5]:
v = np.arange(C.shape[1])

In [6]:
v

array([0, 1, 2, 3, 4, 5])

In [7]:
w = np.dot(C, v)

In [8]:
w

array([ 288.,  364.,  630.,  796.,  972., 1228.])

In [9]:
V = np.reshape(v, (A.shape[1], B.shape[0]))

In [10]:
V

array([[0, 1],
       [2, 3],
       [4, 5]])

In [11]:
W = np.reshape(w, (A.shape[1], B.shape[0]))

In [12]:
W

array([[ 288.,  364.],
       [ 630.,  796.],
       [ 972., 1228.]])

In [15]:
np.allclose(np.dot(A, np.dot(V, B.T)), W)

True