# Kronecker product

#### References

* Magnus, J. R. and H. Neudecker (2007), Matrix differential calculus with applications in statistics and econometrics, 3rd edition, John Wiley & Sons, ISBN 0-471-98632-1.

* Jain, A. K. (1989), Fundamentals of Digital Image Processing, Prentice Hall, ISBN 978-0-13-336165-0.

* Horn, R. A. and C. R. Johnson, (1991), Topics in Matrix Analysis, Cambridge University Press, ISBN 978-0-521-46713-1.

Let $\mathbf{A}$ and $\mathbf{B}$ be, respectively, $N \times M$ and $L \times P$ matrices given by:

$$\mathbf{A} 
= \begin{bmatrix}
a_{11} & \cdots & a_{1M} \\
\vdots &        & \vdots \\
a_{N1} & \cdots & a_{NM}
\end{bmatrix}_{N \times M} \:
$$

and

$$\mathbf{B} 
= \begin{bmatrix}
b_{11} & \cdots & b_{1P} \\
\vdots &        & \vdots \\
b_{L1} & \cdots & b_{LP}
\end{bmatrix}_{L \times P} \: .
$$

The [Kronecker product](https://en.wikipedia.org/wiki/Kronecker_product) of $\mathbf{A}$ and $\mathbf{B}$, denoted as $\mathbf{A} \otimes \mathbf{B}$, is an $NL \times MP$ matrix given by:

<a id='eq1'></a>
$$
\mathbf{A} \otimes \mathbf{B}
= \begin{bmatrix}
a_{11} \, \mathbf{B} & \cdots & a_{1M} \, \mathbf{B} \\
\vdots &        & \vdots \\
a_{N1} \, \mathbf{B} & \cdots & a_{NM} \, \mathbf{B}
\end{bmatrix}_{\, NL \, \times \, MP} \: . \tag{1}
$$

Notice that $\mathbf{A} \otimes \mathbf{B}$ ([equation 1](#eq1)) is a block matrix formed by $N \times M$ blocks, each one with $L \times P$ elements.

In [1]:
import numpy as np
from numpy.linalg import multi_dot

In [2]:
N = 3
M = 4
L = 2
P = 3

In [3]:
A = np.random.rand(N, M)
B = np.random.rand(L, P)

In [4]:
print(A)

[[0.28504691 0.14125843 0.26827027 0.25281422]
 [0.31210281 0.81128487 0.85484176 0.47271245]
 [0.49792762 0.51192315 0.37108006 0.01934159]]


In [5]:
print(B)

[[0.17286001 0.5970379  0.77745973]
 [0.34202057 0.2701088  0.75782418]]


In [6]:
Kron_AB = np.kron(A, B)

In [7]:
Kron_AB.shape

(6, 12)

In [8]:
print(Kron_AB)

[[0.04927321 0.17018381 0.22161249 0.02441793 0.08433664 0.10982274
  0.0463732  0.16016752 0.20856933 0.04370147 0.15093967 0.19655288]
 [0.0974919  0.07699368 0.21601544 0.04831329 0.03815514 0.10704905
  0.09175395 0.07246216 0.2033017  0.08646766 0.06828734 0.19158873]
 [0.0539501  0.18633721 0.24264736 0.14023871 0.48436782 0.63074132
  0.14776796 0.51037293 0.66460505 0.08171308 0.28222725 0.3675149 ]
 [0.10674558 0.08430171 0.23651905 0.27747611 0.21913518 0.61481129
  0.29237346 0.23090028 0.64781976 0.16167738 0.12768379 0.35823293]
 [0.08607178 0.29728166 0.38711867 0.08849104 0.30563753 0.39799964
  0.06414491 0.22154886 0.28849981 0.00334339 0.01154766 0.0150373 ]
 [0.17030149 0.13449463 0.37734159 0.17508825 0.13827495 0.38794775
  0.12691701 0.10023199 0.28121345 0.00661522 0.00522433 0.01465752]]


It can be shown that the Kronecker product satisfies the following conditions:

<a id='eq2'></a>
$$
\begin{align}
\mathbf{A} \otimes (\mathbf{B} + \mathbf{C}) &= \mathbf{A} \otimes \mathbf{B} + \mathbf{A} \otimes \mathbf{C} \tag{2a} \\
(\mathbf{B} + \mathbf{C}) \otimes \mathbf{A} &= \mathbf{B} \otimes \mathbf{A} + \mathbf{C} \otimes \mathbf{A} \tag{2b} \\
(k\mathbf{A}) \otimes \mathbf{B} &= \mathbf{A} \otimes (k\mathbf{B}) = k(\mathbf{A} \otimes \mathbf{B}) \tag{2c} \\
(\mathbf{A} \otimes \mathbf{B}) \otimes \mathbf{C} &= \mathbf{A} \otimes (\mathbf{B} \otimes \mathbf{C}) \tag{2d}
\end{align}
$$

where $\mathbf{C}$ is an arbitrary matrix. Another very important property of the Kronecker product can be defined as follows:

The matrix-vector product

<a id='eq3'></a>
$$
\left( \mathbf{A} \otimes \mathbf{B} \right) \mathbf{v} = \mathbf{w} \: , \tag{3}
$$

where $\mathbf{v}$ is an $MP \times 1$ vector and $\mathbf{w}$ is an $NL \times 1$ vector,  can be rewritten as follows:

<a id='eq4'></a>
$$
\mathbf{A} \mathbf{V} \mathbf{B}^{\top} = \mathbf{W} \: , \tag{4}
$$

where $\mathbf{V}$ is an $M \times P$ matrix obtained by reorganizing $\mathbf{v}$ along its rows and $\mathbf{W}$ is a $N \times L$ matrix obtained by reorganizing $\mathbf{w}$ along its rows (Jain, 1989; Horn and Johnson, 1991).

In [9]:
v = np.arange(M*P)

In [10]:
v.shape

(12,)

In [11]:
v

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [12]:
w = np.dot(Kron_AB, v)

In [13]:
w.shape

(6,)

In [14]:
w

array([ 8.7058809 ,  7.59456106, 23.55993867, 20.56596263,  9.10422782,
        7.8931277 ])

In [15]:
# reorganize v along the rows of V
V = np.reshape(v, (M, P))

In [16]:
V.shape

(4, 3)

In [17]:
V

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [18]:
v

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [19]:
# reorganize w along the rows of W
W = np.reshape(w, (N, L))

In [20]:
W.shape

(3, 2)

In [21]:
W

array([[ 8.7058809 ,  7.59456106],
       [23.55993867, 20.56596263],
       [ 9.10422782,  7.8931277 ]])

In [22]:
w

array([ 8.7058809 ,  7.59456106, 23.55993867, 20.56596263,  9.10422782,
        7.8931277 ])

In [23]:
np.allclose(multi_dot([A, V, B.T]), W)

True

Similarly to equations [3](#eq3) and [4](#eq4), the matrix-vector product

<a id='eq5'></a>
$$
\left( \mathbf{B}^{\top} \otimes \mathbf{A} \right) \mathbf{v} = \mathbf{w} \: , \tag{5}
$$

where $\mathbf{v}$ is an $LM \times 1$ vector and $\mathbf{w}$ is an $PN \times 1$ vector, can be rewritten as follows:

<a id='eq6'></a>
$$
\mathbf{A} \mathbf{V} \mathbf{B} = \mathbf{W} \: , \tag{6}
$$

where $\mathbf{V}$ is an $M \times L$ matrix obtained by reorganizing $\mathbf{v}$ along its columns and $\mathbf{W}$ is a $L \times P$ matrix obtained by reorganizing $\mathbf{w}$ along its columns (Magnus and Neudecker, 2007).

In [24]:
Kron_BTA = np.kron(B.T, A)

In [25]:
Kron_BTA.shape

(9, 8)

In [26]:
Kron_BTA

array([[0.04927321, 0.02441793, 0.0463732 , 0.04370147, 0.0974919 ,
        0.04831329, 0.09175395, 0.08646766],
       [0.0539501 , 0.14023871, 0.14776796, 0.08171308, 0.10674558,
        0.27747611, 0.29237346, 0.16167738],
       [0.08607178, 0.08849104, 0.06414491, 0.00334339, 0.17030149,
        0.17508825, 0.12691701, 0.00661522],
       [0.17018381, 0.08433664, 0.16016752, 0.15093967, 0.07699368,
        0.03815514, 0.07246216, 0.06828734],
       [0.18633721, 0.48436782, 0.51037293, 0.28222725, 0.08430171,
        0.21913518, 0.23090028, 0.12768379],
       [0.29728166, 0.30563753, 0.22154886, 0.01154766, 0.13449463,
        0.13827495, 0.10023199, 0.00522433],
       [0.22161249, 0.10982274, 0.20856933, 0.19655288, 0.21601544,
        0.10704905, 0.2033017 , 0.19158873],
       [0.24264736, 0.63074132, 0.66460505, 0.3675149 , 0.23651905,
        0.61481129, 0.64781976, 0.35823293],
       [0.38711867, 0.39799964, 0.28849981, 0.0150373 , 0.37734159,
        0.38794775, 0.281213

In [27]:
v = np.arange(L*M)

In [28]:
v.shape

(8,)

In [29]:
v

array([0, 1, 2, 3, 4, 5, 6, 7])

In [30]:
w = np.dot(Kron_BTA, v)

In [31]:
w.shape

(9,)

In [32]:
w

array([ 2.03560013,  5.38125918,  2.59126682,  2.26902548,  6.0638664 ,
        2.65069376,  5.07685833, 13.47717779,  6.25909959])

In [33]:
# reorganize v along the columns of V
V = np.reshape(v, (L, M)).T

In [34]:
V.shape

(4, 2)

In [35]:
V

array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

In [36]:
v

array([0, 1, 2, 3, 4, 5, 6, 7])

In [37]:
# reorganize w along the columns of W
W = np.reshape(w, (P, N)).T

In [38]:
W.shape

(3, 3)

In [39]:
W

array([[ 2.03560013,  2.26902548,  5.07685833],
       [ 5.38125918,  6.0638664 , 13.47717779],
       [ 2.59126682,  2.65069376,  6.25909959]])

In [40]:
w

array([ 2.03560013,  5.38125918,  2.59126682,  2.26902548,  6.0638664 ,
        2.65069376,  5.07685833, 13.47717779,  6.25909959])

In [41]:
np.allclose(multi_dot([A, V, B]), W)

True