# Kronecker product

#### References

* Magnus, J. R. and H. Neudecker (2007), Matrix differential calculus with applications in statistics and econometrics, 3rd edition, John Wiley & Sons, ISBN 0-471-98632-1.

* Jain, A. K. (1989), Fundamentals of Digital Image Processing, Prentice Hall, ISBN 978-0-13-336165-0.

* Horn, R. A. and C. R. Johnson, (1991), Topics in Matrix Analysis, Cambridge University Press, ISBN 978-0-521-46713-1.

Let $\mathbf{A}$ and $\mathbf{B}$ be, respectively, $N \times M$ and $L \times P$ matrices given by:

$$\mathbf{A} 
= \begin{bmatrix}
a_{11} & \cdots & a_{1M} \\
\vdots &        & \vdots \\
a_{N1} & \cdots & a_{NM}
\end{bmatrix}_{N \times M} \:
$$

and

$$\mathbf{B} 
= \begin{bmatrix}
b_{11} & \cdots & b_{1P} \\
\vdots &        & \vdots \\
b_{L1} & \cdots & b_{LP}
\end{bmatrix}_{L \times P} \: .
$$

The [Kronecker product](https://en.wikipedia.org/wiki/Kronecker_product) of $\mathbf{A}$ and $\mathbf{B}$, denoted as $\mathbf{A} \otimes \mathbf{B}$, is an $NL \times MP$ matrix given by:

<a id='eq1'></a>
$$
\mathbf{A} \otimes \mathbf{B}
= \begin{bmatrix}
a_{11} \, \mathbf{B} & \cdots & a_{1M} \, \mathbf{B} \\
\vdots &        & \vdots \\
a_{N1} \, \mathbf{B} & \cdots & a_{NM} \, \mathbf{B}
\end{bmatrix}_{\, NL \, \times \, MP} \: . \tag{1}
$$

Notice that $\mathbf{A} \otimes \mathbf{B}$ ([equation 1](#eq1)) is a block matrix formed by $N \times M$ blocks, each one with $L \times P$ elements.

In [1]:
import numpy as np
from numpy.linalg import multi_dot

In [2]:
N = 3
M = 4
L = 2
P = 3

In [3]:
A = np.random.rand(N, M)
B = np.random.rand(L, P)

In [4]:
print(A)

[[0.22790782 0.99563861 0.99542867 0.16192179]
 [0.81417627 0.37756896 0.97364149 0.32643871]
 [0.23256292 0.13988534 0.91528559 0.12311775]]


In [5]:
print(B)

[[0.09954247 0.2260351  0.91104976]
 [0.07635364 0.81436109 0.30889322]]


In [6]:
A_kron_B = np.kron(A, B)

In [7]:
A_kron_B.shape

(6, 12)

In [8]:
print(A_kron_B)

[[0.02268651 0.05151517 0.20763536 0.09910833 0.22504927 0.90707632
  0.09908743 0.22500182 0.90688505 0.01611809 0.03660001 0.14751881]
 [0.01740159 0.18559926 0.07039918 0.07602063 0.81080935 0.30754602
  0.0760046  0.81063838 0.30748117 0.01236332 0.13186281 0.05001654]
 [0.08104512 0.18403241 0.74175509 0.03758415 0.08534384 0.34398411
  0.09691868 0.22007715 0.88703585 0.03249451 0.0737866  0.2974019 ]
 [0.06216532 0.66303348 0.25149353 0.02882876 0.30747747 0.11662849
  0.07434107 0.79289575 0.30075126 0.02492478 0.26583898 0.1008347 ]
 [0.02314989 0.05256738 0.21187639 0.01392453 0.031619   0.12744251
  0.09110979 0.20688666 0.83387071 0.01225544 0.02782893 0.11216639]
 [0.01775702 0.18939019 0.07183711 0.01068075 0.11391718 0.04320963
  0.06988538 0.74537297 0.28272552 0.00940049 0.1002623  0.03803024]]


It can be shown that the Kronecker product satisfies the following conditions:

<a id='eq2'></a>
$$
\begin{align}
\mathbf{A} \otimes (\mathbf{B} + \mathbf{C}) &= \mathbf{A} \otimes \mathbf{B} + \mathbf{A} \otimes \mathbf{C} \tag{2a} \\
(\mathbf{B} + \mathbf{C}) \otimes \mathbf{A} &= \mathbf{B} \otimes \mathbf{A} + \mathbf{C} \otimes \mathbf{A} \tag{2b} \\
(k\mathbf{A}) \otimes \mathbf{B} &= \mathbf{A} \otimes (k\mathbf{B}) = k(\mathbf{A} \otimes \mathbf{B}) \tag{2c} \\
(\mathbf{A} \otimes \mathbf{B}) \otimes \mathbf{C} &= \mathbf{A} \otimes (\mathbf{B} \otimes \mathbf{C}) \tag{2d} \\
(\mathbf{A} \otimes \mathbf{B})^{\top} &= \mathbf{A}^{\top} \otimes \mathbf{B}^{\top} \tag{2e} \\
(\mathbf{A} \otimes \mathbf{B})^{\ast} &= \mathbf{A}^{\ast} \otimes \mathbf{B}^{\ast} \tag{2f}
\end{align}
$$

where $\mathbf{C}$ is an arbitrary matrix.

In [9]:
C = np.random.rand(B.shape[0], B.shape[1])
A_kron_B_plus_C = np.kron(A, B+C)
A_kron_C = np.kron(A, C)
np.allclose(A_kron_B_plus_C, A_kron_B + A_kron_C)

True

In [10]:
AT_kron_BT = np.kron(A.T, B.T)
np.allclose(A_kron_B.T, AT_kron_BT)

True

Another very important property of the Kronecker product can be defined as follows:

The matrix-vector product

<a id='eq3'></a>
$$
\left( \mathbf{A} \otimes \mathbf{B} \right) \mathbf{v} = \mathbf{w} \: , \tag{3}
$$

where $\mathbf{v}$ is an $MP \times 1$ vector and $\mathbf{w}$ is an $NL \times 1$ vector,  can be rewritten as follows:

<a id='eq4'></a>
$$
\mathbf{A} \mathbf{V} \mathbf{B}^{\top} = \mathbf{W} \: , \tag{4}
$$

where $\mathbf{V}$ is an $M \times P$ matrix obtained by reorganizing $\mathbf{v}$ along its rows and $\mathbf{W}$ is a $N \times L$ matrix obtained by reorganizing $\mathbf{w}$ along its rows (Jain, 1989; Horn and Johnson, 1991).

In [11]:
print(N, M, L, P)

3 4 2 3


In [12]:
A_kron_B.shape

(6, 12)

In [13]:
v = np.arange(M*P)

In [14]:
v.shape

(12,)

In [15]:
v

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [16]:
w = np.dot(A_kron_B, v)

In [17]:
w.shape

(6,)

In [18]:
w

array([17.75807705, 15.90585256, 17.3616674 , 15.45978049, 11.57003195,
       10.44111077])

In [19]:
# reorganize v along the rows of V
V = np.reshape(v, (M, P))

In [20]:
V.shape

(4, 3)

In [21]:
V

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [22]:
v

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [23]:
# reorganize w along the rows of W
W = np.reshape(w, (N, L))

In [24]:
W.shape

(3, 2)

In [25]:
W

array([[17.75807705, 15.90585256],
       [17.3616674 , 15.45978049],
       [11.57003195, 10.44111077]])

In [26]:
w

array([17.75807705, 15.90585256, 17.3616674 , 15.45978049, 11.57003195,
       10.44111077])

In [27]:
np.allclose(multi_dot([A, V, B.T]), W)

True

Similarly to equations [3](#eq3) and [4](#eq4), the matrix-vector product

<a id='eq5'></a>
$$
\left( \mathbf{B}^{\top} \otimes \mathbf{A} \right) \mathbf{v} = \mathbf{w} \: , \tag{5}
$$

where $\mathbf{v}$ is an $LM \times 1$ vector and $\mathbf{w}$ is an $PN \times 1$ vector, can be rewritten as follows:

<a id='eq6'></a>
$$
\mathbf{A} \mathbf{V} \mathbf{B} = \mathbf{W} \: , \tag{6}
$$

where $\mathbf{V}$ is an $M \times L$ matrix obtained by reorganizing $\mathbf{v}$ along its columns and $\mathbf{W}$ is a $L \times P$ matrix obtained by reorganizing $\mathbf{w}$ along its columns (Magnus and Neudecker, 2007).

In [28]:
BT_kron_A = np.kron(B.T, A)

In [29]:
BT_kron_A.shape

(9, 8)

In [30]:
BT_kron_A

array([[0.02268651, 0.09910833, 0.09908743, 0.01611809, 0.01740159,
        0.07602063, 0.0760046 , 0.01236332],
       [0.08104512, 0.03758415, 0.09691868, 0.03249451, 0.06216532,
        0.02882876, 0.07434107, 0.02492478],
       [0.02314989, 0.01392453, 0.09110979, 0.01225544, 0.01775702,
        0.01068075, 0.06988538, 0.00940049],
       [0.05151517, 0.22504927, 0.22500182, 0.03660001, 0.18559926,
        0.81080935, 0.81063838, 0.13186281],
       [0.18403241, 0.08534384, 0.22007715, 0.0737866 , 0.66303348,
        0.30747747, 0.79289575, 0.26583898],
       [0.05256738, 0.031619  , 0.20688666, 0.02782893, 0.18939019,
        0.11391718, 0.74537297, 0.1002623 ],
       [0.20763536, 0.90707632, 0.90688505, 0.14751881, 0.07039918,
        0.30754602, 0.30748117, 0.05001654],
       [0.74175509, 0.34398411, 0.88703585, 0.2974019 , 0.25149353,
        0.11662849, 0.30075126, 0.1008347 ],
       [0.21187639, 0.12744251, 0.83387071, 0.11216639, 0.07183711,
        0.04320963, 0.282725

In [31]:
v = np.arange(L*M)

In [32]:
v.shape

(8,)

In [33]:
v

array([0, 1, 2, 3, 4, 5, 6, 7])

In [34]:
w = np.dot(BT_kron_A, v)

In [35]:
w.shape

(9,)

In [36]:
w

array([ 1.33791778,  1.34223001,  0.84245801, 11.36816664, 11.55462656,
        7.0300997 ,  7.17773252,  7.1097286 ,  4.59764446])

In [37]:
# reorganize v along the columns of V
V = np.reshape(v, (L, M)).T

In [38]:
V.shape

(4, 2)

In [39]:
V

array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

In [40]:
v

array([0, 1, 2, 3, 4, 5, 6, 7])

In [41]:
# reorganize w along the columns of W
W = np.reshape(w, (P, N)).T

In [42]:
W.shape

(3, 3)

In [43]:
W

array([[ 1.33791778, 11.36816664,  7.17773252],
       [ 1.34223001, 11.55462656,  7.1097286 ],
       [ 0.84245801,  7.0300997 ,  4.59764446]])

In [44]:
w

array([ 1.33791778,  1.34223001,  0.84245801, 11.36816664, 11.55462656,
        7.0300997 ,  7.17773252,  7.1097286 ,  4.59764446])

In [45]:
np.allclose(multi_dot([A, V, B]), W)

True