# LDL<sup>T</sup> decomposition

Consider a $N \times N$ matrix $\mathbf{A}$ that is symmetric and admits an LU decomposition, e.g., the matrix $\mathbf{A}$ satisfies the following equations:

$$
\begin{split}
\mathbf{A} &= \mathbf{A}^{\top} \\
\mathbf{A} &= \mathbf{L} \, \mathbf{U}
\end{split}\: .
$$

By considering the existence of the inverse $\mathbf{L}^{-1}$, we may rewrite the equation above as follows:

$$
\begin{split}
\mathbf{L}^{-1} \, \mathbf{A} &= \mathbf{U} \\
\mathbf{L}^{-1} \, \mathbf{A} \, \mathbf{L}^{-\top} &= \mathbf{U} \, \mathbf{L}^{-\top}
\end{split} \: ,
$$

where $\mathbf{L}^{-\top} = \left( \mathbf{L}^{-1} \right)^{\top} = \left( \mathbf{L}^{\top} \right)^{-1}$. Notice that

$$
\begin{split}
\left( \mathbf{L}^{-1} \, \mathbf{A} \, \mathbf{L}^{-\top} \right)^{\top} 
&= \left( \mathbf{L}^{-\top} \right)^{\top} \, \mathbf{A}^{\top} \, \left( \mathbf{L}^{-1} \right)^{\top}\\
&= \left[ \left( \mathbf{L}^{-1} \right)^{\top} \right]^{\top} \, \mathbf{A} \, \mathbf{L}^{-\top} \\
&= \mathbf{L}^{-1} \, \mathbf{A} \, \mathbf{L}^{-\top}
\end{split} \: ,
$$

which means that $\mathbf{L}^{-1} \, \mathbf{A} \, \mathbf{L}^{-\top}$ **and, consequently,** $\mathbf{U} \, \mathbf{L}^{-\top}$ **are symmetric matrices**. Now, let's analyze the matrix $\mathbf{U} \, \mathbf{L}^{-\top}$. First, consider two square matrices $\mathbf{B}$ and $\mathbf{C}$. Then, bear in mind that:

1. If $\mathbf{B}$ is upper (lower) triangular, then $\mathbf{B}^{-1}$ is also upper (lower) triangular;

2. If $\mathbf{B}$ and $\mathbf{C}$ are upper (lower) triangular, then $\mathbf{BC}$ is also upper (lower) triangular;

3. If $\mathbf{B}$ is unit upper (lower) triangular, then $\mathbf{B}^{-1}$ is also unit upper (lower) triangular;

4. If $\mathbf{B}$ and $\mathbf{C}$ are unit upper (lower) triangular, then $\mathbf{BC}$ is also unit upper (lower) triangular.

These statements can be verified numericaly by running the cell below. It uses the routines [`numpy.random.rand`](http://docs.scipy.org/doc/numpy/reference/generated/numpy.random.rand.html), [`numpy.triu`](http://docs.scipy.org/doc/numpy/reference/generated/numpy.triu.html), [`numpy.tril`](http://docs.scipy.org/doc/numpy/reference/generated/numpy.tril.html), [`numpy.indentity`](http://docs.scipy.org/doc/numpy/reference/generated/numpy.identity.html), [`numpy.dot`](http://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) and [`numpy.linalg.inv`](http://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.inv.html).

In [1]:
import numpy as np

In [2]:
N = 5

In [3]:
#Example of upper triangular matrices
B = np.triu(np.reshape(np.random.rand(N*N), (N,N)))
C = np.triu(np.reshape(np.random.rand(N*N), (N,N)))

#Example of lower triangular matrices
#B = np.tril(np.reshape(np.random.rand(N*N), (N,N)))
#C = np.tril(np.reshape(np.random.rand(N*N), (N,N)))

#Example of unit upper triangular matrices
#B = np.triu(np.reshape(np.random.rand(N*N), (N,N)), k=1)
#B += np.identity(N)
#C = np.triu(np.reshape(np.random.rand(N*N), (N,N)), k=1)
#C += np.identity(N)

#Example of unit lower triangular matrices
#B = np.tril(np.reshape(np.random.rand(N*N), (N,N)), k=1)
#B += np.identity(N)
#C = np.tril(np.reshape(np.random.rand(N*N), (N,N)), k=1)
#C += np.identity(N)

Binv = np.linalg.inv(B)

BC = np.dot(B,C)

print 'B = \n', B
print '\n'
print 'B^-1 = \n', Binv
print '\n'
print 'BC = \n', BC

B = 
[[ 0.99757241  0.04286511  0.98990561  0.95022591  0.46026   ]
 [ 0.          0.74911992  0.06705569  0.2417393   0.69253886]
 [ 0.          0.          0.32453677  0.99141715  0.31870066]
 [ 0.          0.          0.          0.65654067  0.1887834 ]
 [ 0.          0.          0.          0.          0.82577037]]


B^-1 = 
[[ 1.0024335  -0.05735987 -3.04578192  3.16959538 -0.05973863]
 [ 0.          1.33489976 -0.2758166  -0.07501199 -0.9959258 ]
 [ 0.          0.          3.08131491 -4.65297671 -0.12547355]
 [ 0.          0.          0.          1.52313489 -0.34821131]
 [ 0.          0.          0.          0.          1.21099041]]


BC = 
[[ 0.23320059  0.69716426  1.16162772  1.86325092  1.19381733]
 [ 0.          0.49958741  0.08478676  0.52071042  1.24783153]
 [ 0.          0.          0.14745531  0.47420225  0.56253829]
 [ 0.          0.          0.          0.11368551  0.287866  ]
 [ 0.          0.          0.          0.          0.54279823]]


Then, we conclude that, besides being symmetric, $\mathbf{U} \, \mathbf{L}^{\top}$ is also upper triangular. In this case, $\mathbf{U} \, \mathbf{L}^{\top}$ must be a diagonal matrix, which we conveniently represent as $\mathbf{D}$. So,

$$
\mathbf{L}^{-1} \, \mathbf{A} \, \mathbf{L}^{-\top} = \mathbf{D}
$$

and, finally,

$$
\mathbf{A} = \mathbf{L} \, \mathbf{D} \, \mathbf{L}^{\top} \: .
$$

This is the LDL<sup>T</sup> decomposition. Any matrix that admits the LU decomposition and is symmetric admits a LDL<sup>T</sup> decomposition as well.

In a most rigorous definition (Golub and Van Loan, 2013):

**THEOREM:** If $\mathbf{A} \in \mathbb{R}^{N \times N}$ is symmetric and the principal submatrix $\mathbf{A} \left[1:k \, , 1:k \right]$ is nonsingular for $k = 1 : N-1$, then there exists a unit lower triangular matrix $\mathbf{L} \in \mathbb{R}^{N \times N}$ and a diagonal matrix $\mathbf{D} \in \mathbb{R}^{N \times N}$ such that $\mathbf{A} = \mathbf{L} \mathbf{D} \mathbf{L}^{\top}$. The factorization is unique.

The following cells illustrate the LDL<sup>T</sup> algorithm for the particular case in which $N = 4$.

$$
\begin{split}
\begin{bmatrix}
a_{11} & a_{21} & a_{31} & a_{41} \\
a_{21} & a_{22} & a_{32} & a_{42} \\
a_{31} & a_{32} & a_{33} & a_{43} \\
a_{41} & a_{42} & a_{43} & a_{44}
\end{bmatrix}
&=
\begin{bmatrix}
1 &  &  &  \\
l_{21} & 1 & & \\
l_{31} & l_{32} & 1 & \\
l_{41} & l_{42} & l_{43} & 1
\end{bmatrix}
\begin{bmatrix}
d_{11} &  &  &  \\
& d_{22} & & \\
& & d_{33} & \\
& & & d_{44}
\end{bmatrix}
\begin{bmatrix}
1 & l_{21} & l_{31} & l_{41} \\
 & 1 & l_{32} & l_{42} \\
 & & 1 & l_{43} \\
 & & & 1
\end{bmatrix} \\\\
&=
\begin{bmatrix}
1 &  &  &  \\
l_{21} & 1 & & \\
l_{31} & l_{32} & 1 & \\
l_{41} & l_{42} & l_{43} & 1
\end{bmatrix}
\begin{bmatrix}
d_{11} & d_{11} \, l_{21} & d_{11} \, l_{31} & d_{11} \, l_{41} \\
 & d_{22} & d_{22} \, l_{32} & d_{22} \, l_{42} \\
 & & d_{33} & d_{33} \, l_{43} \\
 & & & d_{44}
\end{bmatrix}
\end{split}
$$

Column 1 $\left( \, j = 1 \, \right)$

$$
\begin{split}
a_{11} &= d_{11} &\longrightarrow \: &d_{11} = a_{11} \\\\
a_{21} &= d_{11} l_{21} &\longrightarrow \: &l_{21} = \frac{a_{21}}{d_{11}} \\\\
a_{31} &= d_{11} l_{31} &\longrightarrow \: &l_{31} = \frac{a_{31}}{d_{11}} \\\\
a_{41} &= d_{11} l_{41} &\longrightarrow \: &l_{41} = \frac{a_{41}}{d_{11}}
\end{split}
$$

Column 2 $\left( \, j = 2 \, \right)$

$$
\begin{split}
a_{22} &= (d_{11} l_{21}) l_{21} + d_{22} &\longrightarrow \: 
&d_{22} = a_{22} - (d_{11} l_{21}) l_{21} \\\\
a_{32} &= (d_{11} l_{21}) l_{31} + d_{22} l_{32} &\longrightarrow \: 
&l_{32} = \frac{a_{32} - (d_{11} l_{21}) l_{31}}{d_{22}} \\\\
a_{42} &= (d_{11} l_{21}) l_{41} + d_{22} l_{42} &\longrightarrow \: 
&l_{42} = \frac{a_{42} - (d_{11} l_{21}) l_{41}}{d_{22}} \\\\
\end{split}
$$

Column 3 $\left( \, j = 3 \, \right)$

$$
\begin{split}
a_{33} &= (d_{11} l_{31}) l_{31} + (d_{22} l_{32}) l_{32} + d_{33} &\longrightarrow \: 
&d_{33} = a_{33} - (d_{11} l_{31}) l_{31} - (d_{22} l_{32}) l_{32} \\\\
a_{43} &= (d_{11} l_{31}) l_{41} + (d_{22} l_{32}) l_{42} + d_{33} l_{43} &\longrightarrow \: 
&l_{43} = \frac{a_{43} -(d_{11} l_{31}) l_{41} - (d_{22} l_{32}) l_{42}}{d_{33}} \\\\
\end{split}
$$

Column 4 $\left( \, j = 4 \, \right)$

$$
\begin{split}
a_{44} &= (d_{11} l_{41}) l_{41} + (d_{22} l_{42}) l_{42} + (d_{33} l_{43}) l_{43} + d_{44} &\longrightarrow \: 
&l_{44} = a_{44} - (d_{11} l_{41}) l_{41} - (d_{22} l_{42}) l_{42} - (d_{33} l_{43}) l_{43}
\end{split}
$$

The example given above can be easily generalized for any symmetric $N \times N$ matrix $\mathbf{A}$. Based on the example given above, the matrices $\mathbf{L}$ and $\mathbf{D}$ can be calculated as follows:

    for j = 1:N

        v = L[j,:j-1]*d[:j-1]

        d[j] = A[j,j] - dot(L[j,:j-1], v[:j-1])

        L[j+1:,j] = (A[j+1:,j] - dot(L[j+1:,:j-1],v[:j-1]))/d[j]

where `v` is an auxiliary variable and `d` is an 1D array containing the diagonal elements of $\mathbf{D}$.

### Solving a linear system by applying the LDL<sup>T</sup> decomposition

Consider a linear system

$$
\mathbf{A} \mathbf{x} = \mathbf{y} \: ,
$$

where $\mathbf{A}$ is a square symmetric matrix that admits a LU decomposition. In this case, the linear system can be rewritten as follows:

$$
\begin{split}
\mathbf{A} \, &\mathbf{x} &= \mathbf{y} \\
\mathbf{L} \, \mathbf{D} \, \mathbf{L}^{\top} &\mathbf{x} &= \mathbf{y}
\end{split} \: .
$$

So, the linear system can be solved in three steps:

$$
\begin{split}
\mathbf{L} \, &\mathbf{w} &= \mathbf{y} \\
\mathbf{D} \, &\mathbf{z} &= \mathbf{w} \\
\mathbf{L}^{\top} &\mathbf{x} &= \mathbf{z}
\end{split} \: .
$$

## Computing inverses by using the LDL<sup>T</sup> decomposition

As we have learned in a previous class, each column of the inverse of a matrix can be computed by solving a linear system. It means that computing the inverse of an $N \times N$ matrix requires the solution of $N$ linear systems. Note that, by using the Gaussian elimination (with or without partial pivoting), we need to compute and solve one equivalent triangular system for each one of the $N$ columns of the inverse matrix. If the matrix is symmetric, we may use the LDL<sup>T</sup> decomposition to compute its inverse. In this case, we need to compute the matrices $\mathbf{L}$ and $\mathbf{D}$ just once and use them to solve the $N$ required linear systems, each one for a different column of the inverse.

As we have learned in a previous class, each column of the inverse of a matrix can be computed by solving a linear system. It means that computing the inverse of an $N \times N$ matrix requires the solution of $N$ linear systems. Note that, by using the Gaussian elimination (with or without partial pivoting), we need to compute and solve one equivalent triangular system for each one of the $N$ columns of the inverse matrix. If the matrix is symmetric, we may use the LDL<sup>T</sup> decomposition to compute its inverse. In this case, we need to compute the matrices $\mathbf{L}$ and $\mathbf{D}$ just once and use them to solve the $N$ required linear systems, each one for a different collumn of the inverse.

### Exercise

In your `my_functions.py` file:

1) Implement the algorithm presented above for calculating the matrices `L` and `D` from a symmetric matrix `A`. The function must receive a symmetric matrix `A` and return a lower triangular matrix `L` and an 1D array `d` with the diagonal elements of the matrix `D`.

2) Create a function to solve a linear system by using the calculated `L` and `d`. Use the functions you have implemented previously for solving triangular and diagonal systems.

3) Create a function to compute the inverse of a matrix. The code must receive a matrix `A` and calculate its inverse `Ainv`, column by column, by using the LDL<sup>T</sup> decomposition.

In your `test_my_functions.py` file:

4) Use the function implemented in item 1 to verify if $\mathbf{A} = \mathbf{L}\mathbf{D}\mathbf{L}^{\top}$.

5) Compare the solution obtained by using the function implemented in 2 with the solution obtained by using the routine [`numpy.linalg.solve`](http://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.solve.html)

6) Use the function implemented in item 3 to compute the inverse matrix and verify if $\mathbf{A} \mathbf{A}^{-1} = \mathbf{I}$.