In [1]:
import numpy as np

In [2]:
N = 5

In [3]:
A = np.reshape(np.random.rand(N*N), (N,N))

A = np.dot(A.T, A)

In [4]:
print A

[[ 1.21883681  1.12427711  0.84556036  0.91567967  1.26498952]
 [ 1.12427711  1.37911447  1.16736836  0.77475554  0.92861631]
 [ 0.84556036  1.16736836  1.15172195  0.53171608  0.69847219]
 [ 0.91567967  0.77475554  0.53171608  0.85274456  1.06439242]
 [ 1.26498952  0.92861631  0.69847219  1.06439242  1.72352733]]


In [5]:
#v = np.zeros(N)
d = np.zeros(N)
L = np.identity(N)

In [6]:
for j in range(N):

    v = L[j,:j]*d[:j]
        
    d[j] = A[j,j] - np.dot(L[j,:j], v[:j])
    
    L[j+1:,j] = (A[j+1:,j] - np.dot(L[j+1:,:j],v[:j]))/d[j]

In [7]:
A_calc = np.dot(L, np.dot(np.diag(d), L.T))

In [8]:
np.allclose(A, A_calc)

True

In [9]:
v1 = np.zeros(N)
d1 = np.zeros(N)
L1 = np.identity(N)

In [10]:
for j in range(N):
    
    for i in range(j):
        v1[i] = d1[i]*L1[j,i]
        
    d1[j] = A[j,j]
    for i in range(j):
        d1[j] -= v1[i]*L1[j,i]
    
    for i in range(j+1,N):
        L1[i,j] = A[i,j]
        for k in range(j):
            L1[i,j] -= v1[k]*L1[i,k]
        L1[i,j] = L1[i,j]/d1[j]

In [11]:
A_calc = np.dot(L1, np.dot(np.diag(d1), L1.T))

In [12]:
np.allclose(A, A_calc)

True

In [13]:
np.allclose(L, L1)

True

In [14]:
np.allclose(d, d1)

True

In [15]:
y = np.random.rand(N)

In [16]:
x = np.linalg.solve(A,y)

In [17]:
print x

[ 21.51393868 -28.16059541  16.97716206   9.84692573 -13.54234636]


In [18]:
w = np.linalg.solve(L,y)

In [19]:
z = np.linalg.solve(np.diag(d),w)

In [20]:
x_calc = np.linalg.solve(L.T, z)

In [21]:
np.allclose(x, x_calc)

True