In [1]:
import numpy as np

In [2]:
N = 5

In [3]:
A = np.reshape(np.random.rand(N*N), (N,N))

A = np.dot(A.T, A)

In [4]:
def permut (C, i):
    p = [j for j in range(C.shape[0])]
    imax = i + np.argmax(np.abs(np.diag(C)[i:]))
    if imax != i:
        p[i], p[imax] = p[imax], p[i]
    C = C[p,:]
    C = C[:,p]
    return p, C

In [5]:
print A

[[ 1.10047269  1.35077762  1.05271579  1.16353626  1.13307255]
 [ 1.35077762  1.83819919  1.5097005   1.53238027  1.50675037]
 [ 1.05271579  1.5097005   1.35227312  1.04567117  1.11098115]
 [ 1.16353626  1.53238027  1.04567117  1.79026306  1.61219812]
 [ 1.13307255  1.50675037  1.11098115  1.61219812  1.54008367]]


In [6]:
p, C = permut(A,0)
P = np.identity(N)[p,:]

In [7]:
print C

[[ 1.83819919  1.35077762  1.5097005   1.53238027  1.50675037]
 [ 1.35077762  1.10047269  1.05271579  1.16353626  1.13307255]
 [ 1.5097005   1.05271579  1.35227312  1.04567117  1.11098115]
 [ 1.53238027  1.16353626  1.04567117  1.79026306  1.61219812]
 [ 1.50675037  1.13307255  1.11098115  1.61219812  1.54008367]]


In [8]:
print P

[[ 0.  1.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  1.]]


In [9]:
np.allclose(C, np.dot(P,np.dot(A,P.T)))

True

In [10]:
v = np.zeros(N)
C = np.copy(A)
P = np.identity(N)

In [11]:
for j in range(N):
    
    p, C = permut(C,j)
    P = P[p,:]

    alpha = C[j,j]
    
    v = C[j+1:,j]

    C[j+1:,j] = v/alpha
    
    C[j+1:,j+1:] -= np.outer(v,v)/alpha

In [12]:
L = np.identity(N) + np.tril(C,k=-1)

In [13]:
print C

[[ 1.83819919  1.53238027  1.5097005   1.50675037  1.35077762]
 [ 0.83363124  1.41220771  0.67321117  1.24046596  0.83028431]
 [ 0.8212932   0.47670832  0.82440682  0.44824002  0.52593179]
 [ 0.8196883   0.87838775  0.54371216  0.2696265   0.01896055]
 [ 0.73483746  0.58793356  0.63795177  0.07032155  0.04993699]]


In [14]:
print L

[[ 1.          0.          0.          0.          0.        ]
 [ 0.83363124  1.          0.          0.          0.        ]
 [ 0.8212932   0.47670832  1.          0.          0.        ]
 [ 0.8196883   0.87838775  0.54371216  1.          0.        ]
 [ 0.73483746  0.58793356  0.63795177  0.07032155  1.        ]]


In [15]:
D = np.diag(np.diag(C))

In [29]:
print D

[[ 1.83819919  0.          0.          0.          0.        ]
 [ 0.          1.41220771  0.          0.          0.        ]
 [ 0.          0.          0.82440682  0.          0.        ]
 [ 0.          0.          0.          0.2696265   0.        ]
 [ 0.          0.          0.          0.          0.04993699]]


In [16]:
PAPt = np.dot(P,np.dot(A,P.T))
A_til = np.dot(P.T,np.dot(A,P))
LDLt = np.dot(L, np.dot(D,L.T))

In [17]:
PA_tilPt = np.dot(P,np.dot(A_til,P.T))

In [18]:
np.allclose(PA_tilPt, LDLt)

False

In [27]:
np.allclose(A_til, LDLt)

False

In [19]:
np.allclose(PA_tilPt, A)

True

In [20]:
np.allclose(PAPt, LDLt)

False

In [21]:
np.allclose(PAPt, A)

False

In [22]:
print A

[[ 1.10047269  1.35077762  1.05271579  1.16353626  1.13307255]
 [ 1.35077762  1.83819919  1.5097005   1.53238027  1.50675037]
 [ 1.05271579  1.5097005   1.35227312  1.04567117  1.11098115]
 [ 1.16353626  1.53238027  1.04567117  1.79026306  1.61219812]
 [ 1.13307255  1.50675037  1.11098115  1.61219812  1.54008367]]


In [23]:
print PA_tilPt

[[ 1.10047269  1.35077762  1.05271579  1.16353626  1.13307255]
 [ 1.35077762  1.83819919  1.5097005   1.53238027  1.50675037]
 [ 1.05271579  1.5097005   1.35227312  1.04567117  1.11098115]
 [ 1.16353626  1.53238027  1.04567117  1.79026306  1.61219812]
 [ 1.13307255  1.50675037  1.11098115  1.61219812  1.54008367]]


In [24]:
print LDLt

[[ 1.83819919  1.53238027  1.5097005   1.50675037  1.35077762]
 [ 1.53238027  2.68964777  1.93174466  2.49654013  1.95633473]
 [ 1.5097005   1.93174466  2.38523895  2.2770643   2.0311197 ]
 [ 1.50675037  2.49654013  2.2770643   2.8380158   2.14144424]
 [ 1.35077762  1.95633473  2.0311197   2.14144424  1.86754345]]


In [28]:
print C

[[ 1.83819919  1.53238027  1.5097005   1.50675037  1.35077762]
 [ 0.83363124  1.41220771  0.67321117  1.24046596  0.83028431]
 [ 0.8212932   0.47670832  0.82440682  0.44824002  0.52593179]
 [ 0.8196883   0.87838775  0.54371216  0.2696265   0.01896055]
 [ 0.73483746  0.58793356  0.63795177  0.07032155  0.04993699]]


In [25]:
print np.diag(LDLt)

[ 1.83819919  2.68964777  2.38523895  2.8380158   1.86754345]


In [26]:
print np.diag(C)

[ 1.83819919  1.41220771  0.82440682  0.2696265   0.04993699]
