In [1]:
import numpy as np

In [2]:
N = 5

In [3]:
A = np.reshape(np.random.rand(N*N), (N,N))

A = np.dot(A.T, A)

In [4]:
v = np.zeros(N)
d = np.zeros(N)
L = np.identity(N)

In [6]:
for j in range(N):
    
    L[j,j] = 1.

    v[:j] = L[j,:j]*d[:j]
        
    d[j] = A[j,j] - np.dot(L[j,:j], v[:j])
    
    L[j+1:,j] = (A[j+1:,j] - np.dot(L[j+1:,:j],v[:j]))/d[j]
    
    print np.dot(L[j+1:,:j],v[:j])

[ 0.  0.  0.  0.]
[ 1.28583394  1.50651059  1.12025257]
[ 1.03582655  0.87974366]
[ 1.33401399]
[]


In [7]:
A_calc = np.dot(L, np.dot(np.diag(d), L.T))

In [8]:
np.allclose(A, A_calc)

True

In [9]:
v1 = np.zeros(N)
d1 = np.zeros(N)
L1 = np.identity(N)

In [10]:
for j in range(N):
    
    for i in range(j):
        v1[i] = d1[i]*L1[j,i]
        
    d1[j] = A[j,j]
    for i in range(j):
        d1[j] -= v1[i]*L1[j,i]
    
    for i in range(j+1,N):
        L1[i,j] = A[i,j] - np.dot(L1[i,:j],v1[:j])
        #for k in range(j):
        #    L1[i,j] -= v1[k]*L1[i,k]
        L1[i,j] = L[i,j]/d1[j]

In [11]:
A_calc = np.dot(L1, np.dot(np.diag(d1), L1.T))

In [12]:
np.allclose(A, A_calc)

False

In [13]:
L

array([[ 1.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 1.71458863,  1.        ,  0.        ,  0.        ,  0.        ],
       [ 0.8412663 ,  0.46013694,  1.        ,  0.        ,  0.        ],
       [ 0.98564562,  0.83565593,  0.13315588,  1.        ,  0.        ],
       [ 0.73293348,  0.92984122,  0.99748548,  0.04342415,  1.        ]])

In [15]:
d

array([ 0.89143863,  0.77149984,  0.68175157,  0.8141073 ,  0.09191125])