# LDL<sup>T</sup> decomposition

Consider an $N \times N$ matrix $\mathbf{A}$ that is symmetric and admits an LU decomposition, e.g., the matrix $\mathbf{A}$ satisfies the following equations:

<a id='eq1'></a>
$$
\begin{align}
\mathbf{A} &= \mathbf{A}^{\top} \tag{1a} \\
\mathbf{A} &= \mathbf{L} \, \mathbf{U} \tag{1b}
\end{align}
$$

By considering the existence of the inverse $\mathbf{L}^{-1}$, we may rewrite the equation above as follows:

<a id='eq2'></a>
$$
\begin{align}
\mathbf{L}^{-1} \, \mathbf{A} &= \mathbf{U} \tag{2a} \\
\mathbf{L}^{-1} \, \mathbf{A} \, \mathbf{L}^{-\top} &= \mathbf{U} \, \mathbf{L}^{-\top} \tag{2b}
\end{align}
$$

where $\mathbf{L}^{-\top} = \left( \mathbf{L}^{-1} \right)^{\top} = \left( \mathbf{L}^{\top} \right)^{-1}$. Notice that

<a id='eq3'></a>
$$
\begin{split}
\left( \mathbf{L}^{-1} \, \mathbf{A} \, \mathbf{L}^{-\top} \right)^{\top} 
&= \left( \mathbf{L}^{-\top} \right)^{\top} \, \mathbf{A}^{\top} \, \left( \mathbf{L}^{-1} \right)^{\top}\\
&= \left[ \left( \mathbf{L}^{-1} \right)^{\top} \right]^{\top} \, \mathbf{A} \, \mathbf{L}^{-\top} \\
&= \mathbf{L}^{-1} \, \mathbf{A} \, \mathbf{L}^{-\top}
\end{split} \: , \tag{3}
$$

which means that $\mathbf{L}^{-1} \, \mathbf{A} \, \mathbf{L}^{-\top}$ **and, consequently,** $\mathbf{U} \, \mathbf{L}^{-\top}$ **are symmetric matrices** ([equation 2b](#eq2)). Now, let's analyze the matrix $\mathbf{U} \, \mathbf{L}^{-\top}$. First, consider two square matrices $\mathbf{B}$ and $\mathbf{C}$. Then, bear in mind that:

1. If $\mathbf{B}$ is upper (lower) triangular, then $\mathbf{B}^{-1}$ is also upper (lower) triangular;

2. If $\mathbf{B}$ and $\mathbf{C}$ are upper (lower) triangular, then $\mathbf{BC}$ is also upper (lower) triangular;

3. If $\mathbf{B}$ is unit upper (lower) triangular, then $\mathbf{B}^{-1}$ is also unit upper (lower) triangular;

4. If $\mathbf{B}$ and $\mathbf{C}$ are unit upper (lower) triangular, then $\mathbf{BC}$ is also unit upper (lower) triangular.

Then, we conclude that, besides being symmetric, $\mathbf{U} \, \mathbf{L}^{\top}$ ([equation 2b](#eq2)) is also upper triangular. In this case, $\mathbf{U} \, \mathbf{L}^{\top}$ must be a diagonal matrix, which we conveniently represent as $\mathbf{D}$. So, [equation 2b](#eq2) can be rewritten as follows

<a id='eq4'></a>
$$
\mathbf{L}^{-1} \, \mathbf{A} \, \mathbf{L}^{-\top} = \mathbf{D} \tag{4}
$$

and, finally, matrix $\mathbf{A}$ ([equations 1a-b](#eq1)) is given by

<a id='eq5'></a>
$$
\mathbf{A} = \mathbf{L} \, \mathbf{D} \, \mathbf{L}^{\top} \quad . \tag{5}
$$

This is the LDL<sup>T</sup> decomposition. Any matrix that admits the LU decomposition and is symmetric admits an LDL<sup>T</sup> decomposition.

In a most rigorous definition (Golub and Van Loan, 2013):

**THEOREM:** If $\mathbf{A} \in \mathbb{R}^{N \times N}$ is symmetric and the principal submatrix $\mathbf{A} \left[1:k \, , 1:k \right]$ is nonsingular for $k = 1 : N-1$, then there exists a unit lower triangular matrix $\mathbf{L} \in \mathbb{R}^{N \times N}$ and a diagonal matrix $\mathbf{D} \in \mathbb{R}^{N \times N}$ such that $\mathbf{A} = \mathbf{L} \mathbf{D} \mathbf{L}^{\top}$. The factorization is unique.

### Algorithm for computing the LDL<sup>T</sup>

The following cells illustrate the LDL<sup>T</sup> algorithm for the particular case in which $N = 4$.

$$
\begin{split}
\begin{bmatrix}
a_{00} & a_{10} & a_{20} & a_{30} \\
a_{10} & a_{11} & a_{21} & a_{31} \\
a_{20} & a_{21} & a_{22} & a_{32} \\
a_{30} & a_{31} & a_{32} & a_{33}
\end{bmatrix}
&=
\begin{bmatrix}
1 &  &  &  \\
l_{10} & 1 & & \\
l_{20} & l_{21} & 1 & \\
l_{30} & l_{31} & l_{32} & 1
\end{bmatrix}
\begin{bmatrix}
d_{00} &  &  &  \\
& d_{11} & & \\
& & d_{22} & \\
& & & d_{33}
\end{bmatrix}
\begin{bmatrix}
1 & l_{10} & l_{20} & l_{30} \\
 & 1 & l_{21} & l_{31} \\
 & & 1 & l_{32} \\
 & & & 1
\end{bmatrix} \\\\
&=
\begin{bmatrix}
1 &  &  &  \\
l_{10} & 1 & & \\
l_{20} & l_{21} & 1 & \\
l_{30} & l_{31} & l_{32} & 1
\end{bmatrix}
\begin{bmatrix}
d_{00} & d_{00} \, l_{10} & d_{00} \, l_{20} & d_{00} \, l_{30} \\
 & d_{11} & d_{11} \, l_{21} & d_{11} \, l_{31} \\
 & & d_{22} & d_{22} \, l_{32} \\
 & & & d_{33}
\end{bmatrix}
\end{split}
$$

Column 1 $\left( \, j = 0 \, \right)$

$$
\begin{split}
a_{00} &= d_{00} &\longrightarrow \: &d_{00} = a_{00} \\\\
a_{10} &= d_{00} l_{10} &\longrightarrow \: &l_{10} = \frac{a_{10}}{d_{00}} \\\\
a_{20} &= d_{00} l_{20} &\longrightarrow \: &l_{20} = \frac{a_{20}}{d_{00}} \\\\
a_{30} &= d_{00} l_{30} &\longrightarrow \: &l_{30} = \frac{a_{30}}{d_{00}}
\end{split}
$$

Column 2 $\left( \, j = 1 \, \right)$

$$
\begin{split}
a_{11} &= (d_{00} l_{10}) l_{10} + d_{11} &\longrightarrow \: 
&d_{11} = a_{11} - (d_{00} l_{10}) l_{10} \\\\
a_{21} &= (d_{00} l_{10}) l_{20} + d_{11} l_{21} &\longrightarrow \: 
&l_{21} = \frac{a_{21} - (d_{00} l_{10}) l_{20}}{d_{11}} \\\\
a_{31} &= (d_{00} l_{10}) l_{30} + d_{11} l_{31} &\longrightarrow \: 
&l_{31} = \frac{a_{31} - (d_{00} l_{10}) l_{30}}{d_{11}} \\\\
\end{split}
$$

Column 3 $\left( \, j = 2 \, \right)$

$$
\begin{split}
a_{22} &= (d_{00} l_{20}) l_{20} + (d_{11} l_{21}) l_{21} + d_{22} &\longrightarrow \: 
&d_{22} = a_{22} - (d_{00} l_{20}) l_{20} - (d_{11} l_{21}) l_{21} \\\\
a_{32} &= (d_{00} l_{20}) l_{30} + (d_{11} l_{21}) l_{31} + d_{22} l_{32} &\longrightarrow \: 
&l_{32} = \frac{a_{32} -(d_{00} l_{20}) l_{30} - (d_{11} l_{21}) l_{31}}{d_{22}} \\\\
\end{split}
$$

Column 4 $\left( \, j = 3 \, \right)$

$$
\begin{split}
a_{33} &= (d_{00} l_{30}) l_{30} + (d_{11} l_{31}) l_{31} + (d_{22} l_{32}) l_{32} + d_{33} &\longrightarrow \: 
&l_{33} = a_{33} - (d_{00} l_{30}) l_{30} - (d_{11} l_{31}) l_{31} - (d_{22} l_{32}) l_{32}
\end{split}
$$

The example given above can be easily generalized for any symmetric $N \times N$ matrix $\mathbf{A}$. Based on the example given above, the LDL<sup>T</sup> algorithm can be implemented as follows:

    def ldlt_decomp(A, check_input=True):
        N = A.shape[0]
        if check_input is True:
            assert A.ndim == 2, 'A must be a matrix'
            assert A.shape[1] == N, 'A must be square'
            assert np.all(A.T == A), 'A must be symmetric'

        L = identity matrix of order N
        d = vector of zeros with N elements

        for j = 0:N-1

            v = L[j,:j-1]*d[:j-1]

            d[j] = A[j,j] - dot(L[j,:j-1], v)

            L[j+1:,j] = (A[j+1:,j] - dot(L[j+1:,:j-1],v))/d[j]
        
        return L, d

where `v` is an auxiliary variable. This algorithm receives a square matrix $\mathbf{A}$ and returns the lower triangular matrix $\mathbf{L}$ and a vector $\mathbf{d}$ containing the diagonal elements of $\mathbf{D}$. An alternative implementation overwrites the elements below the main diagonal of $\mathbf{A}$ with the corresponding elements of $\mathbf{L}$ and returns only the vector $\mathbf{d}$.

    def ldlt_decomp_overwrite(A, check_input=True):
        N = A.shape[0]
        if check_input is True:
            assert A.ndim == 2, 'A must be a matrix'
            assert A.shape[1] == N, 'A must be square'
            assert np.all(A.T == A), 'A must be symmetric'

        d = vector of zeros with N elements
        
        for j = 0:N-1
        
            v = A[j,:j-1]*d[:j-1]
            
            d[j] = A[j,j] - dot(A[j,:j-1], v)
            
            A[j+1:,j] = (A[j+1:,j] - dot(A[j+1:,:j-1],v))/d[j]

        return d

#### Testing the function `ldlt_decomp`

#### Testing the function `ldlt_decomp_overwrite`

### Solving a linear system by applying the LDL<sup>T</sup> decomposition

Consider a linear system

<a id='eq6'></a>
$$
\mathbf{A} \mathbf{x} = \mathbf{y} \: , \tag{6}
$$

where $\mathbf{A}$ is a square symmetric matrix that admits a LU decomposition. In this case, the linear system can be rewritten as follows:

<a id='eq7'></a>
$$
\begin{align}
\mathbf{A} \, \mathbf{x} &= \mathbf{y} \tag{7a} \\
\mathbf{L} \, \mathbf{D} \, \mathbf{L}^{\top} \mathbf{x} &= \mathbf{y} \tag{7b}
\end{align}
$$

So, the linear system ([equation 6](#eq6)) can be solved in three steps:

<a id='eq8'></a>
$$
\begin{align}
\mathbf{L} \, \mathbf{w} &= \mathbf{y} \tag{8a} \\
\mathbf{D} \, \mathbf{z} &= \mathbf{w} \tag{8b} \\
\mathbf{L}^{\top} \mathbf{x} &= \mathbf{z} \tag{8c}
\end{align}
$$

### Computing inverses by using the LDL<sup>T</sup> decomposition

As we have learned in the notebook `gauss-elim-pivoting`, each column of the inverse of a matrix can be computed by solving a linear system. It means that computing the inverse of an $N \times N$ matrix requires the solution of $N$ linear systems. Note that, if the matrix is symmetric, we may use the LDL<sup>T</sup> decomposition to compute its inverse. In this case, we need to compute the matrices $\mathbf{L}$ and $\mathbf{D}$ just once and use them to solve the $N$ required linear systems, each one for a different column of the inverse.

### References

* Golub, G. H. and C. F. Van Loan, (2013), Matrix computations, 4th edition, Johns Hopkins University Press, ISBN 978-1-4214-0794-4.

### Statements about triangular matrices

These statements can be verified numericaly by running the cells at the end of this notebook. It uses the routines [`numpy.random.rand`](http://docs.scipy.org/doc/numpy/reference/generated/numpy.random.rand.html), [`numpy.triu`](http://docs.scipy.org/doc/numpy/reference/generated/numpy.triu.html), [`numpy.tril`](http://docs.scipy.org/doc/numpy/reference/generated/numpy.tril.html), [`numpy.indentity`](http://docs.scipy.org/doc/numpy/reference/generated/numpy.identity.html), [`numpy.dot`](http://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) and [`numpy.linalg.inv`](http://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.inv.html).

In [1]:
import numpy as np

In [2]:
N = 5

In [3]:
#Example of upper triangular matrices
B = np.triu(np.reshape(np.random.rand(N*N), (N,N)))
C = np.triu(np.reshape(np.random.rand(N*N), (N,N)))

#Example of lower triangular matrices
#B = np.tril(np.reshape(np.random.rand(N*N), (N,N)))
#C = np.tril(np.reshape(np.random.rand(N*N), (N,N)))

#Example of unit upper triangular matrices
#B = np.triu(np.reshape(np.random.rand(N*N), (N,N)), k=1)
#B += np.identity(N)
#C = np.triu(np.reshape(np.random.rand(N*N), (N,N)), k=1)
#C += np.identity(N)

#Example of unit lower triangular matrices
#B = np.tril(np.reshape(np.random.rand(N*N), (N,N)), k=1)
#B += np.identity(N)
#C = np.tril(np.reshape(np.random.rand(N*N), (N,N)), k=1)
#C += np.identity(N)

Binv = np.linalg.inv(B)

BC = np.dot(B,C)

print('B = \n', B)
print('\n')
print('B^-1 = \n', Binv)
print('\n')
print('BC = \n', BC)

B = 
 [[0.35830366 0.18276014 0.26340443 0.50440721 0.54493817]
 [0.         0.94348407 0.13860105 0.03062381 0.9753346 ]
 [0.         0.         0.57398788 0.38955512 0.42186669]
 [0.         0.         0.         0.02900644 0.29509011]
 [0.         0.         0.         0.         0.63521721]]


B^-1 = 
 [[  2.79092878  -0.54062441  -1.15021922 -32.51467088  14.30440342]
 [  0.           1.05990131  -0.25593473   2.31819112  -2.53435099]
 [  0.           0.           1.74219707 -23.39762502   9.71232023]
 [  0.           0.           0.          34.47510346 -16.01540717]
 [  0.           0.           0.           0.           1.57426465]]


BC = 
 [[0.10686431 0.35862642 0.52558321 0.72062197 1.01349923]
 [0.         0.48547806 0.17190221 0.79732817 1.21406876]
 [0.         0.         0.36586855 0.47437335 0.74964302]
 [0.         0.         0.         0.00706524 0.27955112]
 [0.         0.         0.         0.         0.59675359]]


### Exercise

In your `my_functions.py` file:

1) Create a function called `ldlt_decomp` for computing the matrices `L` and `D` from a symmetric matrix `A`. The function must receive a symmetric matrix `A` and return a lower triangular matrix `L` and an 1D array `d` with the diagonal elements of the matrix `D`.

2) Create a function called `ldlt_solve` to solve a linear system by using the calculated `L` and `d`. The function must receive `L`, `d` and `y` and return the solution vector `x`. Use the functions you have implemented previously for solving triangular and diagonal systems.

3) Create a function called `matsym_inverse` to compute the inverse of a symmetric matrix. The code must receive a symmetric matrix `A` and calculate its inverse `Ainv`, column by column, by using the functions `ldlt_decomp` and `ldlt_solve`.

In your `test_my_functions.py` file:

4) Use the function `ldlt_decomp` to verify if a given symmetric matrix $\mathbf{A}$ satisfies the condition  $\mathbf{A} = \mathbf{L}\mathbf{D}\mathbf{L}^{\top}$.

5) Compare the solution obtained by using the function `ldlt_solve` with the solution obtained by using the routine [`numpy.linalg.solve`](http://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.solve.html)

6) Use the function `matsym_inverse` to compute the inverse of a symmetric matrix and verify if $\mathbf{A} \mathbf{A}^{-1} = \mathbf{I}$.