# LDL<sup>T</sup> decomposition

Consider a $N \times N$ matrix $\mathbf{A}$ that is symmetric and admits an LU decomposition, e.g., the matrix $\mathbf{A}$ satisfies the following equation:

$$
\mathbf{A} = \mathbf{L} \, \mathbf{U} \: .
$$

By considering the existence of the inverse $\mathbf{L}^{-1}$, we may rewrite the equation above as follows:

$$
\begin{split}
\mathbf{L}^{-1} \, \mathbf{A} &= \mathbf{U} \\
\mathbf{L}^{-1} \, \mathbf{A} \, \mathbf{L}^{-\top} &= \mathbf{U} \, \mathbf{L}^{-\top}
\end{split} \: ,
$$

where $\mathbf{L}^{-\top} = \left( \mathbf{L}^{-1} \right)^{\top} = \left( \mathbf{L}^{\top} \right)^{-1}$. Notice that

$$
\begin{split}
\left( \mathbf{L}^{-1} \, \mathbf{A} \, \mathbf{L}^{-\top} \right)^{\top} 
&= \left( \mathbf{L}^{-\top} \right)^{\top} \, \mathbf{A}^{\top} \, \left( \mathbf{L}^{-1} \right)^{\top}\\
&= \left[ \left( \mathbf{L}^{-1} \right)^{\top} \right]^{\top} \, \mathbf{A} \, \mathbf{L}^{-\top} \\
&= \mathbf{L}^{-1} \, \mathbf{A} \, \mathbf{L}^{-\top}
\end{split} \: ,
$$

which means that $\mathbf{L}^{-1} \, \mathbf{A} \, \mathbf{L}^{-\top}$ and, consequently, $\mathbf{U} \, \mathbf{L}^{-\top}$ are symmetric matrices. Now, let's analyze the matrix $\mathbf{U} \, \mathbf{L}^{-\top}$. First, consider two square matrices $\mathbf{B}$ and $\mathbf{C}$. Then, bear in mind that:

1. If $\mathbf{B}$ is upper (lower) triangular, then $\mathbf{B}^{-1}$ is also upper (lower) triangular;

2. If $\mathbf{B}$ and $\mathbf{C}$ are upper (lower) triangular, then $\mathbf{BC}$ is also upper (lower) triangular;

3. If $\mathbf{B}$ is unit upper (lower) triangular, then $\mathbf{B}^{-1}$ is also unit upper (lower) triangular;

4. If $\mathbf{B}$ and $\mathbf{C}$ are unit upper (lower) triangular, then $\mathbf{BC}$ is also unit upper (lower) triangular.

These statements can be verified numericaly by running the cell below. It uses the routines [`numpy.random.rand`](http://docs.scipy.org/doc/numpy/reference/generated/numpy.random.rand.html), [`numpy.triu`](http://docs.scipy.org/doc/numpy/reference/generated/numpy.triu.html), [`numpy.tril`](http://docs.scipy.org/doc/numpy/reference/generated/numpy.tril.html), [`numpy.indentity`](http://docs.scipy.org/doc/numpy/reference/generated/numpy.identity.html), [`numpy.dot`](http://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) and [`numpy.linalg.inv`](http://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.inv.html).

In [1]:
import numpy as np

In [2]:
N = 5

In [3]:
#Example of upper triangular matrices
B = np.triu(np.reshape(np.random.rand(N*N), (N,N)))
C = np.triu(np.reshape(np.random.rand(N*N), (N,N)))

#Example of lower triangular matrices
#B = np.tril(np.reshape(np.random.rand(N*N), (N,N)))
#C = np.tril(np.reshape(np.random.rand(N*N), (N,N)))

#Example of unit upper triangular matrices
#B = np.triu(np.reshape(np.random.rand(N*N), (N,N)), k=1)
#B += np.identity(N)
#C = np.triu(np.reshape(np.random.rand(N*N), (N,N)), k=1)
#C += np.identity(N)

#Example of unit lower triangular matrices
#B = np.tril(np.reshape(np.random.rand(N*N), (N,N)), k=1)
#B += np.identity(N)
#C = np.tril(np.reshape(np.random.rand(N*N), (N,N)), k=1)
#C += np.identity(N)

Binv = np.linalg.inv(B)

BC = np.dot(B,C)

print 'B = \n', B
print '\n'
print 'B^-1 = \n', Binv
print '\n'
print 'BC = \n', BC

B = 
[[ 0.76232337  0.773993    0.04934886  0.97607779  0.06170274]
 [ 0.          0.24348637  0.49218532  0.0057127   0.67401715]
 [ 0.          0.          0.11145379  0.69038759  0.35207957]
 [ 0.          0.          0.          0.12305399  0.80226336]
 [ 0.          0.          0.          0.          0.64298304]]


B^-1 = 
[[   1.31177927   -4.16987611   17.83355231 -110.26575224  132.06097998]
 [   0.            4.10700616  -18.13673759  101.56449743 -121.09820518]
 [   0.            0.            8.97232831  -50.33875141   57.89571375]
 [   0.            0.            0.            8.12651439  -10.13962155]
 [   0.            0.            0.            0.            1.55525096]]


BC = 
[[ 0.0034238   1.29782368  1.25710973  1.38242975  0.7138184 ]
 [ 0.          0.22145888  0.64254935  0.42891649  0.45724576]
 [ 0.          0.          0.1037343   0.37293063  0.22156328]
 [ 0.          0.          0.          0.05514951  0.13936707]
 [ 0.          0.          0.          0.  

Then, we conclude that, besides being symmetric, $\mathbf{U} \, \mathbf{L}^{\top}$ is also upper triangular. In this case, $\mathbf{U} \, \mathbf{L}^{\top}$ must be a diagonal matrix, which we conveniently represent as $\mathbf{D}$. So,

$$
\mathbf{L}^{-1} \, \mathbf{A} \, \mathbf{L}^{-\top} = \mathbf{D}
$$

and, finally,

$$
\mathbf{A} = \mathbf{L} \, \mathbf{D} \, \mathbf{L}^{\top} \: .
$$

This is the LDL<sup>T</sup> decomposition. Any matrix that admits the LU decomposition and is symmetric admits a LDL<sup>T</sup> decomposition as well.

It can be shown that, given a symmetric matrix $\mathbf{A}$, the matrices $\mathbf{L}$ and $\mathbf{D}$ can be calculated as follows:

    for j in range(N):

        v = L[j,:j]*d[:j]

        d[j] = A[j,j] - np.dot(L[j,:j], v[:j])

        L[j+1:,j] = (A[j+1:,j] - np.dot(L[j+1:,:j],v[:j]))/d[j]

where `v` is an auxiliary variable and `d` is an 1D array containing the diagonal elements of $\mathbf{D}$.

### Solving a linear system bu applying the LDL<sup>T</sup> decomposition

Consider a linear a linaer system

$$
\mathbf{A} \mathbf{x} = \mathbf{y} \: ,
$$

where $\mathbf{A}$ is a square symmetric matrix that admitis a LU decomposition. In this case, the linear system can be rewritten as follows:

$$
\begin{split}
\mathbf{A} \, &\mathbf{x} &= \mathbf{y} \\
\mathbf{L} \, \mathbf{D} \, \mathbf{L}^{\top} &\mathbf{x} &= \mathbf{y}
\end{split} \: .
$$

So, the linear system can be solved in three steps:

$$
\begin{split}
\mathbf{L} \, &\mathbf{w} &= \mathbf{y} \\
\mathbf{D} \, &\mathbf{z} &= \mathbf{w} \\
\mathbf{L}^{\top} &\mathbf{x} &= \mathbf{z}
\end{split} \: .
$$

### Exercise 18

1. Implement the algorithm presented above for calculating the matrices `L` and `D` from a symmetric matrix `A`. The function must receive a symmetric matrix `A` and return a lower triangular matrix `L` and an 1D array `d` with the diagonal elements of the matrix `D`.

2. Solve a linear system by using the calculated `L` and `d`. Use the functions implemented previously for solving triangular and diagonal systems.

3. Test if `A` = `LDL`<sup>T</sup>

4. Test your solution of the linear system againt the solution obtained by using the routine [`numpy.linalg.solve`](http://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.solve.html)

How to create a symmetric matrix?

In [4]:
N = 5

A = np.reshape(np.random.rand(N*N), (N,N))

A = np.dot(A.T, A)

In [5]:
print A

[[ 2.37236061  2.1176592   2.26495545  1.16510657  1.0490748 ]
 [ 2.1176592   2.56340889  2.10077217  0.99854764  1.29929365]
 [ 2.26495545  2.10077217  2.95203926  1.49470026  1.27651369]
 [ 1.16510657  0.99854764  1.49470026  0.77740187  0.56441059]
 [ 1.0490748   1.29929365  1.27651369  0.56441059  0.91402017]]
