# Matrix-vector product

### Product of a real matrix and a real vector

Let $\mathbf{A}$ be a $N \times M$ real matrix and $\mathbf{x}$ be a $M \times 1$ real vector. $\mathbf{A}$ can be represented by using a *row partition* or by a *column partition* as follows:

$$
\begin{split}
    \mathbf{A} 
    & = \left[
    \begin{array}{ccc}
        a_{00} & \cdots & a_{0(M-1)} \\
        \vdots &        & \vdots \\
        a_{(N-1)0} & \cdots & a_{(N-1)(M-1)}
    \end{array}
    \right]_{N \times M} \\
    & = \left[
    \begin{array}{c}
        \mathbf{A}[0 \, , \, :] \\
        \vdots \\
        \mathbf{A}[N-1 \, , \, :]
    \end{array}
    \right]_{N \times M} \\
    & = \left[
    \begin{array}{ccc}
        \mathbf{A}[:\ , \, 0] &
        \cdots &
        \mathbf{A}[: \, , \, M-1]
    \end{array}
    \right]_{N \times M}
\end{split} \: ,
$$

where $\mathbf{A}[i \, , \, :]$, $i = 0, ..., N-1$, is a $1 \times M$ vector representing the $i$th row of $\mathbf{A}$ and $\mathbf{A}[: \, , \, j]$, $j = 0, ..., M-1$, is a $N \times 1$ vector representing the $j$th column of $\mathbf{A}$.

After defining these partitions, we can define the product $\mathbf{y} = \mathbf{A} \mathbf{x}$ by using three different approaches:

**1) *doubly nested for***

    matrix_vector_real(A, x):
    
        N, M = shape(A)
        
        y = zeros(N)
        
        for i = 0:N-1
            for j = 0:M-1
                y[i] += A[i,j]*x[j]
        
        return y

**2) *dot product formulation***

    matrix_vector_real(A, x):
    
        N, M = shape(A)
        
        y = zeros(N)
        
        for i = 0:N-1
            y[i] = dot_real(A[i,:], x[:])
        
        return y

**3) *linear combination formulation***

    matrix_vector_real(A, x):
    
        N, M = shape(A)
        
        y = zeros(N)
        
        for j = 0:M-1
            y[:] += scalar_vec_real(x[j], A[:,j])
        
        return y

### Product of a complex matrix and a complex vector

Let $\mathbf{A}$ be an $N \times M$ complex matrix and $\mathbf{x}$ be an $M \times 1$ complex vector given by:

$$
\mathbf{A} = \mathbf{A}_{R} + imag \, \mathbf{A}_{I}
$$

and

$$
\mathbf{x} = \mathbf{x}_{R} + imag \, \mathbf{x}_{I} \: .
$$

It can be shown that the product $\mathbf{A} \mathbf{x}$ results in the following complex vector:

$$
\mathbf{y} = \mathbf{y}_{R} + imag \, \mathbf{y}_{I} \: ,
$$

where

$$
\mathbf{y}_{R} = \mathbf{A}_{R} \mathbf{x}_{R} - \mathbf{A}_{I} \mathbf{x}_{I}
$$

and

$$
\mathbf{y}_{I} = \mathbf{A}_{R} \mathbf{x}_{I} + \mathbf{A}_{I} \mathbf{x}_{R} \: .
$$

This product can be represented by the pseudo-code shown below:

    matrix_vector_complex(A, x):

        # compute the real and imaginary parts of the product
        y_R  = matrix_vector_real(Re(A), Re(x))
        y_R -= matrix_vector_real(Im(A), Im(x))
        y_I  = matrix_vector_real(Re(A), Im(x))
        y_I += matrix_vector_real(Im(A), Re(x))
        y = y_R + imag*y_I
        
        # return the result        
        return y

### Exercise 1

Create the functions below according to `template.py`: 
* `matvec_real_dumb`
* `matvec_real_numba`
* `matvec_real_dot` 
* `matvec_real_columns`
* `matvec_complex`
    
These functions must pass the following tests defined in `tests_template.py`:
* `test_matvec_real_input_doesnt_match`
* `test_matvec_real_functions_compare_numpy_dot`
* `test_matvec_complex_compare_numpy_dot`

##### Numpy example of the matrix-vector product

This example uses the routines [numpy.arange](http://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html) and [numpy.reshape](http://docs.scipy.org/doc/numpy/reference/generated/numpy.reshape.html).

In [1]:
import numpy as np

In [2]:
x = np.arange(5.)

In [3]:
x

array([ 0.,  1.,  2.,  3.,  4.])

In [4]:
A = np.reshape(np.arange(20.), (4,5))

In [5]:
A

array([[  0.,   1.,   2.,   3.,   4.],
       [  5.,   6.,   7.,   8.,   9.],
       [ 10.,  11.,  12.,  13.,  14.],
       [ 15.,  16.,  17.,  18.,  19.]])

In [6]:
np.dot(A, x)

array([  30.,   80.,  130.,  180.])

### Exercise 2

The previously presented algorithm for calculating a [simple moving average filter](https://github.com/birocoles/Disciplina-metodos-computacionais/tree/master/Content/first_steps_Python/SMA) can be formulated as the product of a matrix $\mathbf{A}$ and the original data $\mathbf{x}$, where $\mathbf{A}$ depends on the number of points forming the moving window and the number of data. For example, consider a data vector $\mathbf{x}$ given by

$$
\mathbf{x} = \left[ \begin{array}{c}
x_{0} \\
x_{1} \\
x_{2} \\
x_{3} \\
x_{4}
\end{array} \right]
$$

and a moving window formed by $3$ elements. In this case, the matrix $\mathbf{A}$ (see the hint presented below for creating this matrix automatically) is given by

$$
\mathbf{A} = \frac{1}{3} \, \left[ \begin{array}{ccccc}
0 & 0 & 0 & 0 & 0 \\
1 & 1 & 1 & 0 & 0 \\
0 & 1 & 1 & 1 & 0 \\
0 & 0 & 1 & 1 & 1 \\
0 & 0 & 0 & 0 & 0
\end{array} \right] \: .
$$

Then, the filtered data $\mathbf{x}_{f}$ can be calculated as follows:

$$\mathbf{x}_{f} = \mathbf{A} \, \mathbf{x} \: .$$

Show that the matrix formulation presented above is equivalent to that presented in `first_steps_Python\SMA\`. To do that:

1. Create a function called `mat_sma`, in your `my_functions.py` file, to calculate the moving average filter by using the matrix-vector product. This function must receive two arguments: the data vector and the number of points forming the moving window. This function must create the matrix $\mathbf{A}$ and use one of your three functions for calculating the matrix-vector product.

2. In your `test_my_functions.py` file, create a test to compare the results produced by this function and the results produced by that one presented in `first_steps_Python\SMA\`.

##### Hint: how to create $\mathbf{A}$ automatically?

In [7]:
N = 5 # number of data
ws = 3 # window size
i0 = ws//2
A = np.array(np.hstack(((1./ws)*np.ones(ws), np.zeros(N - ws + 1))))

In [8]:
A = np.resize(A, (N-2*i0, N))

In [9]:
A = np.vstack((np.zeros(N), A, np.zeros(N)))

In [10]:
A

array([[ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.33333333,  0.33333333,  0.33333333,  0.        ,  0.        ],
       [ 0.        ,  0.33333333,  0.33333333,  0.33333333,  0.        ],
       [ 0.        ,  0.        ,  0.33333333,  0.33333333,  0.33333333],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ]])

### Exercise 3

Let $\mathbf{y}$ be a $N \times 1$ vector whose $i$th element $y_{i} = f(x_{i})$, $i = 1, ..., N$, represents a function $f(x)$ evaluated at a point $x_{i}$. Let us also consider that the $N$ points $x_{i}$ are regularly spaced. In this case,

$$
x_{i} = x_{0} + i*h \: , \quad i = 0 \, , \, ..., \, N-1 \: ,
$$

where $x_{0}$ is the minimum $x_{i}$.

In this case, the derivative of the function $f(x)$ with respect to $x$ can be approximated by using a [central finite difference](https://en.wikipedia.org/wiki/Finite_difference) equation:

$$
\frac{d \, f(x_{i})}{d \, x} \approx \frac{f(x_{i} + h) - f(x_{i} - h)}{2 \, h} \: , \quad i = 1, ..., N-2 \: ,
$$

where $y_{i+1} = f(x_{i} + h)$ and $y_{i-1} = f(x_{i} - h)$. Notice that the derivative $\frac{d \, f(x_{i})}{d \, x}$ is not calculated at the points $x_{0}$ and $x_{N-1}$. The first derivatives $\frac{d \, f(x_{i})}{d \, x}$ can be calculated as a matrix-vector product $\mathbf{D} \, \mathbf{y}$, where

$$
\mathbf{D} = \frac{1}{2 \, h} \, \left[ \begin{array}{c}
0 & 0 & 0 & 0 & \cdots & 0 \\
-1 & 0 & 1 & 0 & \cdots & 0 \\
0 & -1 & 0 & 1 & & 0 \\
\vdots  & & &  &  & \vdots \\
0  &  & -1 & 0 & 1 & 0 \\
0  & \cdots & 0 & -1 & 0 & 1 \\
0 & \cdots & 0 & 0 & 0 & 0
\end{array} \right] \: .
$$

Based on this,

1. In your `my_functions.py` file, create a function called `deriv1d` that receives a $N \times 1$ data vector $\mathbf{y}$ and the interval $h$ and returns the first derivatives calculated according to the matrix-vector product presented above. The function must use one your functions for calculating the matrix-vector product. Hint: modify the algorithm for creating the matrix $\mathbf{A}$ presented in the previous exercise to create the matrix $\mathbf{D}$ automatically.

2. In your `test_my_function.py` file, create one test for your function `deriv1d`. In this test, create a vector `theta` with the function [`numpy.arange`](http://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html), by using the arguments `0.`, `2*np.pi`, `dtheta`, where `dtheta = 2.*numpy.pi/1000`. Create a data vector `y` by using the [`numpy.sin`](http://docs.scipy.org/doc/numpy/reference/generated/numpy.sin.html) function. Then, calculate a vector `z_true` by using the [`numpy.cos`](http://docs.scipy.org/doc/numpy/reference/generated/numpy.cos.html) function. Finally, calculate a `z_calc` vector with your function `deriv1d` and compare with the `z_true` vector by using the routine [`numpy.testing.assert_almost_equal`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.testing.assert_almost_equal.html). In the routine `numpy.testing.assert_almost_equal`, use `decimal = 3`. Remember that the first and last elements of `z_calc` will be equal to zero. Be careful!