# Product of a matrix and a vector

Let $\mathbf{A}$ be a $N \times M$ matrix and $\mathbf{x}$ be a $M \times 1$ vector. $\mathbf{A}$ can be represented by using a *row partition* or by a *colunm partition* as follows:

$$\begin{split}
    \mathbf{A} 
    & = \left[
    \begin{array}{ccc}
        a_{11} & \cdots & a_{1M} \\
        \vdots &        & \vdots \\
        a_{N1} & \cdots & a_{NM}
    \end{array}
    \right]_{N \times M} \\
    & = \left[
    \begin{array}{c}
        \mathbf{A}[1,:] \\
        \vdots \\
        \mathbf{A}[N,:]
    \end{array}
    \right]_{N \times M} \\
    & = \left[
    \begin{array}{ccc}
        \mathbf{A}[:,1] &
        \cdots &
        \mathbf{A}[:,M]
    \end{array}
    \right]_{N \times M}
\end{split} \: ,$$

where $\mathbf{A}[i,:]$, $i = 1, ..., N$, is a $1 \times M$ vector representing the $i$th row of $\mathbf{A}$ and $\mathbf{A}[:,j]$, $j = 1, ..., M$, is a $N \times 1$ vector representing the $j$th colunm of $\mathbf{A}$.

Once defined these partitions, we can define the product $\mathbf{y} = \mathbf{A} \mathbf{x}$ by using three different approaches:

**1) *doubly nested for***

    for i = 1:N
        for j = 1:M
            y[i] = y[i] + A[i,j]*x[j]

**2) *dot product formulation***

    for i = 1:N
        y[i] = dot(A[i,:], x[:])

**3) *linear combination formulation* **

    for j = 1:M
        y[:] = y[:] + A[:,j]*x[j]

### Exercise

Show that these three approaches are equivalent. To do this, follow the steps below:

1. In your `my_functions.py` file, create 3 functions. Each function must implement one of the 3 algorithms shown above. Follow the template presented in the [`dot.ipynb`](https://nbviewer.jupyter.org/github/birocoles/Disciplina-metodos-computacionais/blob/master/Content/dot.ipynb). All functions must return the resultant vector, given a matrix and a vector.
2. For each function created in the previous item, create 2 tests in your `test_my_functions.py`. One test must compare the result produced by your function and an expected result produced by a specific input. The other test must compare the result produced by your function and the result produced by the routine [`numpy.dot`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) (see the example shown below). Follow the template presented in the [`dot.ipynb`](https://nbviewer.jupyter.org/github/birocoles/Disciplina-metodos-computacionais/blob/master/Content/dot.ipynb).
3. *Extra*: use the `%timeit` to compare your functions and the function `numpy.dot`.

##### Numpy example of the matrix-vector product

This example uses the routines [numpy.arange](http://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html) and [numpy.reshape](http://docs.scipy.org/doc/numpy/reference/generated/numpy.reshape.html).

In [1]:
import numpy as np

In [2]:
x = np.arange(5.)

In [3]:
x

array([ 0.,  1.,  2.,  3.,  4.])

In [4]:
A = np.reshape(np.arange(20.), (4,5))

In [5]:
A

array([[  0.,   1.,   2.,   3.,   4.],
       [  5.,   6.,   7.,   8.,   9.],
       [ 10.,  11.,  12.,  13.,  14.],
       [ 15.,  16.,  17.,  18.,  19.]])

In [6]:
np.dot(A, x)

array([  30.,   80.,  130.,  180.])

### Exercise

The previously presented algorithm for calculating a [simple moving average filter](https://nbviewer.jupyter.org/github/birocoles/Disciplina-metodos-computacionais/tree/master/Content/first_steps_Python/SMA/) can be formulated as the product of a matrix $\mathbf{A}$ and the original data $\mathbf{x}$, where $\mathbf{A}$ depends on the number of points forming the moving window and the number of data. For example, consider a data vector $\mathbf{x}$ given by

$$
\mathbf{x} = \left[ \begin{array}{c}
x_{1} \\
x_{2} \\
x_{3} \\
x_{4} \\
x_{5}
\end{array} \right]
$$

and a moving window formed by $3$ elements. In this case, the matrix $\mathbf{A}$ (see the hint presented below for creating this matrix automatically) is given by

$$
\mathbf{A} = \frac{1}{3} \, \left[ \begin{array}{ccccc}
0 & 0 & 0 & 0 & 0 \\
1 & 1 & 1 & 0 & 0 \\
0 & 1 & 1 & 1 & 0 \\
0 & 0 & 1 & 1 & 1 \\
0 & 0 & 0 & 0 & 0
\end{array} \right] \: .
$$

Then, the filtered data $\mathbf{x}_{f}$ can be calculated as follows:

$$\mathbf{x}_{f} = \mathbf{A} \, \mathbf{x} \: .$$

Show that this formulation is equivalent to that presented previously. To do that,

1. Create a function that calculates the moving average filter by using the matrix-vector product and save it in your `my_functions.py` file. This function must receive two arguments: the data vector and the number of points forming the moving window. This function must create the matrix $\mathbf{A}$ and call one of the three functions created in the previous exercise for calculating the matrix-vector product.
2. In your `test_my_functions.py` file, create a test to compare the results produced by this function and the results produced by the previously presented simple moving average filter (`first_steps_Python\SMA\`).

##### Hint: how to create $\mathbf{A}$ automatically?

In [7]:
N = 5 # number of data
ws = 3 # window size
i0 = ws//2
A = np.array(np.hstack(((1./ws)*np.ones(ws), np.zeros(N - ws + 1))))

In [8]:
A = np.resize(A, (N-2*i0, N))

In [9]:
A = np.vstack((np.zeros(N), A, np.zeros(N)))

In [10]:
A

array([[ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.33333333,  0.33333333,  0.33333333,  0.        ,  0.        ],
       [ 0.        ,  0.33333333,  0.33333333,  0.33333333,  0.        ],
       [ 0.        ,  0.        ,  0.33333333,  0.33333333,  0.33333333],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ]])

### Exercise

Let $\mathbf{y}$ be a $N \times 1$ vector whose $i$th element $y_{i} = f(x_{i})$, $i = 1, ..., N$, represents a function $f(x)$ evaluated at a point $x_{i}$. Let us also consider that the $N$ points $x_{i}$ are regularly spaced, it means

$$
x_{i} = x_{1} + (i-1)*h \: , \quad i = 1, ..., N \: ,
$$

where $x_{1}$ is the minimum $x_{i}$.

In this case, the derivative of the function $f(x)$ with respect to $x$ can be approximated by using a [central finite difference](https://en.wikipedia.org/wiki/Finite_difference) equation:

$$
\frac{d \, f(x_{i})}{d \, x} \approx \frac{f(x_{i} + h) - f(x_{i} - h)}{2 \, h} \: , \quad i = 2, ..., N-1 \: ,
$$

where $y_{i+1} = f(x_{i} + h)$ and $y_{i-1} = f(x_{i} - h)$. Notice that the derivative $\frac{d \, f(x_{i})}{d \, x}$ is not calculated at the points $x_{1}$ and $x_{N-1}$. The first derivatives $\frac{d \, f(x_{i})}{d \, x}$ can be calculated as a matrix-vector product $\mathbf{D} \, \mathbf{y}$, where

$$
\mathbf{D} = \frac{1}{2 \, h} \, \left[ \begin{array}{c}
0 & 0 & 0 & 0 & \cdots & 0 \\
-1 & 0 & 1 & 0 & \cdots & 0 \\
0 & -1 & 0 & 1 & & 0 \\
\vdots  & & &  &  & \vdots \\
0  &  & -1 & 0 & 1 & 0 \\
0  & \cdots & 0 & -1 & 0 & 1 \\
0 & \cdots & 0 & 0 & 0 & 0
\end{array} \right] \: .
$$

Based on this introduction,

1. In your `my_functions.py` file, create a function that receives a $N \times 1$ data vector $\mathbf{y}$ and return the first derivatives calculated according to the matrix-vector product presented above. The function must call one your functions for calculating the matrix-vector product. Hint: modify the algorithm for creating the matrix $\mathbf{A}$ presented in the previous exercise to create the matrix $\mathbf{D}$ automatically.
2. In your `test_my_function.py` file, create a test for the function created in the previous item. In this test, create a vector `theta` with the function [`numpy.arange`](http://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html), by using the arguments `0.`, `2*np.pi`, `dtheta`, where `dtheta = 2.*np.pi/1000`. Create a data vector `y` by using the [`numpy.sin`](http://docs.scipy.org/doc/numpy/reference/generated/numpy.sin.html) function. Then, calculate a vector `z_true` by using the [`numpy.cos`](http://docs.scipy.org/doc/numpy/reference/generated/numpy.cos.html) function. Finally, calculate a `z_calc` vector with your function and compare with the `z_true` vector by using the routine [`numpy.testing.assert_almost_equal`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.testing.assert_almost_equal.html). In the routine `numpy.testing.assert_almost_equal`, use `decimal = 3`. Remember that the first and last elements of `z_calc` will be equal to zero. Be careful!