# Outer product

Let $\mathbf{x}$ and $\mathbf{y}$ be two vectors given by:

$$\mathbf{x} = \left[
\begin{array}{c}
x_{1} \\
x_{2} \\
\vdots \\
x_{N}
\end{array}
\right]_{\, N \times 1}$$

and

$$\mathbf{y} = \left[
\begin{array}{c}
y_{1} \\
y_{2} \\
\vdots \\
y_{M}
\end{array}
\right]_{\, M \times 1} \: .$$

The [outer](https://en.wikipedia.org/wiki/Outer_product) product is defined as follows:

$$
\begin{split}
\mathbf{M} &= \mathbf{x} \otimes \mathbf{y} \\
           &= \mathbf{x} \cdot \mathbf{y}^{\top} \\
           &= \begin{bmatrix}
                x_{1} \, \mathbf{y}^{\top} \\
                x_{2} \, \mathbf{y}^{\top} \\
                \vdots \\
                x_{N} \, \mathbf{y}^{\top}
              \end{bmatrix}_{\, N \times M} \\
           &= \begin{bmatrix}
                y_{1} \, \mathbf{x} & \dots & y_{N} \, \mathbf{x}
              \end{bmatrix}_{\, N \times M}
\end{split} \: .
$$

Notice that, in this case, the result is a $N \times M$ matrix, where $N$ is the number of elements of $\mathbf{x}$ and $M$ is the number of elements of $\mathbf{y}$.

The matrix $\mathbf{M}$ can be represented by

    for i = 1:N
        for j = 1:M
            M[i,j] = x[i]*y[j]

or, according to the *colon notation*, by a *row partition*

    for i = 1:N
        M[i,:] = x[i]*y[:]

or a *colounm partition*

    for j = 1:M
        M[:,j] = x[:]*y[j]

### Exercise

1. Create three functions called `outer1`, `outer2` and `outer3` to implement the three algoritms shown above. All functions must receive two numpy arrays and return the outer product. The numpy arrays may have different sizes. The functions must be written in your `my_functions.py` file, according to the template shown in the notebook `dot.ipynb`.
2. Create four automatic tests in your `test_my_functions.py` file, according to the template shown in the notebook `dot.ipynb`. One test must compare the result obtained by all your functions and the result obtained by the function [`numpy.outer`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.outer.html) (see the example below). The other three tests must set a specific input and compare the expected result and the result obtained by each of your functions.

#### The routine [`numpy.outer`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.outer.html)

The code below uses the routines [`numpy.arange`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html) and [`numpy.linspace`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.linspace.html).

In [1]:
import numpy as np

In [2]:
x = np.arange(5.)

In [3]:
x

array([ 0.,  1.,  2.,  3.,  4.])

In [4]:
y = np.linspace(0.6, 1.2, 3)

In [5]:
y

array([ 0.6,  0.9,  1.2])

Calculate the outer product

In [6]:
np.outer(x, y)

array([[ 0. ,  0. ,  0. ],
       [ 0.6,  0.9,  1.2],
       [ 1.2,  1.8,  2.4],
       [ 1.8,  2.7,  3.6],
       [ 2.4,  3.6,  4.8]])