# Outer product

Let $\mathbf{x}$ and $\mathbf{y}$ be two $N \times 1$ vectors given by:

$$\mathbf{x} = \left[
\begin{array}{c}
x_{1} \\
x_{2} \\
\vdots \\
x_{N}
\end{array}
\right]_{\, N \times 1}$$

and

$$\mathbf{y} = \left[
\begin{array}{c}
y_{1} \\
y_{2} \\
\vdots \\
y_{M}
\end{array}
\right]_{\, M \times 1} \: .$$

### Kronecker (or direct, or [outer](https://en.wikipedia.org/wiki/Outer_product)) product

$$\begin{split}
\mathbf{M} & = \mathbf{x} \otimes \mathbf{y}^{\top} \\
           & = \left[
                \begin{array}{c}
                x_{1} \, \mathbf{y}^{\top} \\
                x_{2} \, \mathbf{y}^{\top}\\
                \vdots \\
                x_{N} \, \mathbf{y}^{\top}
                \end{array}
                \right]_{N \times N} \\
           & = \left[
                \begin{array}{ccc}
                y_{1} \, \mathbf{x} & \dots & y_{N} \, \mathbf{x}
                \end{array}
                \right]_{N \times N}
\end{split} \: .$$

Notice that, in this case, the result is a square matrix with order $N$ equal to the number of elements of $\mathbf{x}$ and $\mathbf{y}$. However, this operation does not require that the vectors $\mathbf{x}$ and $\mathbf{y}$ have the same number of elements. Consider, for example, that $\mathbf{x}$ is a $N \times 1$ vector and that $\mathbf{y}$ is a $M \times 1$ vector, where $N \neq M$. In this case, the matrix $\mathbf{M}$ is $N \times M$, e.g., it has the number of rows equal to the number of elements of $\mathbf{x}$ and the number of colunms equal to the number of elements of $\mathbf{y}$.

The matrix $\mathbf{M}$ can be represented by

    for i = 1:N
        for j = 1:M
            M[i,j] = x[i]*y[j]

or, according to the *colon notation*, by a *row partition*

    for i = 1:N
        M[i,:] = x[i]*y[:]

or a *colounm partition*

    for j = 1:M
        M[:,j] = x[:]*y[j]

### Exercise 3

Show that these three approaches are equivalent. To do this, follow the steps below:

1. Create a function according to the first approach and save it in an external file
2. Create a function according to the second approach and save it in an external file
3. Create a function according to the third approach and save it in an external file
4. Use the `code-template.ipynb` for comparing the results produced by these three functions with the code presented below

#### Numpy example of the outer product

Import numpy

In [1]:
import numpy as np

Create a colunm vector using the functions [numpy.arange](http://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html) and [numpy.reshape](http://docs.scipy.org/doc/numpy/reference/generated/numpy.reshape.html)

In [2]:
x = np.arange(5.)
x = np.reshape(x, (x.size, 1))

In [3]:
x

array([[ 0.],
       [ 1.],
       [ 2.],
       [ 3.],
       [ 4.]])

Create a row vector by using the function [numpy.linspace](http://docs.scipy.org/doc/numpy/reference/generated/numpy.linspace.html)

In [4]:
yT = np.linspace(0.6, 1.2, 3)

In [5]:
yT

array([ 0.6,  0.9,  1.2])

Calculate the outer product

In [6]:
x*yT

array([[ 0. ,  0. ,  0. ],
       [ 0.6,  0.9,  1.2],
       [ 1.2,  1.8,  2.4],
       [ 1.8,  2.7,  3.6],
       [ 2.4,  3.6,  4.8]])

### Exercise 4

Let $\mathbf{a}^{\top}$ be an ${1 \times 5}$ vector and $\mathbf{b}^{\top}$ be an ${1 \times 3}$ vector as follows:

In [7]:
aT = np.arange(5.)
bT = np.linspace(11., 13., 3)

Let's also consider the two matrices $\mathbf{A}$ and $\mathbf{B}$, created from $\mathbf{a}^{\top}$ and $\mathbf{b}^{\top}$ by using the function [numpy.meshgrid](http://docs.scipy.org/doc/numpy/reference/generated/numpy.meshgrid.html):

In [8]:
A, B = np.meshgrid(aT,bT)

In [9]:
A

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 0.,  1.,  2.,  3.,  4.],
       [ 0.,  1.,  2.,  3.,  4.]])

In [10]:
B

array([[ 11.,  11.,  11.,  11.,  11.],
       [ 12.,  12.,  12.,  12.,  12.],
       [ 13.,  13.,  13.,  13.,  13.]])

Show that $\mathbf{A} = \mathbf{1}_{3 \times 1} \otimes \mathbf{a}^{\top}$ and $\mathbf{B} = \mathbf{b} \otimes \mathbf{1}_{1 \times 5}$. Use the `code-template.ipynb` and follow the steps below:

1. Create the inputs $\mathbf{a}^{\top}$, $\mathbf{b}$, $\mathbf{1}_{3 \times 1}$ and $\mathbf{1}_{1 \times 5}$

2. Calculate $\mathbf{A}$ and $\mathbf{B}$ by using one of your outer product functions

3. Calculate $\mathbf{A}$ and $\mathbf{B}$ by using the `numpy.meshgrid` function

4. Compare the results by using the function `numpy.allclose`

### References

* Golub, G. H. and Van Loan, C. F. Matrix computations, 4th edition, Johns Hopkins University Press, 2013

* Horn, R. A. and Johnson, C. R. Topics in matrix analysis, Cambridge University Press, 1994