# Permutation matrices

Let $\mathbf{I}_{N}$ be the $N \times N$ identity matrix:

$$
\mathbf{I}_{N} = \begin{bmatrix}
1 &  &  \\
  & \ddots & \\
  & & 1
\end{bmatrix}_{N \times N}
$$

We define *permutation matrices* by properly reordering the rows (or columns) of $\mathbf{I}_{N}$. Consider the example with $N = 4$. 

$$
\mathbf{I}_{N} = \begin{bmatrix}
1 & 0 & 0 & 0 \\
0 & 1 & 0 & 0 \\
0 & 0 & 1 & 0 \\
0 & 0 & 0 & 1
\end{bmatrix}
$$

By using this example, three important permutation matrices can be defined as follows:

#### Exchange permutation

$$
\mathcal{E}_{4} = \begin{bmatrix}
0 & 0 & 0 & 1 \\
0 & 0 & 1 & 0 \\
0 & 1 & 0 & 0 \\
1 & 0 & 0 & 0
\end{bmatrix}
$$

#### Downshift permutation

$$
\mathcal{D}_{4} = \begin{bmatrix}
0 & 0 & 0 & 1 \\
1 & 0 & 0 & 0 \\
0 & 1 & 0 & 0 \\
0 & 0 & 1 & 0
\end{bmatrix}
$$

#### Upshift permutation

$$
\mathcal{U}_{4} = \begin{bmatrix}
0 & 1 & 0 & 0 \\
0 & 0 & 1 & 0 \\
0 & 0 & 0 & 1 \\
1 & 0 & 0 & 0
\end{bmatrix}
$$

#### Examples

Let $\mathbf{x}$ be a $4 \times 1$ vector given by:

$$
\mathbf{x} = \begin{bmatrix}
x_{0} \\
x_{1} \\
x_{2} \\
x_{3}
\end{bmatrix}
$$

and $\mathbf{A}$ be a $4 \times 4$ matrix given by:

$$
\mathbf{A} = \begin{bmatrix}
a_{00} & a_{01} & a_{02} & a_{03} \\
a_{10} & a_{11} & a_{12} & a_{13} \\
a_{20} & a_{21} & a_{22} & a_{23} \\
a_{30} & a_{31} & a_{32} & a_{33}
\end{bmatrix} \: .
$$

In [1]:
import numpy as np

In [2]:
I = np.identity(4)
print(I)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [3]:
E = np.identity(4)[:,::-1]
print(E)

[[0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]]


In [4]:
D = np.roll(a=np.identity(4), shift=1, axis=0)
print(D)

[[0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [5]:
U = D.T
print(U)

[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]]


In [6]:
x = np.arange(4.)*10
print(x)

[ 0. 10. 20. 30.]


In [7]:
A = np.arange(16.).reshape((4,4))*10
print(A)

[[  0.  10.  20.  30.]
 [ 40.  50.  60.  70.]
 [ 80.  90. 100. 110.]
 [120. 130. 140. 150.]]


#### Permutation matrices are orthogonal

In [8]:
E.T@E

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [9]:
E@E.T

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [10]:
D.T@D

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [11]:
D@D.T

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [12]:
U.T@U

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [13]:
U@U.T

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

#### Product of a permutation matrix a vector

In [14]:
x

array([ 0., 10., 20., 30.])

In [15]:
E@x

array([30., 20., 10.,  0.])

In [27]:
x[::-1]

array([30., 20., 10.,  0.])

In [30]:
x[[3,2,1,0]]

array([30., 20., 10.,  0.])

In [31]:
D@x

array([30.,  0., 10., 20.])

In [32]:
x[[3,0,1,2]]

array([30.,  0., 10., 20.])

In [33]:
np.roll(a=x,shift=1)

array([30.,  0., 10., 20.])

In [34]:
U@x

array([10., 20., 30.,  0.])

In [ ]:
x[[1,2,3,0]]

In [35]:
np.roll(a=x,shift=-1)

array([10., 20., 30.,  0.])

#### Product of a permutation matrix and a matrix

In [36]:
A

array([[  0.,  10.,  20.,  30.],
       [ 40.,  50.,  60.,  70.],
       [ 80.,  90., 100., 110.],
       [120., 130., 140., 150.]])

In [37]:
E@A

array([[120., 130., 140., 150.],
       [ 80.,  90., 100., 110.],
       [ 40.,  50.,  60.,  70.],
       [  0.,  10.,  20.,  30.]])

In [38]:
A[::-1,:]

array([[120., 130., 140., 150.],
       [ 80.,  90., 100., 110.],
       [ 40.,  50.,  60.,  70.],
       [  0.,  10.,  20.,  30.]])

In [39]:
A[[3,2,1,0],:]

array([[120., 130., 140., 150.],
       [ 80.,  90., 100., 110.],
       [ 40.,  50.,  60.,  70.],
       [  0.,  10.,  20.,  30.]])

In [40]:
A@E

array([[ 30.,  20.,  10.,   0.],
       [ 70.,  60.,  50.,  40.],
       [110., 100.,  90.,  80.],
       [150., 140., 130., 120.]])

In [41]:
A[:,::-1]

array([[ 30.,  20.,  10.,   0.],
       [ 70.,  60.,  50.,  40.],
       [110., 100.,  90.,  80.],
       [150., 140., 130., 120.]])

In [42]:
A[:,[3,2,1,0]]

array([[ 30.,  20.,  10.,   0.],
       [ 70.,  60.,  50.,  40.],
       [110., 100.,  90.,  80.],
       [150., 140., 130., 120.]])

In [43]:
D@A

array([[120., 130., 140., 150.],
       [  0.,  10.,  20.,  30.],
       [ 40.,  50.,  60.,  70.],
       [ 80.,  90., 100., 110.]])

In [44]:
A[[3,0,1,2],:]

array([[120., 130., 140., 150.],
       [  0.,  10.,  20.,  30.],
       [ 40.,  50.,  60.,  70.],
       [ 80.,  90., 100., 110.]])

In [45]:
np.roll(a=A,shift=1,axis=0)

array([[120., 130., 140., 150.],
       [  0.,  10.,  20.,  30.],
       [ 40.,  50.,  60.,  70.],
       [ 80.,  90., 100., 110.]])

In [46]:
A@D

array([[ 10.,  20.,  30.,   0.],
       [ 50.,  60.,  70.,  40.],
       [ 90., 100., 110.,  80.],
       [130., 140., 150., 120.]])

In [47]:
A[:,[1,2,3,0]]

array([[ 10.,  20.,  30.,   0.],
       [ 50.,  60.,  70.,  40.],
       [ 90., 100., 110.,  80.],
       [130., 140., 150., 120.]])

In [48]:
np.roll(a=A,shift=-1,axis=1)

array([[ 10.,  20.,  30.,   0.],
       [ 50.,  60.,  70.,  40.],
       [ 90., 100., 110.,  80.],
       [130., 140., 150., 120.]])

In [49]:
U@A

array([[ 40.,  50.,  60.,  70.],
       [ 80.,  90., 100., 110.],
       [120., 130., 140., 150.],
       [  0.,  10.,  20.,  30.]])

In [50]:
A[[1,2,3,0],:]

array([[ 40.,  50.,  60.,  70.],
       [ 80.,  90., 100., 110.],
       [120., 130., 140., 150.],
       [  0.,  10.,  20.,  30.]])

In [51]:
np.roll(a=A,shift=-1,axis=0)

array([[ 40.,  50.,  60.,  70.],
       [ 80.,  90., 100., 110.],
       [120., 130., 140., 150.],
       [  0.,  10.,  20.,  30.]])

In [52]:
A@U

array([[ 30.,   0.,  10.,  20.],
       [ 70.,  40.,  50.,  60.],
       [110.,  80.,  90., 100.],
       [150., 120., 130., 140.]])

In [53]:
A[:,[3,0,1,2]]

array([[ 30.,   0.,  10.,  20.],
       [ 70.,  40.,  50.,  60.],
       [110.,  80.,  90., 100.],
       [150., 120., 130., 140.]])

In [54]:
np.roll(a=A,shift=1,axis=1)

array([[ 30.,   0.,  10.,  20.],
       [ 70.,  40.,  50.,  60.],
       [110.,  80.,  90., 100.],
       [150., 120., 130., 140.]])

Note that products of permutation matrices and vectors/matrices do not expend any flop. Instead, such products only rearrange terms in vectors/matrices.