# Polynomial fitting

In [1]:
#used for inserting images
from IPython.display import Image as img

import numpy as np

In [2]:
from numpy.polynomial.polynomial import polyvander, polyvander2d

#### Example of the routine [`numpy.polynomial.polynomial.polyvander`](https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.polynomial.polynomial.polyvander.html)

In [3]:
x = np.arange(1, 5)
degree = 3

In [6]:
print(x)

[1 2 3 4]


In [5]:
print(polyvander(x, degree))

[[ 1.  1.  1.  1.]
 [ 1.  2.  4.  8.]
 [ 1.  3.  9. 27.]
 [ 1.  4. 16. 64.]]


The matrix in the cell above is used in the 1D polynomial fitting.

#### Example of the routine [`numpy.polynomial.polynomial.polyvander2d`](https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.polynomial.polynomial.polyvander2d.html)

In [7]:
x, y = np.meshgrid(np.arange(1, 5), np.arange(2, 6))
x = np.ravel(x)
y = np.ravel(y)

In [8]:
print(x)
print(y)

[1 2 3 4 1 2 3 4 1 2 3 4 1 2 3 4]
[2 2 2 2 3 3 3 3 4 4 4 4 5 5 5 5]


In [9]:
degreex = 2 # maximum degree in x
degreey = 2 # maximum degree in y

In [10]:
print(polyvander2d(x, y, [degreex, degreey]))

[[  1.   2.   4.   1.   2.   4.   1.   2.   4.]
 [  1.   2.   4.   2.   4.   8.   4.   8.  16.]
 [  1.   2.   4.   3.   6.  12.   9.  18.  36.]
 [  1.   2.   4.   4.   8.  16.  16.  32.  64.]
 [  1.   3.   9.   1.   3.   9.   1.   3.   9.]
 [  1.   3.   9.   2.   6.  18.   4.  12.  36.]
 [  1.   3.   9.   3.   9.  27.   9.  27.  81.]
 [  1.   3.   9.   4.  12.  36.  16.  48. 144.]
 [  1.   4.  16.   1.   4.  16.   1.   4.  16.]
 [  1.   4.  16.   2.   8.  32.   4.  16.  64.]
 [  1.   4.  16.   3.  12.  48.   9.  36. 144.]
 [  1.   4.  16.   4.  16.  64.  16.  64. 256.]
 [  1.   5.  25.   1.   5.  25.   1.   5.  25.]
 [  1.   5.  25.   2.  10.  50.   4.  20. 100.]
 [  1.   5.  25.   3.  15.  75.   9.  45. 225.]
 [  1.   5.  25.   4.  20. 100.  16.  80. 400.]]


The matrix in the cell above is used in the 2D polynomial fitting.

### Exercise for 1D polynomials

In your `my_functions.py` file,

1. create a function called `pol1d_matrix` to calculate the matrix `A` associated with an 1D polynomial od degree `D`. The function must receive the data coordinates `x` and the degree `D` and return the matrix `A` used in the polynomial fitting. 

2. create a function `pol1d_coeffs` to estimate the coefficients of a 1D polynomial that fits a given dataset. The function must receive the data coordinates `x`, the degree `D` of the polynomial and the 1d-array containing the data `y`. The function must return a 1D-array `p` containing the coefficients of the polynomial. Use the function `pol1d_matrix` and your previous functions for calculating the matrix operations and solving the linear system.

3. create a function `pol1d_interpol` to interpolate data. The function must receive the interpolating points `x0` and the 1D-array of coefficients `p` calculated with the function `pol1d_coeffs` and return a 1D-array containing the interpolated points. Use the function `pol1d_matrix` and your previous functions for calculating the matrix operations.

In your `test_my_functions.py`, 

4. create a test to compare the result produced by `pol1d_matrix` and that produced by the routine [`numpy.polynomial.polynomial.polyvander`](https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.polynomial.polynomial.polyvander.html) (See the example above).

5. create a test for function `pol1d_coeffs`. This test must simulate data produced by a known polynomial and use these data to estimate the coefficients of the polynomial with your function `pol1d_coeffs`.

In a `Jupyter Notebook`,

6. Simulate data `d` produced by a given 1D polynomial at irregularly spaced points `x`. Simulate data `d_regular` produced by the same 1D polynomial at regularly spaced points `x_regular`. Use your function `pol1d_interpol` to estimate the coefficients of the polynomial by using the irregularly spaced data `d`. Use your function `pol1d_interpol` to interpolate data at the regularly spaced points `x_regular`. Plot the interpolated data obtained with your function `pol1d_interpol` and the true data set `d_regular`.

### Exercise for 2D polynomials

In your `my_functions.py` file,

1. create a function called `pol2d_matrix` to calculate the matrix `A` associated with an 1D polynomial od degree `D`. The function must receive the data coordinates `x` and `y`, the maximum degrees `Dx` and `Dy` and return the matrix `A` used in the polynomial fitting. 

2. create a function `pol2d_coeffs` to estimate the coefficients of a 2D polynomial that fits a given dataset. The function must receive the data coordinates `x` and `y`, the maximum degrees `Dx` and `Dy` of the variables x and y and the **1D-array** containing the data `y`. The function must return a 1D-array `p` containing the coefficients of the polynomial. Use the function `pol1d_matrix` and your previous functions for calculating the matrix operations and solving the linear system.

3. create a function `pol2d_interpol` to interpolate data. The function must receive the interpolating points `x0` and `y0` and the 1D-array of coefficients `p` calculated with the function `pol2d_coeffs` and return a **1D-array** containing the interpolated points. Use the function `pol2d_matrix` and your previous functions for calculating the matrix operations.

In your `test_my_functions.py`, 

4. create a test to compare the result produced by `pol2d_matrix` and that produced by the routine [`numpy.polynomial.polynomial.polyvander2d`](https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.polynomial.polynomial.polyvander2d.html) (See the example above).

5. create a test for function `pol2d_coeffs`. This test must simulate data produced by a known polynomial and use these data to estimate the coefficients of the polynomial with your function `pol2d_coeffs`.

In a `Jupyter Notebook`,

6. Simulate data `d` produced by a given 2D polynomial at irregularly spaced points `x` and `y`. Simulate data `d_regular` produced by the same 2D polynomial at regularly spaced points `x_regular` and `y_regular`. Use your function `pol2d_interpol` to estimate the coefficients of the polynomial by using the irregularly spaced data `d`. Use your function `pol2d_interpol` to interpolate data at the regularly spaced points `x_regular` and `y_regular`. Plot the interpolated data obtained with your function `pol2d_interpol` and the true data set `d_regular`.