# Polynomial fitting

As we could see in the notebooks `straight_line` and `parabola`, the problem of fitting a <a href="https://en.wikipedia.org/wiki/Polynomial" target="_blank">polynomial</a> to $N$ data $d_{i}$, $i = 0, \dots, N-1$, can be represented by a linear system:

<a id="eq1"></a>
$$
\mathbf{d}^{o} \approx \mathbf{d}(\mathbf{q}) = \mathbf{A} \mathbf{q} \quad , \tag{1}
$$

where $\mathbf{d}$ and $\mathbf{d}(\mathbf{q})$ are the observed and predicted $N \times 1$ data vectors, respectively, $\mathbf{q}$ is the $M \times 1$ parameter vector containing the coefficients of the polynomial and $\mathbf{A}$ is an $N \times M$ matrix depending on the coordinates of the observation points and the degree of the polynomial function.

By estimating a parameter vector $\tilde{\mathbf{q}}$ satisfying [equation 1](#eq1), we can compute the polynomial not only at the observation points, but also at other points where there are no data. To do this, we must:

1. Create a set of $L$ interpolation points;
2. Compute a new $L \times M$ matrix $\breve{\mathbf{A}}$ at the interpolation points;
4. Compute $L$ interpolated data $\breve{\mathbf{d}}(\tilde{\mathbf{q}})$ as follows:

<a id="eq2"></a>
$$
\breve{\mathbf{d}}(\tilde{\mathbf{q}}) = \breve{\mathbf{A}} \, \tilde{\mathbf{q}} \quad . \tag{2}
$$

Note that the key point here is computing the matrix $\mathbf{A}$. 

#### Example of the routine [`numpy.polynomial.polynomial.polyvander`](https://numpy.org/doc/stable/reference/generated/numpy.polynomial.polynomial.polyvander.html)

In [1]:
import numpy as np

In [2]:
from numpy.polynomial.polynomial import polyvander, polyvander2d

In [4]:
x = np.arange(1, 5)
degree = 3

In [5]:
print(x)

[1 2 3 4]


This example computes the matrix associated with the following polynomial:

$$
d_{i}(\mathbf{p}) = p_{0} \, x^{0}_{i} + p_{1} \, x^{1}_{i} + p_{2} \, x^{2}_{i} + p_{3} \, x^{3}_{i} \quad .
$$

In [6]:
print(polyvander(x, degree))

[[ 1.  1.  1.  1.]
 [ 1.  2.  4.  8.]
 [ 1.  3.  9. 27.]
 [ 1.  4. 16. 64.]]


The matrix in the cell above is used in the 1D polynomial fitting.

#### Example of the routine [`numpy.polynomial.polynomial.polyvander2d`](https://numpy.org/doc/stable/reference/generated/numpy.polynomial.polynomial.polyvander2d.html)

In [7]:
N = 10
x = np.ones(N)+1
y = np.arange(1, N+1)

In [8]:
print(x)
print(y)

[2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
[ 1  2  3  4  5  6  7  8  9 10]


In [9]:
degreex = 2 # maximum degree in x
degreey = 2 # maximum degree in y

This example computes the matrix associated with the following polynomial:

$$
\begin{split}
d_{i}(\mathbf{p}) = \: 
&p_{0} \left(  x^{0}_{i} \, y^{0}_{i} \right) + p_{1} \left(  x^{1}_{i} \, y^{0}_{i} \right) + p_{2} \left(  x^{2}_{i} \, y^{0}_{i} \right) + \\
&p_{3} \left(  x^{0}_{i} \, y^{1}_{i} \right) + p_{4} \left(  x^{1}_{i} \, y^{1}_{i} \right) + p_{5} \left(  x^{2}_{i} \, y^{1}_{i} \right) + \\
&p_{6} \left(  x^{0}_{i} \, y^{2}_{i} \right) + p_{7} \left(  x^{1}_{i} \, y^{2}_{i} \right) + p_{8} \left(  x^{2}_{i} \, y^{2}_{i} \right)
\end{split} \quad .
$$

In [10]:
print(polyvander2d(x, y, [degreex, degreey]))

[[  1.   1.   1.   2.   2.   2.   4.   4.   4.]
 [  1.   2.   4.   2.   4.   8.   4.   8.  16.]
 [  1.   3.   9.   2.   6.  18.   4.  12.  36.]
 [  1.   4.  16.   2.   8.  32.   4.  16.  64.]
 [  1.   5.  25.   2.  10.  50.   4.  20. 100.]
 [  1.   6.  36.   2.  12.  72.   4.  24. 144.]
 [  1.   7.  49.   2.  14.  98.   4.  28. 196.]
 [  1.   8.  64.   2.  16. 128.   4.  32. 256.]
 [  1.   9.  81.   2.  18. 162.   4.  36. 324.]
 [  1.  10. 100.   2.  20. 200.   4.  40. 400.]]


The matrix in the cell above is used in the 2D polynomial fitting.