# Product of a scalar and a vector

Let $a$ be a scalar and $\mathbf{x}$ be a $N \times 1$ vector. The product of $a$ and $\mathbf{x}$ is given by:

$$\begin{split}
\mathbf{y} & = a \, \mathbf{x}\\
           & = \left[
                \begin{array}{c}
                a \, x_{1} \\
                a \, x_{2} \\
                \vdots \\
                a \, x_{N}
                \end{array}
                \right]_{\, N \times 1}
\end{split}$$

This product can be represented as follows:

    for i = 1:N
        y[i] = a*x[i]

or, alternatively, by using the *colon notation*,

    y[:] = a*x[:]

### Import the required stuff

In [1]:
import numpy as np
import my_functions as mf

In [2]:
from numpy.testing import assert_almost_equal as aae

### Input

In [3]:
a = 4.0
x = np.array([1., 2., 3.])

### Result computed with my function

In [4]:
my_result = mf.dumb_scalar_vector(a,x)

In [5]:
print my_result

[  4.   8.  12.]


### Testing

In [6]:
# specific input
b = 3.
y = np.ones(4)

print y

[ 1.  1.  1.  1.]


In [7]:
# expected result
expected_result = np.zeros(4) + 3.

In [8]:
print expected_result

[ 3.  3.  3.  3.]


In [9]:
# my result
my_result = mf.dumb_scalar_vector(b, y)

In [10]:
# compare your result with the expected result
aae(my_result, expected_result, decimal=15)

In [11]:
# compare your result with an alternative Python implementation
aae(my_result, b*y[:], decimal=15)

In [12]:
# compare your result with an alternative Python implementation
aae(my_result, b*y, decimal=15)

Take a look at the file `test_my_functions.py`. At the same directory containing the file `my_functions.py`, run the command `python -m pytest test_my_functions.py`. You will get an output like the following:

<img src='pytest_output_example.png' width = 800>

### Timing the code

In [13]:
c = 23.
z = np.random.rand(1000)

In [14]:
%timeit -n 10000 mf.dumb_scalar_vector(c, z)

10000 loops, best of 3: 320 µs per loop


In [15]:
%timeit -n 10000 c*z[:]

10000 loops, best of 3: 2.16 µs per loop


In [16]:
%timeit -n 10000 c*z

10000 loops, best of 3: 1.91 µs per loop
