## Special linear systems

Consider the linear system

$$
\mathbf{A} \mathbf{x} = \mathbf{y} \: ,
$$

where $\mathbf{A}$ is a $N \times N$ matrix and $\mathbf{y}$ is a $N \times 1$ vector.

### Diagonal systems

In this case, $\mathbf{A}$ is a diagonal matrix and the solution $\mathbf{x}$ is given by:

    for i = 1:N
        x[i] = y[i]/A[i,i]

### Upper triangular systems

In this case, $\mathbf{A}$ is an upper triangular matrix and the solution $\mathbf{x}$ is given by:

    for i = N:1:-1
        x[i] = y[i]
        for j = i+1:N
            x[i] = x[i] - A[i,j]*x[j]
        x[i] = x[i]/A[i,i]

    for i = N:1:-1
        x[i] = y[i] - dot(A[i,i+1:],x[i+1:])
        x[i] = x[i]/A[i,i]

### Lower triangular systems

In this case, $\mathbf{A}$ is an lower triangular matrix and the solution $\mathbf{x}$ is given by:

    for i = 1:N
        x[i] = y[i]
        for j = 1:i-1
            x[i] = x[i] - A[i,j]*x[j]
        x[i] = x[i]/A[i,i]

    for i = 1:N
        x[i] = y[i] - dot(A[i,:i-1],x[:i-1])
        x[i] = x[i]/A[i,i]

### Exercise 12

Validate the algorithm for solving an upper triangular system according to the steps below:

1. Create a function that solves the linear system `Ax` for an upper triangular `A`. The function must receive the matrix `A` and the vector `x`.
3. Use the `code-template.ipynb` for testing this function against the Python code shown at the end of this notebook.

### Exercise 13

Validate the algorithm for solving a lower triangular system according to the steps below:

1. Create a function that solves the linear system `Ax` for a lower triangular `A`. The function must receive the matrix `A` and the vector `x`.
3. Use the `code-template.ipynb` for testing this function against the Python code shown at the end of this notebook.

In [1]:
import numpy as np

In [2]:
N = 5

B = np.reshape(np.arange(1., 26.), (N,N))

y = np.linspace(11, 15, N)

In [3]:
print B

[[  1.   2.   3.   4.   5.]
 [  6.   7.   8.   9.  10.]
 [ 11.  12.  13.  14.  15.]
 [ 16.  17.  18.  19.  20.]
 [ 21.  22.  23.  24.  25.]]


In [4]:
print y

[ 11.  12.  13.  14.  15.]


In [5]:
L = np.tril(B)

print L

[[  1.   0.   0.   0.   0.]
 [  6.   7.   0.   0.   0.]
 [ 11.  12.  13.   0.   0.]
 [ 16.  17.  18.  19.   0.]
 [ 21.  22.  23.  24.  25.]]


In [6]:
U = np.triu(B)

print U

[[  1.   2.   3.   4.   5.]
 [  0.   7.   8.   9.  10.]
 [  0.   0.  13.  14.  15.]
 [  0.   0.   0.  19.  20.]
 [  0.   0.   0.   0.  25.]]


In [7]:
np.linalg.solve(L,y)

array([ 11.        ,  -7.71428571,  -1.18681319,  -0.49971082,  -0.27983806])

In [8]:
np.linalg.solve(U,y)

array([ 5.99652979,  0.49971082,  0.19433198,  0.10526316,  0.6       ])