# Triangular matrices

Consider the $N \times N$ matrix $\mathbf{S}$ given by:

$$\mathbf{S} 
= \left[ \begin{array}{ccccc}
s_{11} & s_{12} & s_{13} & \cdots & s_{1N} \\
s_{12} & s_{22} & s_{23} & \cdots & s_{2N} \\
s_{13} & s_{23} & s_{33} & \cdots & s_{3N}  \\
\vdots & \vdots & \vdots & \ddots & \vdots  \\
s_{1N} & s_{2N} & s_{3N} & \cdots & s_{NN}
\end{array} \right] \: .
$$

This matrix is called **symmetric matrix**. Notice that, in this matrix, $s_{ij} = s_{ji}$.

Let $\mathbf{x}$ be a $N \times 1$ vector given by:

$$\mathbf{x} = 
\left[ \begin{array}{c}
x_{1} \\
\vdots \\
x_{N}
\end{array} \right] \: .
$$

It can be show that the product $\mathbf{y} = \mathbf{S} \mathbf{x}$ can be calculated as follows:

    y[:] = 0
    for i = 1:N
        for j = 1:N
            y[i] = y[i] + S[i,j]*x[j]

    y[:] = 0
    for i = 1:N
        for j = i:N
            y[i] = y[i] + S[i,j]*x[j]

    for i = 1:N
        for j = 1:i-1
            y[i] = y[i] + S[i,j]*x[j]

    y[:] = 0
    for i = 1:N
        y[i] = y[i] + dot(S[i,i:],x[i:])

    for j = 1:N
        y[j+1:] = y[j+1:] + S[j+1:,j]*x[j]

    y[:] = 0
    for i = 1:N
        y[i] = y[i] + dot(S[i,i:],x[i:])

    for j = 1:N
        y[j+1:] = y[j+1:] + S[j,j+1:]*x[j]

### Exercise 11

Validate this algorithm according to the steps below:

1. Create a function that calculates the product `Sx`. The function may receive the full symmetric matrix `S` or just its upper part (including the diagonal) and the vector `x`.
2. Use the `code-template.ipynb` for testing the two functions against the Python code shown below:

In [1]:
import numpy as np

Create a full symmetric matrix `S` and a vector `x` by using, for example, the functions [`numpy.random.rand`](http://docs.scipy.org/doc/numpy/reference/generated/numpy.random.rand.html#numpy.random.rand) and [`numpy.arange`](http://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html)

In [2]:
S = np.reshape(np.arange(1., 26.), (5,5))
S = np.dot(S.T, S)

x = np.arange(11.,16.)

In [3]:
print S

[[  855.   910.   965.  1020.  1075.]
 [  910.   970.  1030.  1090.  1150.]
 [  965.  1030.  1095.  1160.  1225.]
 [ 1020.  1090.  1160.  1230.  1300.]
 [ 1075.  1150.  1225.  1300.  1375.]]


In [4]:
print x

[ 11.  12.  13.  14.  15.]


Compare the results produced by your functions with the function [`numpy.dot`](http://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html)

In [5]:
print np.dot(S,x)

[ 63275.  67550.  71825.  76100.  80375.]
