# Triangular matrices - part 1

Consider two $N \times N$ matrices $\mathbf{U}$ and $\mathbf{L}$ given by:

$$\mathbf{U} 
= \left[ \begin{array}{ccccc}
u_{11} & u_{12} & u_{13} & \cdots & u_{1N} \\
       & u_{22} & u_{23} & \cdots & u_{2N} \\
       &        & u_{33} & \cdots & u_{3N}  \\
       &        &        & \ddots & \vdots  \\
       &        &        &        & u_{NN}
\end{array} \right]
$$

and

$$\mathbf{L} 
= \left[ \begin{array}{ccccc}
l_{11} & & & & \\
\vdots & \ddots & & & \\
l_{N-2 \, 1} & \cdots & l_{N-2\,N-2} & &\\
l_{N-1 \, 1} & \cdots & l_{N-1\,N-2} & l_{N-1\,N-1} &\\
l_{N1} & \cdots & l_{N\,N-2} & l_{N\,N-1} & l_{N\,N}
\end{array} \right] \: .
$$

The matrix $\mathbf{U}$ is called **upper triangular** and has all the elements below the main diagonal equal to zero. Similarly, the matrix $\mathbf{L}$ is called **lower triangular** and has all the elements above the main diagonal equal to zero.

Let $\mathbf{x}$ be a $N \times 1$ vector given by:

$$\mathbf{x} = 
\left[ \begin{array}{c}
x_{1} \\
\vdots \\
x_{N}
\end{array} \right] \: .
$$

By using the notebook [`matrix-vector.ipynb`](https://nbviewer.jupyter.org/github/birocoles/Disciplina-metodos-computacionais/blob/master/Content/matrix-vector.ipynb), it can be shown that the product $\mathbf{y} = \mathbf{U} \mathbf{x}$ can be calculated by following different algorithms:

**Algorithm 1**
    
    for i = 1:N
        for j = 1:N
            y[i] = y[i] + U[i,j]*x[j]

**Algorithm 2**
    
    for i = 1:N
        for j = i:N
            y[i] = y[i] + U[i,j]*x[j]

**Algorithm 3**

    for i = 1:N
        y[i] = dot(U[i,i:],x[i:])

**Algorithm 4**

    for j = 1:N
        for i = 1:j
            y[i] = y[i] + U[i,j]*x[j]

**Algorithm 5**

    for j = 1:N
        y[:j] = y[:j] + U[:j,j]*x[j]

Similarly, there are different algorithms to compute the product $\mathbf{z} = \mathbf{L} \mathbf{x}$:

**Algorithm 6**
    
    for i = 1:N
        for j = 1:N
            z[i] = z[i] + L[i,j]*x[j]

**Algorithm 7**
    
    for i = 1:N
        for j = 1:i
            z[i] = z[i] + L[i,j]*x[j]

**Algorithm 8**

    for i = 1:N
        z[i] = dot(L[i,:i],x[:i])

**Algorithm 9**

    for j = 1:N
        for i = j:N
            z[i] = z[i] + L[i,j]*x[j]

**Algorithm 10**

    for j = 1:N
        z[j:] = z[j:] + L[j:,j]*x[j]

Note that some of the algorithms presented above include the terms associated with null elements of the triangular matrices and other algorithms do not include these null elements.

### Exercise (extra)

What is the total number of flops associated with each algorithm presented above?

### Exercise

1. In your `my_functions.py` file, implement the algorithms 3, 5, 8, and 10. Each algorithm must be implemented in a single function. Each algorithm must receive the triangular matrix U or L and the vector x and return the resultant vector y or z, according to the notation presented above. The cells below show how to create the matrices U and L.
2. In your `test_my_functions.py` file, create four tests. The first test must compare the results produced by the algorithms 3 and 5; the second test must compare the results produced by the algorithms 8 and 10; the third test must compare the results produced by the algorithms 3 and 5 and the result produced by the routine [`numpy.dot`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html), and the fourth test must compare the results produced by the algorithms 8 and 10 and the result produced by the routine [`numpy.dot`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html).

#### How to create triangular matrices

The code below uses the routines [`numpy.random.rand`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.random.rand.html), [`numpy.triu`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.triu.html), and [`numpy.tril`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.tril.html).

In [1]:
import numpy as np

In [5]:
N = 5

In [8]:
A = 10*np.random.rand(N,N)

In [10]:
U = np.triu(A)

In [11]:
L = np.tril(A)

In [9]:
print A

[[ 2.39994494  5.1990145   6.64802477  8.26461278  9.97597219]
 [ 9.32020145  6.16766859  7.21614016  9.56120463  3.36986973]
 [ 4.80990239  7.81498467  5.32755188  2.66383862  4.80562381]
 [ 1.06540763  0.13238005  3.60187207  9.63759958  6.58738176]
 [ 8.64717915  7.79233115  6.66156655  5.49369209  1.39116862]]


In [12]:
print U

[[ 2.39994494  5.1990145   6.64802477  8.26461278  9.97597219]
 [ 0.          6.16766859  7.21614016  9.56120463  3.36986973]
 [ 0.          0.          5.32755188  2.66383862  4.80562381]
 [ 0.          0.          0.          9.63759958  6.58738176]
 [ 0.          0.          0.          0.          1.39116862]]


In [13]:
print L

[[ 2.39994494  0.          0.          0.          0.        ]
 [ 9.32020145  6.16766859  0.          0.          0.        ]
 [ 4.80990239  7.81498467  5.32755188  0.          0.        ]
 [ 1.06540763  0.13238005  3.60187207  9.63759958  0.        ]
 [ 8.64717915  7.79233115  6.66156655  5.49369209  1.39116862]]
