# Triangular matrices - part 1

Consider two $N \times N$ matrices $\mathbf{U}$ and $\mathbf{L}$ given by:

$$\mathbf{U} 
= \left[ \begin{array}{ccccc}
u_{00} & u_{01} & u_{02} & \cdots & u_{0(N-1)} \\
       & u_{11} & u_{12} & \cdots & u_{1(N-1)} \\
       &        & u_{22} & \cdots & u_{2(N-1)}  \\
       &        &        & \ddots & \vdots  \\
       &        &        &        & u_{(N-1)(N-1)}
\end{array} \right]
$$

and

$$
\mathbf{L} 
= \left[ \begin{array}{ccccc}
l_{00} & & & & \\
\vdots & \ddots & & & \\
l_{(N-3)0} & \cdots & l_{(N-3)(N-3)} & &\\
l_{(N-2)0} & \cdots & l_{(N-2)(N-3)} & l_{(N-2)(N-2)} &\\
l_{(N-1)0} & \cdots & l_{(N-1)(N-3)} & l_{(N-1)(N-2)} & l_{(N-1)(N-1)}
\end{array} \right] \: .
$$

The matrix $\mathbf{U}$ is called **upper triangular** and has all the elements below the main diagonal equal to zero. Similarly, the matrix $\mathbf{L}$ is called **lower triangular** and has all the elements above the main diagonal equal to zero.

Let $\mathbf{x}$ be a $N \times 1$ vector given by:

$$\mathbf{x} = 
\left[ \begin{array}{c}
x_{0} \\
\vdots \\
x_{(N-1)}
\end{array} \right] \: .
$$

By using the notebook `matrix-vector.ipynb`, it can be shown that the product $\mathbf{y} = \mathbf{U} \mathbf{x}$ can be calculated by following different algorithms:

**Algorithm 1**
    
    for i = 0:N-1
        for j = 0:N-1
            y[i] = y[i] + U[i,j]*x[j]

**Algorithm 2**
    
    for i = 0:N-1
        for j = i:N-1
            y[i] = y[i] + U[i,j]*x[j]

**Algorithm 3**

    for i = 0:N-1
        y[i] = dot(U[i,i:],x[i:])

**Algorithm 4**

    for j = 0:N-1
        for i = 0:j
            y[i] = y[i] + U[i,j]*x[j]

**Algorithm 5**

    for j = 0:N-1
        y[:j] = y[:j] + scalar_vec(x[j], U[:j,j])

Similarly, there are different algorithms to compute the product $\mathbf{z} = \mathbf{L} \mathbf{x}$:

**Algorithm 6**
    
    for i = 0:N-1
        for j = 0:N-1
            z[i] = z[i] + L[i,j]*x[j]

**Algorithm 7**
    
    for i = 0:N-1
        for j = 0:i
            z[i] = z[i] + L[i,j]*x[j]

**Algorithm 8**

    for i = 0:N-1
        z[i] = dot(L[i,:i],x[:i])

**Algorithm 9**

    for j = 0:N-1
        for i = j:N-1
            z[i] = z[i] + L[i,j]*x[j]

**Algorithm 10**

    for j = 0:N-1
        z[j:] = z[j:] + scalar_vec(x[j], L[j:,j])

Note that some of the algorithms presented above access the null elements of the triangular matrices and other algorithms do not access the null elements.

### Exercise

Implement the functions `matvec_triu_prod3`, `matvec_triu_prod5`, `matvec_tril_prod8` and `matvec_tril_prod10` defined by, respectively, the Algorithms 3, 5, 8 and 10 given above. The required functions must use the templates given below:

```python
def matvec_triu_prod3(U, x, check_input=True):
    '''
    Compute the product of an upper triangular matrix U 
    and a vector x. All elements are real numbers.
    
    Each element of the resultant vector is obtained by 
    computing a dot product.

    Parameters
    ----------
    U : numpy array 2d
        Upper triangular matrix.
    x : numpy array 1d
        Vector that postmultiply the triangular matrix U.
    check_input : boolean
        If True, verify if the input is valid. Default is True.

    Returns
    -------
    result : numpy array 1d
        Vector obtained from the product U x.
    '''

    # create your code here
    
    return result
```

```python
def matvec_triu_prod5(U, x, check_input=True):
    '''
    Compute the product of an upper triangular matrix U 
    and a vector x. All elements are real numbers.
    
    The elements of the resultant vector are obtained by 
    computing successive scalar vector products.

    Parameters
    ----------
    U : numpy array 2d
        Upper triangular matrix.
    x : numpy array 1d
        Vector that postmultiply the triangular matrix U.
    check_input : boolean
        If True, verify if the input is valid. Default is True.

    Returns
    -------
    result : numpy array 1d
        Vector obtained from the product U x.
    '''

    # create your code here
    
    return result
```

```python
def matvec_triu_prod8(L, x, check_input=True):
    '''
    Compute the product of an lower triangular matrix L 
    and a vector x. All elements are real numbers.
    
    Each element of the resultant vector is obtained by 
    computing a dot product.

    Parameters
    ----------
    L : numpy array 2d
        Lower triangular matrix.
    x : numpy array 1d
        Vector that postmultiply the triangular matrix U.
    check_input : boolean
        If True, verify if the input is valid. Default is True.

    Returns
    -------
    result : numpy array 1d
        Vector obtained from the product U x.
    '''

    # create your code here
    
    return result
```

```python
def matvec_triu_prod10(U, x, check_input=True):
    '''
    Compute the product of an lower triangular matrix L 
    and a vector x. All elements are real numbers.
    
    The elements of the resultant vector are obtained by 
    computing successive scalar vector products.

    Parameters
    ----------
    L : numpy array 2d
        Lower triangular matrix.
    x : numpy array 1d
        Vector that postmultiply the triangular matrix U.
    check_input : boolean
        If True, verify if the input is valid. Default is True.

    Returns
    -------
    result : numpy array 1d
        Vector obtained from the product U x.
    '''

    # create your code here
    
    return result
```

The functions **must**: 
* verify if the given triangular matrix is square;
* verify if `x` is a numpy array with ndim = 1;
* assert that the number of rows/columns of the triangular matrix is equal to the number of elements forming `x`;
* ignore possible imaginary of the input parameters;
* use your `scalar_vec_real` and `dot_real` functions;

Additionally, **create at least two tests**. The first test must compare the results produced by the functions `matvec_triu_prod3` and `matvec_triu_prod5` with the result produced by the routine [`numpy.dot`](https://numpy.org/doc/stable/reference/generated/numpy.dot.html). The second test must compare the results produced by the functions `matvec_tril_prod8` and `matvec_tril_prod10` with the result produced by the routine [`numpy.dot`](https://numpy.org/doc/stable/reference/generated/numpy.dot.html).

#### How to create triangular matrices from full matrices?

The code below uses the routines [`Random generator`](https://numpy.org/doc/stable/reference/random/generator.html), [`numpy.triu`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.triu.html), and [`numpy.tril`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.tril.html).

In [1]:
import numpy as np

In [2]:
N = 5

In [3]:
rng = np.random.default_rng(12345)
A = 10*rng.random(N,N)

In [4]:
U = np.triu(A)

In [5]:
L = np.tril(A)

In [7]:
A

array([[7.01718117, 5.68432108, 6.63469429, 7.46441974, 2.89290608],
       [8.46778867, 1.95805811, 3.70039965, 3.55683556, 0.35377703],
       [9.3899707 , 3.44357192, 8.25396946, 1.2056961 , 7.06074992],
       [8.96343784, 3.20113979, 7.31977538, 2.9235426 , 8.81175334],
       [5.12841362, 8.94764649, 8.42383142, 4.505968  , 3.56083785]])

In [8]:
U

array([[7.01718117, 5.68432108, 6.63469429, 7.46441974, 2.89290608],
       [0.        , 1.95805811, 3.70039965, 3.55683556, 0.35377703],
       [0.        , 0.        , 8.25396946, 1.2056961 , 7.06074992],
       [0.        , 0.        , 0.        , 2.9235426 , 8.81175334],
       [0.        , 0.        , 0.        , 0.        , 3.56083785]])

In [9]:
L

array([[7.01718117, 0.        , 0.        , 0.        , 0.        ],
       [8.46778867, 1.95805811, 0.        , 0.        , 0.        ],
       [9.3899707 , 3.44357192, 8.25396946, 0.        , 0.        ],
       [8.96343784, 3.20113979, 7.31977538, 2.9235426 , 0.        ],
       [5.12841362, 8.94764649, 8.42383142, 4.505968  , 3.56083785]])