## Triangular systems

Consider the linear system

$$
\mathbf{A} \mathbf{x} = \mathbf{y} \: ,
$$

where $\mathbf{A}$ is a $N \times N$ matrix and $\mathbf{y}$ is an $N \times 1$ vector. We consider that $\mathbf{A}$, $\mathbf{y}$ and $\mathbf{x}$ are formed by real elements.

### Upper triangular systems

Let us consider that $\mathbf{A}$ is an $N \times N$ upper triangular matrix of order 4 ($N = 4$), so that the linear system is given by:

$$
\mathbf{A} = 
\begin{bmatrix}
a_{00} & a_{01} & a_{02} & a_{03} \\
0 & a_{11} & a_{12} & a_{13} \\
0 & 0 & a_{22} & a_{23} \\
0 & 0 & 0 & a_{33}
\end{bmatrix} \quad , \quad
\mathbf{y} = \begin{bmatrix} y_{0} \\ y_{1} \\ y_{2} \\ y_{3} \end{bmatrix} \quad , \quad
\mathbf{x} = \begin{bmatrix} x_{0} \\ x_{1} \\ x_{2} \\ x_{3} \end{bmatrix}
$$

$$
\begin{bmatrix}
a_{00} & a_{01} & a_{02} & a_{03} \\
0 & a_{11} & a_{12} & a_{13} \\
0 & 0 & a_{22} & a_{23} \\
0 & 0 & 0 & a_{33}
\end{bmatrix} \, \begin{bmatrix} x_{0} \\ x_{1} \\ x_{2} \\ x_{3} \end{bmatrix} = \begin{bmatrix} y_{0} \\ y_{1} \\ y_{2} \\ y_{3} \end{bmatrix}
$$

In this case, the solution $\mathbf{x}$ can be obtained as follows:

$$
\begin{split}
x_{3} &= \frac{y_{3}}{a_{33}} \\
x_{2} &= \frac{y_{2} - a_{23} x_{3}}{a_{22}} \\
x_{1} &= \frac{y_{1} - a_{12} x_{2} - a_{13} x_{3}}{a_{11}} \\
x_{0} &= \frac{y_{0} - a_{01} x_{1} - a_{02} x_{2} - a_{03} x_{3}}{a_{00}}
\end{split}
$$

This algorithm can be represented by the following pseudocode:

    for i = N-1:0:-1
        x[i] = y[i]
        for j = i+1:N-1
            x[i] = x[i] - A[i,j]*x[j]
        x[i] = x[i]/A[i,i]

or, by using the colon notation,

    for i = N-1:0:-1
        x[i] = y[i] - dot(A[i,i+1:],x[i+1:])
        x[i] = x[i]/A[i,i]

This algorithm is called **back substitution**.

### Lower triangular systems

Let us now consider that $\mathbf{A}$ is an $N \times N$ lower triangular matrix of order 4 ($N = 4$), so that the linear system is given by:

$$
\mathbf{A} = 
\begin{bmatrix}
a_{00} & 0 & 0 & 0 \\
a_{10} & a_{11} & 0 & 0 \\
a_{20} & a_{21} & a_{22} & 0 \\
a_{30} & a_{31} & a_{32} & a_{33}
\end{bmatrix} \quad , \quad
\mathbf{y} = \begin{bmatrix} y_{0} \\ y_{1} \\ y_{2} \\ y_{3} \end{bmatrix} \quad , \quad
\mathbf{x} = \begin{bmatrix} x_{0} \\ x_{1} \\ x_{2} \\ x_{3} \end{bmatrix}
$$

$$
\begin{bmatrix}
a_{00} & 0 & 0 & 0 \\
a_{10} & a_{11} & 0 & 0 \\
a_{20} & a_{21} & a_{22} & 0 \\
a_{30} & a_{31} & a_{32} & a_{33}
\end{bmatrix} \, \begin{bmatrix} x_{0} \\ x_{1} \\ x_{2} \\ x_{3} \end{bmatrix} = \begin{bmatrix} y_{0} \\ y_{1} \\ y_{2} \\ y_{3} \end{bmatrix}
$$

In this case, the solution $\mathbf{x}$ can be obtained as follows:

$$
\begin{split}
x_{0} &= \frac{y_{0}}{a_{00}} \\
x_{1} &= \frac{y_{1} - a_{10} x_{0}}{a_{11}} \\
x_{2} &= \frac{y_{2} - a_{20} x_{0} - a_{21} x_{1}}{a_{22}} \\
x_{3} &= \frac{y_{3} - a_{30} x_{0} - a_{31} x_{1} - a_{32} x_{2}}{a_{33}}
\end{split}
$$

This algorithm can be represented by the following pseudocode:

    for i = 0:N-1
        x[i] = y[i]
        for j = 0:i-1
            x[i] = x[i] - A[i,j]*x[j]
        x[i] = x[i]/A[i,i]

or, by using the colon notation,

    for i = 0:N-1
        x[i] = y[i] - dot(A[i,:i-1],x[:i-1])
        x[i] = x[i]/A[i,i]

This algorithm is called **forward substitution**.

### Exercise 1

Create a function `triu_system` to implement the back substitution according to the template given below:

```python
def triu_system(A, x, check_input=True):
    '''
    Solve the linear system Ax = y for x by using back substitution.

    The elements of x are computed by using a 'dot' within a single for.

    Parameters
    ----------
    A : numpy array 2d
        Upper triangular matrix.
    y : numpy array 1d
        Independent vector of the linear system.
    check_input : boolean
        If True, verify if the input is valid. Default is True.

    Returns
    -------
    result : numpy array 1d
        Solution x of the linear system.
    '''

    # create your code here
    
    return result
```

The function `triu_system` **must**: 
* verify if the given triangular matrix is square;
* verify if `y` is a numpy array with ndim = 1;
* assert that the number of rows/columns of the triangular matrix is equal to the number of elements forming `y`;
* ignore possible imaginary of the input parameters;
* use your `dot_real` function.

Additionally, **create at least two tests**:
* create an UPPER triangular matrix `A0` and a vector `x0` and use them to compute a vector `A0x0 = y0`. Then, use `A0` and `y0` to compute a vector `x` with the function `triu_system`. Finally, compare the computed vector `x` and the expected vector `x0`;
* compare the result produced by your `triu_system` and the result produced by the [`numpy.linalg.solve`](https://numpy.org/doc/stable/reference/generated/numpy.linalg.solve.html) (see the example presented below).

### Exercise 2

Create a function `tril_system` to implement the forward substitution according to the template given below:

```python
def tril_system(A, x, check_input=True):
    '''
    Solve the linear system Ax = y for x by using forward substitution.

    The elements of x are computed by using a 'dot' within a single for.

    Parameters
    ----------
    A : numpy array 2d
        Lower triangular matrix.
    y : numpy array 1d
        Independent vector of the linear system.
    check_input : boolean
        If True, verify if the input is valid. Default is True.

    Returns
    -------
    result : numpy array 1d
        Solution x of the linear system.
    '''

    # create your code here
    
    return result
```

The function `tril_system` **must**: 
* verify if the given triangular matrix is square;
* verify if `y` is a numpy array with ndim = 1;
* assert that the number of rows/columns of the triangular matrix is equal to the number of elements forming `y`;
* ignore possible imaginary of the input parameters;
* use your `dot_real` function.

Additionally, **create at least two tests**:
* create an LOWER triangular matrix `A0` and a vector `x0` and use them to compute a vector `A0x0 = y0`. Then, use `A0` and `y0` to compute a vector `x` with the function `tril_system`. Finally, compare the computed vector `x` and the expected vector `x0`;
* compare the result produced by your `tril_system` and the result produced by the [`numpy.linalg.solve`](https://numpy.org/doc/stable/reference/generated/numpy.linalg.solve.html) (see the example presented below).

### Routine [`numpy.linalg.solve`](https://numpy.org/doc/stable/reference/generated/numpy.linalg.solve.html)

In [1]:
import numpy as np

In [2]:
N = 5

In [10]:
rng = np.random.default_rng(12765)

In [11]:
A = 10*np.around(rng.random((N,N)), decimals=3) + 0.1*np.identity(N)
print(A)

[[5.44 4.26 8.6  2.69 7.95]
 [2.61 4.4  3.41 4.89 1.53]
 [8.09 4.79 4.94 3.19 3.45]
 [2.39 7.23 8.47 6.66 5.35]
 [5.95 7.15 3.61 3.53 5.59]]


In [12]:
L = np.tril(A)
print(L)

[[5.44 0.   0.   0.   0.  ]
 [2.61 4.4  0.   0.   0.  ]
 [8.09 4.79 4.94 0.   0.  ]
 [2.39 7.23 8.47 6.66 0.  ]
 [5.95 7.15 3.61 3.53 5.59]]


In [13]:
U = np.triu(A)
print(U)

[[5.44 4.26 8.6  2.69 7.95]
 [0.   4.4  3.41 4.89 1.53]
 [0.   0.   4.94 3.19 3.45]
 [0.   0.   0.   6.66 5.35]
 [0.   0.   0.   0.   5.59]]


In [14]:
x_true = np.around(rng.random(N), decimals=3)
print(x_true)

[0.287 0.93  0.196 0.116 0.635]


In [15]:
yu = np.dot(U, x_true)

In [16]:
xu = np.linalg.solve(U, yu)

In [17]:
np.allclose(x_true, xu)

True

In [18]:
yl = np.dot(L, x_true)

In [19]:
xl = xu = np.linalg.solve(L, yl)

In [20]:
np.allclose(x_true, xl)

True