# Triangular matrices

Consider two $N \times N$ matrices $\mathbf{U}$ and $\mathbf{U}$ given by:

$$\mathbf{U} 
= \left[ \begin{array}{ccccc}
u_{11} & u_{12} & u_{13} & \cdots & u_{1N} \\
       & u_{22} & u_{23} & \cdots & u_{2N} \\
       &        & u_{33} & \cdots & u_{3N}  \\
       &        &        & \ddots & \vdots  \\
       &        &        &        & u_{NN}
\end{array} \right]
$$

and

$$\mathbf{L} 
= \left[ \begin{array}{ccccc}
l_{11} & & & & \\
\vdots & \ddots & & & \\
l_{N-2 \, 1} & \cdots & l_{N-2\,N-2} & &\\
l_{N-1 \, 1} & \cdots & l_{N-1\,N-2} & l_{N-1\,N-1} &\\
l_{N1} & \cdots & l_{N\,N-2} & l_{N\,N-1} & l_{N\,N}
\end{array} \right]
$$

These matrices are called **upper triangular** and **lower triangular**, respectively.

Let $\mathbf{x}$ be a $N \times 1$ vector given by:

$$\mathbf{x} = 
\left[ \begin{array}{c}
x_{1} \\
\vdots \\
x_{N}
\end{array} \right] \: .
$$

It can be show that the product $\mathbf{y} = \mathbf{U} \mathbf{x}$ can be calculated as follows:

    y[:] = 0
    for i = 1:N
        for j = i:M
            y[i] = y[i] + U[i,j]*x[j]

    for i = 1:N
        y[i] = dot(U[i,i:],x[i:])

Similarly, the product $\mathbf{z} = \mathbf{L} \mathbf{x}$ can be calculated as follows:

    z[:] = 0
    for i = 1:N
        for j = 1:i
            z[i] = z[i] + L[i,j]*x[j]

    for i = 1:N
        z[i] = dot(L[i,:i],x[:i])

### Exercise 10

Validate these two algorithms according to the steps below:

1. Create a function that calculates the product `Ux`. The function must receive the upper matrix `U` and the vector `x`.
2. Create a function that calculates the product `Lx`. The function must receive the upper matrix `L` and the vector `x`.
3. Use the `code-template.ipynb` for testing the two functions against the Python code shown below:

In [1]:
import numpy as np

Create a full matrix by using, for example, the function [`numpy.random.rand`](http://docs.scipy.org/doc/numpy/reference/generated/numpy.random.rand.html#numpy.random.rand)

In [54]:
B = np.reshape(np.arange(1., 26.), (5,5))

x = np.arange(11,16)

In [55]:
print B

[[  1.   2.   3.   4.   5.]
 [  6.   7.   8.   9.  10.]
 [ 11.  12.  13.  14.  15.]
 [ 16.  17.  18.  19.  20.]
 [ 21.  22.  23.  24.  25.]]


In [56]:
U = np.triu(B)

In [57]:
print U

[[  1.   2.   3.   4.   5.]
 [  0.   7.   8.   9.  10.]
 [  0.   0.  13.  14.  15.]
 [  0.   0.   0.  19.  20.]
 [  0.   0.   0.   0.  25.]]


In [58]:
x

array([11, 12, 13, 14, 15])

In [59]:
np.dot(L,x)

array([   11.,   150.,   434.,   880.,  1505.])

In [62]:
z = np.empty_like(y)
for i in range(5):
    z[i] = np.dot(L[i,:i+1],x[:i+1])

In [63]:
z

array([   11.,   150.,   434.,   880.,  1505.])