## Triangular systems

Consider the linear system

$$
\mathbf{A} \mathbf{x} = \mathbf{y} \: ,
$$

where $\mathbf{A}$ is a $N \times N$ matrix and $\mathbf{y}$ is a $N \times 1$ vector.

### Upper triangular systems

In this case, $\mathbf{A}$ is an upper triangular matrix and the solution $\mathbf{x}$ is given by:

    for i = N:1:-1
        x[i] = y[i]
        for j = i+1:N
            x[i] = x[i] - A[i,j]*x[j]
        x[i] = x[i]/A[i,i]

    for i = N:1:-1
        x[i] = y[i] - dot(A[i,i+1:],x[i+1:])
        x[i] = x[i]/A[i,i]

### Lower triangular systems

In this case, $\mathbf{A}$ is a lower triangular matrix and the solution $\mathbf{x}$ is given by:

    for i = 1:N
        x[i] = y[i]
        for j = 1:i
            x[i] = x[i] - A[i,j]*x[j]
        x[i] = x[i]/A[i,i]

    for i = 1:N
        x[i] = y[i] - dot(A[i,:i],x[:i])
        x[i] = x[i]/A[i,i]

### Exercise

1) In your `my_functions.py` file, create a function called `triu_system` that solves the linear system `Ax = y`, where `A` is an UPPER triangular matrix. The function must receive the matrix `A` and the vector `y` and return the computed vector `x`.

2) In your `test_my_functions.py` file, create two tests. In the first test, create an UPPER triangular matrix `A0` and a vector `x0` and use them to compute a vector `A0x0 = y0`. Then, use `A0` and `y0` to compute a vector `x` with the function `triu_system`. Finally, compare the computed vector `x` and the expected vector `x0`. In the second test, compare the result produced by `triu_system` and the result produced by the [`numpy.linalg.solve`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.solve.html) (see the example presented below), given the same input.

### Exercise

3) In your `my_functions.py` file, create a function called `tril_system` that solves the linear system `Ax = y`, where `A` is an LOWER triangular matrix. The function must receive the matrix `A` and the vector `y` and return the computed vector `x`.

4) In your `test_my_functions.py` file, create two tests. In the first test, create a LOWER triangular matrix `A0` and a vector `x0` and use them to compute a vector `A0x0 = y0`. Then, use `A0` and `y0` to compute a vector `x` with the function `tril_system`. Finally, compare the computed vector `x` and the expected vector `x0`. In the second test, compare the result produced by `tril_system` and the result produced by the [`numpy.linalg.solve`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.solve.html) (see the example presented below), given the same input.

In [1]:
import numpy as np

In [2]:
N = 5

In [3]:
A = 10*np.around(np.random.rand(N,N), decimals=3)
print A

[[ 3.24  5.16  1.06  0.57  1.35]
 [ 0.01  5.87  0.11  4.96  0.56]
 [ 9.75  7.57  0.58  0.95  4.34]
 [ 0.15  3.27  6.49  1.05  4.11]
 [ 9.03  2.29  2.46  6.55  6.69]]


In [4]:
y = np.around(np.random.rand(N), decimals=3)
print y

[ 0.81   0.5    0.677  0.827  0.161]


In [5]:
L = np.tril(A)
print L

[[ 3.24  0.    0.    0.    0.  ]
 [ 0.01  5.87  0.    0.    0.  ]
 [ 9.75  7.57  0.58  0.    0.  ]
 [ 0.15  3.27  6.49  1.05  0.  ]
 [ 9.03  2.29  2.46  6.55  6.69]]


In [6]:
U = np.triu(A)
print U

[[ 3.24  5.16  1.06  0.57  1.35]
 [ 0.    5.87  0.11  4.96  0.56]
 [ 0.    0.    0.58  0.95  4.34]
 [ 0.    0.    0.    1.05  4.11]
 [ 0.    0.    0.    0.    6.69]]


In [7]:
print np.linalg.solve(L,y)

[  0.25         0.08475298  -4.14151736  26.08648134 -24.3600754 ]


In [8]:
print np.linalg.solve(U,y)

[ 0.96330096 -0.50025329 -0.14860906  0.69341875  0.02406577]


### Exercise

Consider the vertical seismic profiling problem where we wish to estimate vertical seismic slowness using travel time measurements of downward-propagating seismic waves, according to the Figure shown below. The orange star represent the source and the green triangles represent the receivers. The subsurface is discretized at $N$ depths $z_{i}$, $i =1, \dots, N$, that are equally spaced at intervals of $\Delta z$. The shallowest depth $z_{1}$ is equal to $\Delta z_{0}$. At each depth $z_{i}$, there is an observed time $t_{i}$ (data). Let us also consider that each depth $z_{i}$ coincides with the limit between two layers having a constant slowness $s_{i}$.

<img src='vsp_sketch.png' width=600>

Notice that, according to the Figure presented above, the linear system to be solved is given by:

$$
\underbrace{\begin{bmatrix}
\Delta z_{0} & & & & & & \\
\Delta z_{0} & \Delta z & & & & & \\
\Delta z_{0} & \Delta z & \Delta z & & & & \\
\Delta z_{0} & \Delta z & \Delta z & \Delta z & & & \\
\Delta z_{0} & \Delta z & \Delta z & \Delta z & \Delta z & & \\
\Delta z_{0} & \Delta z & \Delta z & \Delta z & \Delta z & \Delta z & \\
\Delta z_{0} & \Delta z & \Delta z & \Delta z & \Delta z & \Delta z & \Delta z \\
\end{bmatrix}}_{\mathbf{M}}
\underbrace{\begin{bmatrix}
s_{1} \\ s_{2} \\ s_{3} \\ s_{4} \\ s_{5} \\ s_{6} \\ s_{7}
\end{bmatrix}}_{\mathbf{s}} = 
\underbrace{\begin{bmatrix}
t_{1} \\ t_{2} \\ t_{3} \\ t_{4} \\ t_{5} \\ t_{6} \\ t_{7}
\end{bmatrix}}_{\mathbf{t}}
$$

### Exercise

1. In your `my_functions.py` file, create a function called `vsp` for solving the linear system $\mathbf{M} \mathbf{s} = \mathbf{t}$. The function must receive $\Delta z_{0}$, $\Delta z$, and $\mathbf{t}$ and return the slowness vector $\mathbf{s}$. The function cannot create the matrix $\mathbf{M}$, but use only the variables $\Delta z_{0}$ and $\Delta z$. To do it, modify one of the algorithms presented above for solving triangular systems.
2. In your `test_my_functions.py` file, create one test. In this test, specify values for $\Delta z_{0}$ and $\Delta z$ and create a slowness vector $\mathbf{s}_{0}$. By using $\Delta z_{0}$ and $\Delta z$, create the triangular matrix $\mathbf{M}$. After that, compute a data vector $\mathbf{t}_{0}$ by using $\mathbf{M}$ and $\mathbf{s}_{0}$. Then, use $\Delta z_{0}$, $\Delta z$ and $\mathbf{t}_{0}$ to estimate a slowness vector $\mathbf{s}$ by using the function `vsp`. Finally, compare the estimated slowness vector $\mathbf{s}$ and the true slowness vector $\mathbf{s}_{0}$.