#Noções de Python 4

Este notebok é baseado na lição [Matrix Programming](http://software-carpentry.org/v4/matrix/index.html) da [Software Carpentry](http://software-carpentry.org/index.html).

O principal objetivo deste IPython Notebook é apresentar a biblioteca numérica [Numpy](http://www.numpy.org/).

###Como criar um `numpy array` a partir de uma lista

In [1]:
import numpy

In [2]:
lista1 = [2,3,4,5,6,7,8,9]

In [3]:
lista1

[2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
vetor1 = numpy.array(lista1)

In [5]:
vetor1

array([2, 3, 4, 5, 6, 7, 8, 9])

Diferentemente de uma lista, um **numpy array** contém elementos (dados numéricos) do mesmo tipo. Há vários [tipos de dados numéricos](http://docs.scipy.org/doc/numpy/user/basics.types.html#id5). No exemplo acima, todos os elementos são `int32`, tal como mostrado abaixo:

In [6]:
vetor1.dtype

dtype('int32')

Se, ao gerar o `numpy array`, forem passados elementos de diferentes tipos, todos os elementos serão convertidos para tipo mais geral. Por exemplo, considere que a seguinte variável lista:

In [7]:
lista2 = [2,3.56,4,5,6,7,8,9]

In [8]:
lista2

[2, 3.56, 4, 5, 6, 7, 8, 9]

Note que todos os elementos são inteiros, exceto o segundo, que é um `float`. Neste caso, o `numpy array` criado a partir desta lista fica da seguinte forma:

In [9]:
vetor2 = numpy.array(lista2)

In [10]:
vetor2

array([ 2.  ,  3.56,  4.  ,  5.  ,  6.  ,  7.  ,  8.  ,  9.  ])

In [11]:
vetor2.dtype

dtype('float64')

Observe que todos os elementos foram convertidos para um tipo mais geral, que no exemplo acima é um `float64`.

Abaixo segue outro exemplo interessante em que a lista contém 3 tipos diferentes de dados: `int`, `float` e `complex`

In [12]:
lista3 = [2,3.56,4,5,6,7+1j,8,9]

In [13]:
lista3

[2, 3.56, 4, 5, 6, (7+1j), 8, 9]

In [14]:
vetor3 = numpy.array(lista3)

In [15]:
vetor3

array([ 2.00+0.j,  3.56+0.j,  4.00+0.j,  5.00+0.j,  6.00+0.j,  7.00+1.j,
        8.00+0.j,  9.00+0.j])

In [16]:
vetor3.dtype

dtype('complex128')

Note que, no exemplo acima, o tipo mais geral é o `complex`, logo todos os elementos do `vetor3` são `complex`.

É possível especificar o tipo dos dados numéricos do vetor, tal como mostrado abaixo:

In [17]:
vetor4 = numpy.array(lista2, dtype='complex')

In [18]:
vetor4

array([ 2.00+0.j,  3.56+0.j,  4.00+0.j,  5.00+0.j,  6.00+0.j,  7.00+0.j,
        8.00+0.j,  9.00+0.j])

Note que, ao fornecer o `dtype='complex'`, todos os elementos foram convertidos de `float` para `complex`, que é um **tipo mais geral**.

In [19]:
vetor5 = numpy.array(lista2, dtype='int')

In [20]:
vetor5

array([2, 3, 4, 5, 6, 7, 8, 9])

Já neste outro exemplo, os elementos foram convertidos de `float` para `int`, que é um **tipo menos geral**.

###Outros `numpy arrays`

In [21]:
vetor6 = numpy.zeros(5)

In [22]:
vetor6

array([ 0.,  0.,  0.,  0.,  0.])

Este comando cria um vetor com 5 elementos iguais a zero. Se o tipo dos elementos não for especificado, os elementos serão `float`.

In [23]:
matriz1 = numpy.zeros((3,4))

In [24]:
matriz1

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

Neste exemplo, o `shape` do `array` é `(3,4)`, logo será criada uma matriz 3 x 4 com elementos iguais a zero, todos `float`.

Analogamente,

In [25]:
matriz2 = numpy.ones((5,2))

In [26]:
matriz2

array([[ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.]])

In [27]:
matriz3 = numpy.identity(6)

In [28]:
matriz3

array([[ 1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.]])

In [29]:
matriz4 = numpy.diag(lista3)

In [30]:
matriz4

array([[ 2.00+0.j,  0.00+0.j,  0.00+0.j,  0.00+0.j,  0.00+0.j,  0.00+0.j,
         0.00+0.j,  0.00+0.j],
       [ 0.00+0.j,  3.56+0.j,  0.00+0.j,  0.00+0.j,  0.00+0.j,  0.00+0.j,
         0.00+0.j,  0.00+0.j],
       [ 0.00+0.j,  0.00+0.j,  4.00+0.j,  0.00+0.j,  0.00+0.j,  0.00+0.j,
         0.00+0.j,  0.00+0.j],
       [ 0.00+0.j,  0.00+0.j,  0.00+0.j,  5.00+0.j,  0.00+0.j,  0.00+0.j,
         0.00+0.j,  0.00+0.j],
       [ 0.00+0.j,  0.00+0.j,  0.00+0.j,  0.00+0.j,  6.00+0.j,  0.00+0.j,
         0.00+0.j,  0.00+0.j],
       [ 0.00+0.j,  0.00+0.j,  0.00+0.j,  0.00+0.j,  0.00+0.j,  7.00+1.j,
         0.00+0.j,  0.00+0.j],
       [ 0.00+0.j,  0.00+0.j,  0.00+0.j,  0.00+0.j,  0.00+0.j,  0.00+0.j,
         8.00+0.j,  0.00+0.j],
       [ 0.00+0.j,  0.00+0.j,  0.00+0.j,  0.00+0.j,  0.00+0.j,  0.00+0.j,
         0.00+0.j,  9.00+0.j]])

###Criar um `array` de forma automática

In [31]:
vetor7 = numpy.arange(1., 5., 0.5)

In [32]:
vetor7

array([ 1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

Cria um vetor com elementos variando regularmente no intervalo $\left[1.0, 5.0\right[$, com espaçamento de $0.5$.

In [33]:
vetor8 = numpy.linspace(1.,5.,8)

In [34]:
vetor8

array([ 1.        ,  1.57142857,  2.14285714,  2.71428571,  3.28571429,
        3.85714286,  4.42857143,  5.        ])

Cria um vetor com $8$ elementos variando regularmente no intervalo $\left[1.0, 5.0\right]$.

Observe as diferenças entre os comandos `arange` e `linspace`.

###Como criar uma cópia de um `array`

Voltemos ao seguinte exemplo anterior:

In [35]:
matriz1

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

Agora, vamos criar outra matriz com base na `matriz1`

In [36]:
matriz5 = matriz1

In [37]:
matriz5

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

Se modificarmos um dos elementos da `matriz5`, tal como no exemplo abaixo,

In [38]:
matriz5[1][2] = 4.0

In [39]:
matriz5

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  4.,  0.],
       [ 0.,  0.,  0.,  0.]])

a `matriz1` também será modificada

In [40]:
matriz1

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  4.,  0.],
       [ 0.,  0.,  0.,  0.]])

Note que, ao fazer `matriz5 = matriz1`, não é criada uma matriz nova, mas sim outro objeto que **aponta para o mesmo lugar na memória**.

Se o objetivo é realmente fazer uma cópia da `matriz1`, deve-se proceder como no exemplo abaixo:

In [41]:
matriz5 = matriz1.copy()

Dessa forma, se um elemento da `matriz5` for modificado,

In [42]:
matriz5[2][1] = 4.0

In [43]:
matriz5

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  4.,  0.],
       [ 0.,  4.,  0.,  0.]])

A `matriz1` não será modificada,

In [44]:
matriz1

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  4.,  0.],
       [ 0.,  0.,  0.,  0.]])

###Algumas propriedades de `arrays`

In [45]:
matriz1.shape # formato do array

(3L, 4L)

In [46]:
matriz1.size # número de elementos do array

12

In [47]:
matriz1.transpose() # retorna a transposta

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  4.,  0.],
       [ 0.,  0.,  0.]])

In [48]:
matriz1.transpose().shape

(4L, 3L)

In [49]:
matriz1.T # outra notação

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  4.,  0.],
       [ 0.,  0.,  0.]])

In [50]:
matriz1.T.shape

(4L, 3L)

In [51]:
matriz1

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  4.,  0.],
       [ 0.,  0.,  0.,  0.]])

Note que o uso dos comandos `matriz1.comando` não altera a matriz original.

In [52]:
matriz6 = numpy.array([[1., 2., 3.],
                       [4., 5., 6.],
                       [7., 8., 9.],
                       [10., 11., 12.]])

In [53]:
matriz6

array([[  1.,   2.,   3.],
       [  4.,   5.,   6.],
       [  7.,   8.,   9.],
       [ 10.,  11.,  12.]])

In [54]:
matriz6.ravel() # mostra os elementos em sequência

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
        12.])

Note que a sequência adotada pelo Python é por linhas, ou seja, os primeiros elementos são os da primeira linha, depois os da segunda  e assim por diante.

In [55]:
matriz6.reshape(2,6) # altera a forma do array

array([[  1.,   2.,   3.,   4.,   5.,   6.],
       [  7.,   8.,   9.,  10.,  11.,  12.]])

In [56]:
matriz6.reshape(3,6)

ValueError: total size of new array must be unchanged

Note que o `array` com formato modificado deve ter o mesmo número de elementos do `array` original.

In [57]:
numpy.reshape(matriz6, (2,6)) # outra notação

array([[  1.,   2.,   3.,   4.,   5.,   6.],
       [  7.,   8.,   9.,  10.,  11.,  12.]])

Para alterar o formato do `array` de forma que o resultado tenha um número de elementos diferente do original, use `resize`, tal como mostrado abaixo:

In [58]:
numpy.resize(matriz6, (2,3))

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

Neste caso, parte dos elementos é desconsiderada.

In [59]:
numpy.resize(matriz6, (4,5))

array([[  1.,   2.,   3.,   4.,   5.],
       [  6.,   7.,   8.,   9.,  10.],
       [ 11.,  12.,   1.,   2.,   3.],
       [  4.,   5.,   6.,   7.,   8.]])

Neste caso, observe que o `array` resultante tem mais elementos. compare este `array` com o original: 

In [60]:
matriz6

array([[  1.,   2.,   3.],
       [  4.,   5.,   6.],
       [  7.,   8.,   9.],
       [ 10.,  11.,  12.]])

In [61]:
matriz7 = numpy.reshape(numpy.linspace(0.,12.,6), (2,3))

In [62]:
matriz7

array([[  0. ,   2.4,   4.8],
       [  7.2,   9.6,  12. ]])

###Como acessar os elementos de um `array`

In [63]:
vetor2

array([ 2.  ,  3.56,  4.  ,  5.  ,  6.  ,  7.  ,  8.  ,  9.  ])

In [64]:
vetor2[2]

4.0

In [65]:
vetor2[5]

7.0

In [66]:
vetor2[-1]

9.0

In [67]:
vetor2[:] # imprime todos os elementos

array([ 2.  ,  3.56,  4.  ,  5.  ,  6.  ,  7.  ,  8.  ,  9.  ])

In [68]:
vetor2[:2] # começa no elemento 0 e vai até o 1

array([ 2.  ,  3.56])

In [69]:
vetor2[:4] # começa no elemento 0 e vai até o 3

array([ 2.  ,  3.56,  4.  ,  5.  ])

In [70]:
vetor2[2:] # começa no elemento 2 e vai até o último

array([ 4.,  5.,  6.,  7.,  8.,  9.])

In [71]:
vetor2[3:6] # começa no elemento 3 e vai até o 5

array([ 5.,  6.,  7.])

Nos exemplos acima, está implícito que os elementos devem seracessados em sequência. Para especificar o **passo** entre os elementos, faça como nos exemplos abaixo:

In [72]:
vetor2[1:7:2] # começa no elemento 1 e vai até o 6, de 2 em 2

array([ 3.56,  5.  ,  7.  ])

In [73]:
vetor2[-1:-7:-1] # começa no elemento -1 e vai até o -6, de -1 em -1

array([ 9.,  8.,  7.,  6.,  5.,  4.])

In [74]:
vetor2[::-1] # começa no elemento -1 e vai até o primeiro, de trás pra frente

array([ 9.  ,  8.  ,  7.  ,  6.  ,  5.  ,  4.  ,  3.56,  2.  ])

Esta mesma notação pode ser utilizada para `arrays 2D` (matrizes):

In [75]:
matriz6

array([[  1.,   2.,   3.],
       [  4.,   5.,   6.],
       [  7.,   8.,   9.],
       [ 10.,  11.,  12.]])

In [76]:
matriz6[:,2] # coluna 2

array([  3.,   6.,   9.,  12.])

In [77]:
matriz6[2,:] # linha 2

array([ 7.,  8.,  9.])

In [78]:
matriz6[2:,1:] # acessa os elementos a partir da linha 2 e da coluna 1

array([[  8.,   9.],
       [ 11.,  12.]])

In [79]:
matriz6[::2,::2] # acessa os elementos, de forma alternada, tanto nas linhas como nas colunas

array([[ 1.,  3.],
       [ 7.,  9.]])

In [80]:
matriz6[1,:]

array([ 4.,  5.,  6.])

In [81]:
matriz6[1]

array([ 4.,  5.,  6.])

É possível especificar elementos por meio de uma lista da seguinte forma:

In [82]:
vetor2

array([ 2.  ,  3.56,  4.  ,  5.  ,  6.  ,  7.  ,  8.  ,  9.  ])

In [83]:
vetor2[[1,6,2]]

array([ 3.56,  8.  ,  4.  ])

In [84]:
matriz6

array([[  1.,   2.,   3.],
       [  4.,   5.,   6.],
       [  7.,   8.,   9.],
       [ 10.,  11.,  12.]])

In [85]:
matriz6[[0,2],[1,2]] # elementos 01 e 22

array([ 2.,  9.])

Também é possível utilizar um `array` valores booleanos (True e False):

In [86]:
vetor_booleano = numpy.array([True, True, False, False, False, True, True, True])

In [87]:
vetor2[vetor_booleano]

array([ 2.  ,  3.56,  7.  ,  8.  ,  9.  ])

In [88]:
condicao = vetor2 < 6.5

In [89]:
condicao

array([ True,  True,  True,  True,  True, False, False, False], dtype=bool)

In [90]:
vetor2[condicao]

array([ 2.  ,  3.56,  4.  ,  5.  ,  6.  ])

In [91]:
matriz_booleana = numpy.array([[True, True, False],
                               [False, False, True],
                               [True, True, True],
                               [True, False, True]])

In [92]:
matriz6[matriz_booleana]

array([  1.,   2.,   6.,   7.,   8.,   9.,  10.,  12.])

In [93]:
condicao = matriz6 <= 7.

In [94]:
matriz6[condicao]

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.])

###Acessar elementos por meio do comando `for`

In [95]:
matriz6

array([[  1.,   2.,   3.],
       [  4.,   5.,   6.],
       [  7.,   8.,   9.],
       [ 10.,  11.,  12.]])

In [96]:
print matriz6.shape
N = matriz6.shape[0]
M = matriz6.shape[1]
print N, M

(4L, 3L)
4 3


In [97]:
for i in range(N):
    for j in range(M):
        print matriz6[i][j]

1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0
10.0
11.0
12.0


In [98]:
for j in range(M):
    for i in range(N):
        print matriz6[i][j]

1.0
4.0
7.0
10.0
2.0
5.0
8.0
11.0
3.0
6.0
9.0
12.0
